import re, sys

with open('src/data/kanjiData.ts', 'r', encoding='utf-8') as f:
    text1 = f.read()

chars1 = set(re.findall(r'\"japanese\":\s*\"(.*?)\"', text1))
chars2 = set(re.findall(r'japanese:\s*\'(.*?)\'', text1))
all_existing = chars1.union(chars2)

print(f"Current unique Kanji: {len(all_existing)}")

# 235 authentic N3 Kanji to reach 650 total
new_kanji_raw = [
    # (kanji, subCategory, reading, onyomi, kunyomi, meaningId, mnemonic, exampleJp, exampleId, strokes)
    ("受", "kanji_aktivitas", "ukeru / ju", "ジュ (JU)", "う・ける (uke-ru)", "Menerima / Mengikuti Ujian", "Tangan 上 menerima benda dari tangan lain 下", " me-suke 受験 (じゅけん / juken)", "Mengikuti ujian", 8),
    ("付", "kanji_aktivitas", "tsuku / fu", "フ (FU)", "つ・く (tsu-ku), つ・ける (tsu-keru)", "Menempel / Melampirkan", "Orang イ menempelkan tanda pada dinding", "受付 (うけつけ / uketsuke)", "Resepsionis / Bagian Pendaftaran", 5),
    ("呼", "kanji_aktivitas", "yobu / ko", "コ (KO)", "よ・ぶ (yo-bu)", "Memanggil / Bernapas", "Mulut 口 memanggil dengan nada keras", "呼吸 (こきゅう / kokyuu)", "Pernapasan", 8),
    ("頼", "kanji_sosial", "tanomu / rai", "ライ (RAI)", "たの・む (tano-mu), たよ・る (tayo-ru)", "Membantu / Mengandalkan / Meminta", "Halaman 本 dan kepala 頁 mengisyaratkan permohonan bantuan", "依頼 (いらい / irai)", "Permintaan / Permohonan", 16),
    ("渡", "kanji_gerak", "wataru / to", "TO (ト)", "わた・る (wata-ru), わた・す (wata-su)", "Menyeberang / Menyerahkan", "Air 氵 dan perahu 渡 membawa seberang", "渡す (わたす / watasu)", "Menyerahkan barang", 12),
    ("慣", "kanji_kehidupan", "nareru / kan", "カン (KAN)", "な・れる (na-reru)", "Terbiasa / Kebiasaan", "Hati 心 dan konsistensi 貫 menghasilkan kebiasaan", "習慣 (しゅうかん / shuukan)", "Kebiasaan / Adat", 14),
    ("絡", "kanji_sosial", "karamu / raku", "ラク (RAKU)", "から・む (kara-mu)", "Terhubung / Melilit", "Benang 糸 terhubung dengan tempat 各", "連絡 (れんらく / renraku)", "Komunikasi / Hubungan", 12),
    ("差", "kanji_abstrak", "sasu / sa", "サ (SA)", "さ・す (sa-su)", "Perbedaan / Menunjuk", "Domba 羊 dan tangan 工 menunjukkan selisih", "差別 (さべつ / sabetsu)", "Diskriminasi / Perbedaan", 10),
    ("残", "kanji_kehidupan", "nokoru / zan", "ザン (ZAN)", "のこ・る (noko-ru), のこ・す (noko-su)", "Sisa / Menyisakan", "Tulang 歹 dan pisau 戋 menyisakan bagian", "残念 (ざんねん / zannen)", "Sayang sekali / Penyesalan", 10),
    ("勝", "kanji_kompetisi", "katsu / shou", "ショウ (SHOU)", "か・つ (ka-tsu)", "Menang / Unggul", "Bulan 月 dan kekuatan 力 berhasil mengalahkan musuh", "勝負 (しょうぶ / shoubu)", "Pertandingan / Perlombaan", 12),
    ("負", "kanji_kompetisi", "makeru / fu", "フ (FU)", "ま・ける (make-ru), お・う (o-u)", "Kalah / Memikul", "Orang ⺈ membawa kerang 貝 dan merasa terbeban", "勝負 (しょうぶ / shoubu)", "Kalah menang", 9),
    ("続", "kanji_waktu", "tsuduku / zoku", "ゾク (ZOKU)", "つづ・く (tsudu-ku), つづ・ける (tsudu-keru)", "Berlanjut / Meneruskan", "Benang 糸 yang disambung terus 𠮛", "継続 (けいぞく / keizoku)", "Kelanjutan / Kesinambungan", 13),
    ("探", "kanji_aktivitas", "sagasu / tan", "タン (TAN)", "さが・す (saga-su), さぐ・る (sagu-ru)", "Mencari / Menyelidiki", "Tangan 扌 mencari di balik atap 穴", "探す (さがす / sagasu)", "Mencari barang hilang", 11),
    ("祈", "kanji_perasaan", "inoru / ki", "キ (KI)", "いの・る (ino-ru)", "Berdoa / Memohon", "Altar 示 dan kapak 斤 tempat memohon doa", "祈る (いのる / inoru)", "Berdoa", 8),
    ("願", "kanji_perasaan", "negai / gan", "ガン (GAN)", "ねが・う (nega-u)", "Keinginan / Permohonan", "Asal 原 dan kepala 頁 mengharapkan sesuatu", "願い (ねがい / negai)", "Harapan / Keinginan", 19),
    ("祝", "kanji_sosial", "iwai / shuku", "シュク (SHUKU)", "いわ・う (iwa-u)", "Merayakan / Selamat", "Altar 示 dan orang 口 mengucapkan selamat", "お祝い (おいわい / oiwai)", "Perayaan / Hadiah ucapan selamat", 9),
    ("助", "kanji_sosial", "tasukeru / jo", "ジョ (JO)", "たす・ける (tasuke-ru)", "Membantu / Menolong", "Sawah 且 dan kekuatan 力 saling menolong", "助ける (たすける / tasukeru)", "Menolong seseorang", 7),
    ("努", "kanji_aktivitas", "tsutomeru / do", "ド (DO)", "つと・める (tsutome-ru)", "Berusaha keras", "Budak 奴 mengerahkan kekuatan 力", "努力 (どりょく / doryoku)", "Usaha keras / Kerja keras", 7),
    ("効", "kanji_abstrak", "kou", "コウ (KOU)", "き・く (ki-ku)", "Efektif / Berkhasiat", "Pertukaran 交 mengerahkan kekuatan 力", "効果 (こうか / kouka)", "Efek / Khasiat", 8),
    ("働", "kanji_pekerjaan", "hataraku / dou", "ドウ (DOU)", "はたら・く (hatara-ku)", "Bekerja", "Orang イ mengerahkan gerak 重 dan kekuatan 力", "労働 (ろうどう / roudou)", "Tenaga kerja / Buruh", 13),
    ("勧", "kanji_sosial", "susumeru / kan", "カン (KAN)", "すすめ・る (susume-ru)", "Menganjurkan / Mempersuasi", "Burung 雚 dan kekuatan 力 membujuk orang", "勧誘 (かんゆう / kanyuu)", "Bujukan / Ajak bergabung", 13),
    ("恐", "kanji_perasaan", "osoroi / kyou", "キョウ (KYOU)", "おそ・れる (oso-reru), おそ・ろしい (oso-roshii)", "Takut / Khawatir", "Hati 心 gemetar menghadapi bahaya 𢏚", "恐ろしい (おそろしい / osoroshii)", "Mengerikan / Mencekam", 10),
    ("悲", "kanji_perasaan", "kanashii / hi", "ヒ (HI)", "かな・しい (kana-shii)", "Sedih / Duka", "Sayap 非 terpatahkan membuat hati 心 duka", "悲しい (かなしい / kanashii)", "Sedih", 12),
    ("苦", "kanji_perasaan", "kurashii / ku", "ク (KU)", "くる・しい (kuru-shii), にが・い (niga-i)", "Pahit / Menderita", "Tanaman 草 tua 古 rasanya pahit", "苦しい (くるしい / kurushii)", "Menderita / Sesak", 8),
    ("痛", "kanji_kesehatan", "itai / tsuu", "ツウ (TSUU)", "いた・い (ita-i), いた・む (ita-mu)", "Sakit / Nyeri", "Penyakit 疒 di dalam tubuh 通", "痛い (いたい / itai)", "Sakit / Nyeri", 12),
    ("眠", "kanji_kehidupan", "nemuru / min", "ミン (MIN)", "ねむ・る (nemu-ru), ねむ・い (nemu-i)", "Tidur / Mengantuk", "Mata 目 terpejam di malam 民", "睡眠 (すいみん / suimin)", "Tidur nyenyak", 10),
    ("忙", "kanji_kehidupan", "isogashii / bou", "ボウ (BOU)", "いそが・しい (isoga-shii)", "Sibuk", "Hati 忄 tergesa-gesa hingga hilang 亡", "忙しい (いそがしい / isogashii)", "Sibuk", 6),
    ("困", "kanji_kehidupan", "komaru / kon", "コン (KON)", "こま・る (koma-ru)", "Kesulitan / Bingung", "Pohon 木 terkurung dalam pagar 囗", "困難 (こんなん / konnan)", "Kesulitan besar", 7),
    ("疑", "kanji_perasaan", "utagau / gi", "ギ (GI)", "うたが・う (utaga-u)", "Ragu / Curiga", "Orang berdiri menengok mencari kejelasan", "疑問 (ぎもん / gimon)", "Pertanyaan / Keraguan", 14),
    ("怒", "kanji_perasaan", "okoru / do", "ド (DO)", "おこ・る (oko-ru), いかる (ika-ru)", "Marah / Murka", "Wanita 女 dan budak 奴 memendam gusar di hati 心", "怒る (おこる / okoru)", "Marah", 9),
    ("怖", "kanji_perasaan", "kowai / fu", "フ (FU)", "こわ・い (kowa-i)", "Takut / Mencekam", "Hati 忄 merasa terancam kain 布", "恐怖 (きょうふ / kyoufu)", "Rasa takut luar biasa", 8),
    ("照", "kanji_alam", "teru / shou", "ショウ (SHOU)", "て・れる (te-reru), て・らす (te-rasu)", "Sinar / Menerangi", "Matahari 日 dan api 灬 memancarkan cahaya", "照明 (しょうめい / shoumei)", "Penerangan / Lampu", 13),
    ("迷", "kanji_perasaan", "mayou / mei", "メイ (MEI)", "まよ・う (mayo-u)", "Tersesat / Ragu", "Jalan 米 membuat orang bingung di jalan 辶", "迷子 (まいご / maigo)", "Anak tersesat", 9),
    ("驚", "kanji_perasaan", "odoroku / kyou", "キョウ (KYOU)", "おどろ・く (odoro-ku)", "Terkejut / Kaget", "Kuda 馬 melonjak tinggi kaget", "驚く (おどろく / odoroku)", "Kaget / Terkejut", 22),
    ("悩", "kanji_perasaan", "nayamu / nou", "ノウ (NOU)", "なや・む (naya-mu)", "Cemas / Khawatir", "Hati 忄 pusing memikirkan masalah 脳", "悩み (なやみ / nayami)", "Kecemasan / Masalah pikiran", 10),
    ("恥", "kanji_perasaan", "haji / chi", "チ (CHI)", "はじ (haji), はず・かしい (hazu-kashii)", "Malu / Aib", "Telinga 耳 merah menahan malu di hati 心", "恥ずかしい (はずかしい / hazukashii)", "Malu", 10),
    ("浮", "kanji_alam", "ukabu / fu", "フ (FU)", "う・かぶ (u-kabu), う・く (u-ku)", "Mengapung / Melayang", "Air 氵 dan anak 爪 孑 mengapung di permukaan", "浮く (うく / uku)", "Mengapung", 10),
    ("沈", "kanji_alam", "shizumu / chin", "チン (CHIN)", "しず・む (shizu-mu)", "Tenggelam / Redup", "Air 氵 membawa beban 尢 turun tenggelam", "沈む (しずむ / shizumu)", "Tenggelam", 7),
    ("涼", "kanji_alam", "suzushii / ryou", "リョウ (RYOU)", "すず・しい (suzu-shii)", "Sejuk / Dingin nyaman", "Tetes air 氵 di ibu kota 京 membawa sejuk", "涼しい (すずしい / suzushii)", "Sejuk", 11),
    ("暖", "kanji_alam", "atatakai / dan", "ダン (DAN)", "あたた・かい (atata-kai)", "Hangat (Cuaca)", "Matahari 日 membawa kehangatan 爰", "暖房 (だんぼう / danbou)", "Pemanas ruangan", 13),
    ("温", "kanji_alam", "atatakai / on", "オン (ON)", "あたた・かい (atata-kai), あたた・まる (atata-maru)", "Hangat (Benda/Air)", "Air 氵 dalam wadah 皿 membawa hangat", "温度 (おんど / ondo)", "Suhu udara/benda", 12),
    ("冷", "kanji_alam", "tsumetai / rei", "レイ (REI)", "つめ・たい (tsume-tai), ひ・やす (hi-yasu)", "Dingin / Menyejukkan", "Es 冫 dan perintah 令 membekukan cairan", "冷蔵庫 (れいぞうこ / reizouko)", "Kulkas / Lemari es", 7),
    ("湿", "kanji_alam", "shimeru / shitsu", "シツ (SHITSU)", "しめ・る (shime-ru)", "Lembab / Basah", "Air 氵 dan matahari 日 tertutup embun 顕", "湿度 (しつど / shitsudo)", "Kelembapan udara", 12),
    ("乾", "kanji_alam", "kawaku / kan", "カン (KAN)", "かわ・く (kawa-ku), かわ・かす (kawa-kasu)", "Kering / Menyerap", "Matahari 朝 mengeringkan tanah", "乾燥 (かんそう / kansou)", "Kering / Pengeringan", 11),
    ("薄", "kanji_sifat", "usui / haku", "ハク (HAKU)", "うす・い (usu-i)", "Tipis / Hambar", "Rumput 草 air 氵 tipis menyebar", "薄い (うすい / usui)", "Tipis / Rasa hambar", 16),
    ("濃", "kanji_sifat", "koi / nou", "ノウ (NOU)", "こ・い (ko-i)", "Pekat / Kental", "Air 氵 dan pertanian 農 menghasilkan kepekatannya", "濃い (こい / koi)", "Kental / Pekat", 16),
    ("豊", "kanji_sifat", "yutaka / hou", "ホウ (HOU)", "ゆた・か (yuta-ka)", "Kaya / Berkelimpahan", "Wadah 曲 berisi hasil panen 豆 melimpah", "豊富 (ほうふ / houfu)", "Melimpah ruah", 13),
    ("富", "kanji_sifat", "tomi / fu", "フ (FU), フウ (FUU)", "とみ (tomi), と・む (to-mu)", "Kaya / Kemakmuran", "Rumah 宀 berisi kekayaan 田 dan harta", "豊富 (ほうふ / houfu)", "Kaya / Berkelimpahan", 12),
    ("貧", "kanji_sifat", "mashii / hin", "ヒン (HIN), ビン (BIN)", "mazu-shii", "Miskin / Kekurangan", "Membagi 分 kerang 貝 hingga berkurang", "貧しい (まずしい / mazushii)", "Miskin / Serba kurang", 11),
    ("弱", "kanji_sifat", "yowai / jaku", "ジャク (JAKU)", "よわ・い (yowa-i)", "Lemah / Rapuh", "Dua busur 弓 dan bulu 彡 belum cukup kuat", "弱点 (じゃくてん / jakuten)", "Kelemahan / Titik lemah", 10),
    ("浅", "kanji_sifat", "asai / sen", "セン (SEN)", "あさ・い (asa-i)", "Dangkal", "Air 氵 sedikit dangkal di tepian 戋", "浅い (あさい / asai)", "Dangkal", 8),
    ("深", "kanji_sifat", "fukai / shin", "シン (SHIN)", "ふか・い (fuka-i)", "Dalam / Mendalam", "Air 氵 di dalam gua 穴 dan pohon 木", "深刻 (しんこく / shinkoku)", "Serius / Mendalam", 11),
    ("細", "kanji_sifat", "hosoi / sai", "サイ (SAI)", "ほそ・い (hoso-i), こま・かい (koma-kai)", "Halus / Kecil / Detail", "Benang 糸 dipotong kecil 田", "細かい (こまかい / komakai)", "Rinci / Detail kecil", 11),
    ("太", "kanji_sifat", "futoi / tai", "タイ (TAI), タ (TA)", "ふと・い (futo-i)", "Gemuk / Tebal", "Besar 大 dengan titik penjelas", "太平洋 (たいへいよう / taiheiyou)", "Samudra Pasifik", 4),
    ("硬", "kanji_sifat", "katai / kou", "コウ (KOU)", "かた・い (kata-i)", "Keras / Kaku", "Batu 石 yang diproses 𠮈 terasa keras", "硬い (かたい / katai)", "Keras", 12),
    ("軟", "kanji_sifat", "yawaraka / nan", "ナン (NAN)", "やわ・らか (yawa-raka)", "Lunak / Lembut", "Roda 車 dan panah 欠 bergerak lentur", "柔軟 (じゅうなん / juunan)", "Fleksibel / Lembut", 11),
    ("鋭", "kanji_sifat", "sabolai / ei", "エイ (EI)", "わる・い / すば・やい", "Tajam / Kritis", "Logam 金 yang diasah tajam 兌", "鋭い (するどい / surudoi)", "Tajam", 15),
    ("鈍", "kanji_sifat", "nibui / don", "ドン (DON)", "にぶ・い (nibu-i)", "Tumpul / Lamban", "Logam 金 yang tumpul 屯", "鈍い (にぶい / nibui)", "Tumpul / Lambat merespon", 12),
    ("幼", "kanji_sifat", "osanai / you", "ヨウ (YOU)", "おさな・い (osana-i)", "Balita / Masih Kecil", "Benang 幼 dan kekuatan 力 anak kecil", "幼児 (ようじ / youji)", "Anak balita", 5),
    ("老", "kanji_sosial", "oiru / rou", "ロウ (ROU)", "お・いる (o-iru), ふ・ける (fuke-ru)", "Tua / Lansia", "Orang tua tongkat berdiri kokoh", "老人 (ろうじん / roujin)", "Lansia / Orang tua", 6),
    ("若", "kanji_sifat", "wakarai / jaku", "ジャク (JAKU), ニャク (NYAKU)", "わか・い (waka-i)", "Muda / Remaja", "Rumput 草 muda yang baru tumbuh 右", "若い (わかい / wakai)", "Muda", 8),
    ("貴", "kanji_sifat", "tattobi / ki", "キ (KI)", "たっと・い (tatto-i)", "Mewah / Mulia", "Kerang 貝 berharga mahal 𠀐", "貴重 (きちょう / kichou)", "Sangat berharga", 12),
    ("尊", "kanji_sosial", "toutoi / son", "ソン (SON)", "とうと・い (touto-i)", "Hormat / Agung", "Botol anggur 酋 diletakkan di atas panggung 寸", "尊敬 (そんけい / sonkei)", "Rasa hormat", 12),
    ("敬", "kanji_sosial", "umau / kei", "ケイ (KEI), キョウ (KYOU)", "うやま・う (uyama-u)", "Menghormati", "Anak 苟 dan pimpinan 攵 saling menghormati", "敬語 (けいご / keigo)", "Bahasa halus/sopan", 12),
    ("礼", "kanji_sosial", "rei / rai", "レイ (REI), ライ (RAI)", "おれい", "Sopan Santun / Etiket", "Altar 示 dan penundukan diri 乚", "お礼 (おれい / orei)", "Ucapan terima kasih", 5),
    ("義", "kanji_abstrak", "gi", "ギ (GI)", "-", "Kebenaran / Keadilan", "Domba 羊 dan tombak 我 simbol keadilan", "義務 (ぎむ / gimu)", "Kewajiban", 13),
    ("徳", "kanji_abstrak", "toku", "トク (TOKU)", "-", "Kebajikan / Morality", "Langkah 彳 dan hati 直 yang jujur", "道徳 (どうとく / doutoku)", "Moralitas", 14),
    ("仁", "kanji_abstrak", "jin", "ジン (JIN), ニ (NI)", "-", "Kebaikan Hati / Cinta Kasih", "Dua orang イ 二 saling mengasihi", "仁義 (じんぎ / jingi)", "Nilai kemanusiaan", 4),
    ("誠", "kanji_abstrak", "makoto / sei", "セイ (SEI)", "まこと (makoto)", "Kejujuran / Tulus", "Bicara 言 sesuai kenyataan 成", "誠実 (せいじつ / seijitsu)", "Jujur dan tulus", 13),
    ("善", "kanji_abstrak", "yoshi / zen", "ゼン (ZEN)", "よ・い (yo-i)", "Kebaikan / Kebajikan", "Domba 羊 dan tutur kata 言 yang baik", "改善 (かいぜん / kaizen)", "Perbaikan berkesinambungan", 12),
    ("悪", "kanji_perasaan", "warui / aku", "アク (AKU), オ (O)", "わる・い (waru-i)", "Buruk / Jahat", "Atap 亜 dan hati 心 yang jahat", "悪魔 (あくま / akuma)", "Iblis / Kejahatan", 11),
    ("罪", "kanji_sosial", "tsumi / zai", "ザイ (ZAI)", "つみ (tsumi)", "Dosa / Kejahatan", "Jaring 网 menahan orang bersalah 非", "犯罪 (はんざい / hanzai)", "Tindak kejahatan", 13),
    ("罰", "kanji_sosial", "batsu / bachi", "バツ (BATSU), バチ (BACHI)", "-", "Hukuman / Sanksi", "Jaring 网 bicara 言 dan pisau 刀 memberi sanksi", "罰金 (ばっきん / bakkin)", "Denda uang", 14),
    ("許", "kanji_sosial", "yurusu / kyo", "キョ (KYO)", "ゆる・す (yuru-su)", "Mengingatkan / Memaafkan / Izin", "Bicara 言 dengan jelas 午 memberi izin", "許可 (きょか / kyoka)", "Izin resmi", 11),
    ("認", "kanji_abstrak", "nomeru / nin", "ニン (NIN)", "pro・める", "Mengakui / Menyetujui", "Bicara 言 dan pedang 忍 menyetujui", "確認 (かくにん / kakunin)", "Konfirmasi", 14),
    ("誤", "kanji_abstrak", "ayamaru / go", "ゴ (GO)", "あやま・る (ayama-ru)", "Kesalahan / Keliru", "Bicara 言 yang membingungkan 呉", "誤解 (ごかい / gokai)", "Salah paham", 14),
    ("拾", "kanji_aktivitas", "hiroi / shuu", "シュウ (SHUU), ジュウ (JUU)", "ひろ・う (hiro-u)", "Pemungutan / Mengambil", "Tangan 扌 mengumpulkan 合 barang jatuh", "拾う (ひろう / hirou)", "Memungut barang", 9),
    ("捨", "kanji_aktivitas", "suteru / sha", "シャ (SHA)", "す・てる (su-teru)", "Mebuang / Melepas", "Tangan 扌 membuang barang di rumah 舎", "捨て分 (すてぶち / sutebuchi)", "Membuang sampah", 11),
    ("投", "kanji_aktivitas", "nage / tou", "トウ (TOU)", "な・げる (nage-ru)", "Melempar / Investasi", "Tangan 扌 melempar barang 殳", "投票 (とうひょう / touhyou)", "Pemungutan suara", 7),
    ("打", "kanji_aktivitas", "utsu / da", "ダ (DA)", "う・つ (u-tsu)", "Memukul / Mengetik", "Tangan 扌 memukul paku 丁", "打つ (打つ / utsu)", "Memukul / Mengetik", 5),
    ("押", "kanji_aktivitas", "osu / ou", "オウ (OU)", "お・す (o-su), お・さえる (o-saeru)", "Menekan / Mendorong", "Tangan 扌 menekan tombol 甲", "押す (おす / osu)", "Menekan tombol", 8),
    ("抱", "kanji_aktivitas", "daku / hou", "ホウ (HOU)", "だ・く (da-ku),抱・く (ida-ku)", "Memeluk / Memeluk harapan", "Tangan 扌 merangkul 包", "抱く (だく / daku)", "Memeluk", 8),
    ("支", "kanji_aktivitas", "sasaeru / shi", "シ (SHI)", "ささ・える (sasa-eru)", "Menyokong / Membayar", "Tangan memegang cabang pendukung", "支店 (してん / shiten)", "Cabang toko", 4),
    ("払", "kanji_aktivitas", "harau / futsu", "フツ (FUTSU)", "はら・う (hara-u)", "Membayar / Membersihkan", "Tangan 扌 menyapu 厶", "支払い (しはらい / shiharai)", "Pembayaran", 5),
    ("掘", "kanji_aktivitas", "horu / kutsu", "クツ (KUTSU)", "ほ・る (ho-ru)", "Menggali / Membongkar", "Tangan 扌 menggali tanah 屈", "掘る (ほる / horu)", "Menggali tanah", 11),
    ("捕", "kanji_aktivitas", "tsukamaeru / ho", "ホ (HO)", "つか・まえる (tsuka-maeru), と・らえる (to-raeru)", "Menangkap / Mengamankan", "Tangan 扌 menangkap buronan 甫", "逮捕 (たいほ / taiho)", "Penangkapan polisi", 10),
    ("握", "kanji_aktivitas", "nigiru / aku", "アク (AKU)", "にぎ・る (nigi-ru)", "Mengepal / Memegang", "Tangan 扌 menggenggam 屋", "握手 (あくしゅ / akushu)", "Jabat tangan", 12),
    ("振", "kanji_aktivitas", "furu / shin", "シン (SHIN)", "ふ・る (fu-ru), ふ・りかえる (fu-rikaeru)", "Mengayun / Mengocok", "Tangan 扌 mengayunkan 辰", "振動 (しんどう / shindou)", "Getaran", 10),
    ("揮", "kanji_aktivitas", "ki", "キ (KI)", "ふる・う", "Mengendalikan / Mengayun", "Tangan 扌 memandu pasukan 揮", "指揮 (しき / shiki)", "Instruksi / Komando", 12),
    ("操", "kanji_aktivitas", "操る / sou", "ソウ (SOU)", "あやつ・る (ayatsu-ru)", "Mengendalikan / Kemudi", "Tangan 扌 mengarahkan tiga burung 品 木", "操作 (そうさ / sousa)", "Pengoperasian alat", 16),
    ("提", "kanji_aktivitas", "sageru / tei", "テイ (TEI)", "さ・げる (sage-ru)", "Mengajukan / Menenteng", "Tangan 扌 membawa barang 是", "提案 (ていあん / teian)", "Usul / Proposal", 12),
    ("掲", "kanji_aktivitas", "kageru / kei", "ケイ (KEI)", "かか・げる (kaka-geru)", "Memasang / Memajang", "Tangan 扌 memajang pengumuman 曷", "掲示板 (けいじばん / keijiban)", "Papan pengumuman", 12),
    ("捜", "kanji_aktivitas", "sagasu / sou", "ソウ (SOU)", "さが・す (saga-su)", "Pelacakan / Penyelidikan", "Tangan 扌 melacak keberadaan 叟", "捜査 (そうさ / sousa)", "Penyelidikan kepolisian", 10),
    ("摘", "kanji_aktivitas", "tsumu / teki", "テキ (TEKI)", "つ・む (tsu-mu)", "Mementik / Mengkritik", "Tangan 扌 memetik buah 適", "指摘 (してき / shiteki)", "Penunjukan kesalahan", 14),
    ("摩", "kanji_abstrak", "ma", "マ (MA)", "す・れる", "Gesekan / Memoles", "Rumah 麻 dan tangan 手 menggesek", "摩擦 (まさつ / masatsu)", "Gesekan sosial/fisik", 15),
    ("擦", "kanji_abstrak", "suru / satsu", "サツ (SATSU)", "す・る (su-ru)", "Mengusap / Menggores", "Rumah 察 dan tangan 手 menggosok", "摩擦 (まさつ / masatsu)", "Gesekan", 17),
    ("敷", "kanji_kehidupan", "shiku / fu", "フ (FU)", "し・く (shi-ku)", "Gelar / Hampar Tatami", "Memasang dan menggelar karpet 攴", "敷地 (しきち / shikichi)", "Kawasan / Lahan", 15),
    ("畳", "kanji_kehidupan", "tatami / jou", "ジョウ (JOU)", "たたみ (tatami), たた・む (tata-mu)", "Matras Tatami / Melipat", "Tiga bidang 田 dilipat rapi", "畳 (たたみ / tatami)", "Matras jerami Jepang", 12),
    ("散", "kanji_aktivitas", "chiru / san", "サン (SAN)", "ち・る (chi-ru), ち・らかす (chi-rakasu)", "Berserak / Jalan-jalan", "Daging 月 dan kapak 散 berhamburan", "散歩 (さんぽ / sampo)", "Jalan-jalan santai", 12),
    ("詰", "kanji_aktivitas", "tsumu / kitsu", "キツ (KITSU)", "つ・まる (tsuma-ru), つ・める (tsume-ru)", "Sumbat / Penuh padat", "Bicara 言 di tempat 吉 hingga penuh", "詰める (つめる / tsumeru)", "Mengkemas rapat", 13),
    ("込", "kanji_gerak", "komu", "-", "こ・む (ko-mu), こ・める (kome-ru)", "Masuk padat / Mengisi", "Jalan 辶 masuk ke dalam 人", "人込 (ひとごみ / hitogomi)", "Kerumunan orang", 5),
    ("折", "kanji_aktivitas", "oru / setsu", "セツ (SETSU)", "お・る (o-ru), お・れる (o-reru)", "Melipat / Patah", "Tangan 扌 dan kapak 斤 mematahkan cabang", "骨折 (こっせつ / kossetsu)", "Patah tulang", 7),
    ("破", "kanji_aktivitas", "yaburu / ha", "ハ (HA)", "やぶ・る (yabu-ru)", "Robek / Rusak", "Batu 石 merobek kain 皮", "破壊 (はかい / hakai)", "Kerusakan fatal", 10),
    ("割", "kanji_aktivitas", "wari / katsu", "カツ (KATSU)", "わ・る (wa-ru), わり (wari)", "Membagi / Potongan", "Rumah 害 dan pisau 刀 membagi", "割合 (わりあい / wariai)", "Rasio / Persentase", 12),
    ("裂", "kanji_aktivitas", "sakaru / retsu", "レツ (RETSU)", "さ・ける (sake-ru)", "Terbelah / Sobek", "Baju 衣 terbelah dua 列", "分裂 (ぶんれつ / bunretsu)", "Perpecahan", 12),
    ("砕", "kanji_aktivitas", "kudaku / sai", "サイ (SAI)", "くだ・く (kuda-ku)", "Hancur berkeping", "Batu 石 dihantam卒 hingga pecah", "砕く (くだく / kudaku)", "Menghancurkan", 9),
    ("減", "kanji_abstrak", "heru / gen", "ゲン (GEN)", "へ・る (he-ru), へ・らす (he-rasu)", "Berkurang / Mengurangi", "Air 氵 dan tombak 咸 berkurang", "減少 (げんしょう / genshou)", "Penurunan jumlah", 12),
    ("増", "kanji_abstrak", "fueru / zou", "ゾウ (ZOU)", "ふ・える (fue-ru), ふ・やす (fue-yasu)", "Bertambah / Meningkat", "Tanah 土 bertumpuk 曽 makin banyak", "増加 (ぞうか / zouka)", "Peningkatan", 14),
    ("満", "kanji_abstrak", "michiru / man", "マン (MAN)", "み・ちる (michi-ru)", "Penuh / Puas", "Air 氵 memenuhi wadah 𡃬", "満足 (まんぞく / manzoku)", "Puas / Terpenuhi", 12),
    ("漏", "kanji_alam", "漏れる / rou", "ロウ (ROU)", "も・れる (mo-reru)", "Bocor / Merembes", "Air 氵 menetes dari rumah 尸 雨", "雨漏り (あまもり / amamori)", "Atap bocor kena hujan", 14),
    ("滴", "kanji_alam", "shizuku / teki", "テキ (TEKI)", "しずく (shizuku)", "Tetesan air", "Air 氵 menetes dari atap 商", "水滴 (すいてき / suiteki)", "Tetesan air", 14),
    ("沸", "kanji_alam", "wakaru / futsu", "フツ (FUTSU)", "わ・く (wa-ku), わ・かす (wa-kasu)", "Mendidih", "Air 氵 bergolak 弗 mendidih", "沸騰 (ふっとう / futtou)", "Mendidih gelora", 8),
    ("湧", "kanji_alam", "waku / yuu", "ユウ (YUU), トウ (TOU)", "わ・く (wa-ku)", "Pancar / Sembur air", "Air 氵 memancar dari dalam tanah 勇", "湧き水 (わきみず / wakimizu)", "Mata air alami", 12),
    ("溶", "kanji_alam", "tokeru / you", "ヨウ (YOU)", "と・ける (toke-ru), と・かす (toka-su)", "Larut / Meleleh", "Air 氵 melarutkan zat 容", "溶ける (とける / tokeru)", "Larut dalam air", 13),
    ("凝", "kanji_alam", "kori / gyou", "ギョウ (GYOU)", "こ・る (ko-ru)", "Membeku / Konsentrasi", "Es 冫 membekukan cairan 疑", "凝縮 (ぎょうしゅく / gyoushuku)", "Kondensasi / Pembekuan", 16),
    ("蒸", "kanji_alam", "musu / jou", "ジョウ (JOU)", "む・す (mu-su)", "Mengukus / Penguapan", "Rumput 草 air 氵 dan api 灬 menguap", "蒸気 (じょうき / jouki)", "Uap air", 13),
    ("濁", "kanji_alam", "nigoru / daku", "ダク (DAKU)", "にご・る (nigo-ru)", "Keruh / Buram", "Air 氵 bercampur lumpur 蜀", "濁る (にごる / nigoru)", "Air keruh", 16),
    ("澄", "kanji_alam", "sumu / chou", "チョウ (CHOU)", "す・む (su-mu)", "Jernih / Bening", "Air 氵 jernih di sungai 登", "澄む (すむ / sumu)", "Air jernih bening", 15),
    ("染", "kanji_kehidupan", "somaru / sen", "セン (SEN)", "そ・める (some-ru), そ・まる (soma-ru)", "Mewarnai / Mewarnai kain", "Air 氵 dan sembilan 九 tanaman 木 mewarnai", "感染 (かんせん / kansen)", "Infeksi / Tertular", 9),
    ("漂", "kanji_alam", "tadayou / hyou", "ヒョウ (HYOU)", "ただよ・う (tadayo-u)", "Hanyut / Mengapung", "Air 氵 membawa tiket 票 hanyut", "漂流 (ひょうりゅう / hyouryuu)", "Hanyut di laut", 14),
    ("崩", "kanji_alam", "kuzureru / hou", "ホウ (HOU)", "くず・れる (kuzu-reru)", "Runtuh / Roboh", "Gunung 山 runtuh diterjang 朋", "崩壊 (ほうかい / houkai)", "Keruntuhan total", 11),
    ("荒", "kanji_alam", "arasai / kou", "コウ (KOU)", "あら・い (ara-i), あら・す (ara-su)", "Ganas / Liar / Rusak", "Rumput 草 liar memusnahkan 亡 川", "荒い (あらい / arai)", "Ganas / Ombak besar", 9),
    ("倒", "kanji_gerak", "taoreru / tou", "トウ (TOU)", "たお・れる (tao-reru), たお・す (tao-su)", "Tumbang / Roboh", "Orang イ dan menara 到 roboh", "倒産 (とうさん / tousan)", "Bangkrut", 10),
    ("損", "kanji_abstrak", "son", "ソン (SON)", "そこ・なう (soko-nau)", "Rugi / Kerusakan", "Tangan 扌 dan uang 員 rusak rugi", "損害 (そんがい / songai)", "Kerugian materi", 10),
    ("暴", "kanji_perasaan", "abakeru / bou", "ボウ (BOU), バク (BAKU)", "あば・れる (aba-reru)", "Kekerasan / Ngamuk", "Matahari 日 dan air 氺 menimbulkan kekacauan", "暴力 (ぼうりょく / bouryoku)", "Kekerasan fisik", 15),
    ("撃", "kanji_aktivitas", "utsu / geki", "ゲキ (GEKI)", "う・つ (u-tsu)", "Menembak / Hantaman", "Kereta 車 dan tangan 手 menghantam musuh", "攻撃 (こうげき / kougeki)", "Serangan", 15),
    ("射", "kanji_aktivitas", "itsuru / sha", "シャ (SHA)", "い・つ (i-tsu)", "Melesat / Memancar", "Badan 身 dan panah 寸 meluncurkan anak panah", "発射 (はっしゃ / hassha)", "Peluncuran / Tembakan", 10),
    ("攻", "kanji_aktivitas", "semeru / kou", "コウ (KOU)", "せ・める (se-meru)", "Menerang / Mengkritik", "Kerja 工 dan senjata 攵 menyerang", "攻撃 (こうげき / kougeki)", "Serangan", 7),
    ("防", "kanji_aktivitas", "fusegu / bou", "ボウ (BOU)", "ふせ・ぐ (fuse-gu)", "Mencegah / Bertahan", "Bukit 阝 dan pagar 方 menahan musuh", "防止 (ぼうし / boushi)", "Pencegahan", 7),
    ("避", "kanji_aktivitas", "sakeru / hi", "ヒ (HI)", "さ・ける (sake-ru)", "Menghindari / Mengungsi", "Jalan 辶 membawa jauh dari bahaya 辟", "避難 (ひなん / hinan)", "Evakuasi / Mengungsi", 16),
    ("警", "kanji_sosial", "kei", "ケイ (KEI)", "-", "Waspada / Polisi", "Bicara 言 yang tegas 敬 mengingatkan bahaya", "警察 (けいさつ / keisatsu)", "Kepolisian", 19),
    ("守", "kanji_sosial", "mamoru / shu", "シュ (SHU), ス (SU)", "まも・る (mamo-ru)", "Melindungi / Menjaga", "Atap 宀 melindungi rumah 寸", "留守 (るす / rusu)", "Rumah kosong (pergi)", 6),
    ("救", "kanji_sosial", "sukuu / kyuu", "キュウ (KYUU)", "すく・う (suku-u)", "Menyelamatkan", "Membantu 求 dengan kekuatan 攵", "救急車 (きゅうきゅうしゃ / kyuukyuusha)", "Mobil Ambulans", 11),
    ("逃", "kanji_gerak", "nigeru / tou", "トウ (TOU)", "に・げる (nige-ru), に・がす (niga-su)", "Kabur / Melarikan diri", "Jalan 辶 melarikan diri dari musuh 兆", "逃げる (にげる / nigeru)", "Melarikan diri", 9),
    ("追", "kanji_gerak", "oi / tsui", "ツイ (TSUI)", "お・う (o-u)", "Mengejar / Menyusul", "Jalan 辶 mengejar prajurit 𠂤", "追加 (ついか / tsuika)", "Penambahan / Susulan", 9),
    ("越", "kanji_gerak", "kosu / etsu", "エツ (ETSU)", "こ・す (ko-su), こ・える (koe-ru)", "Melampaui / Menyeberang", "Lari 走 dan kapak 戉 melompati batasan", "引っ越し (ひっこし / hikkoshi)", "Pindah rumah", 12),
    ("導", "kanji_sosial", "michibiku / dou", "ドウ (DOU)", "みちび・く (michibi-ku)", "Membimbing / Menuntun", "Jalan 道 dan petunjuk 寸 memandu arah", "指導 (しどう / shidou)", "Bimbingan / Pengarahan", 15),
    ("招", "kanji_sosial", "maneku / shou", "ショウ (SHOU)", "まね・く (mane-ku)", "Mengundang / Mengajak", "Tangan 扌 dan mulut 口 memanggil tamu", "招待 (しょうたい / shoutai)", "Undangan resmi", 8),
    ("誘", "kanji_sosial", "saso / yuu", "ユウ (YUU)", "さそ・う (saso-u)", "Mengajak / Mengundang", "Bicara 言 dan tanaman 秀 membujuk teman", "誘導 (ゆうどう / yuudou)", "Pengarahan / Panduan", 14),
    ("迎", "kanji_sosial", "mukaeru / gei", "ゲイ (GEI)", "むか・える (mukae-ru)", "Menyambut", "Jalan 辶 menyambut kedatangan 卬", "歓迎 (かんげい / kangei)", "Penyambutan hangat", 7),
    ("戻", "kanji_gerak", "modoru / rei", "レイ (REI)", "もど・る (modo-ru), もど・す (modo-su)", "Kembali / Mengembalikan", "Pintu 房 tertutup menahan kembali 大", "戻る (もどる / modoru)", "Kembali ke tempat asal", 7),
    ("換", "kanji_aktivitas", "kaeru / kan", "カン (KAN)", "か・える (ka-eru), か・わる (ka-waru)", "Tukar / Mengganti", "Tangan 扌 menukar barang 奐", "交換 (こうかん / koukan)", "Pertukaran", 12),
    ("替", "kanji_aktivitas", "kaeru / tai", "タイ (TAI)", "か・える (ka-eru), か・わる (ka-waru)", "Mengganti / Berganti", "Dua orang 夫 夫 bergantian di bawah matahari 日", "両替 (りょうがえ / ryougae)", "Penukaran mata uang", 12),
    ("旅", "kanji_kehidupan", "tabi / ryo", "リョ (RYO)", "たび (tabi)", "Perjalanan / Wisata", "Bendera 方 dan prajurit 𠂤 bepergian", "旅行 (りょこう / ryokou)", "Wisata / Bepergian", 10),
    ("訪", "kanji_sosial", "tazuneru / hou", "ホウ (HOU)", "たず・ねる (tazu-neru)", "Mengunjungi", "Bicara 言 di pintu 方 mengunjungi tuan rumah", "訪問 (ほうもん / houmon)", "Kunjungan resmi", 11),
    ("宿", "kanji_kehidupan", "yado / shuku", "シュク (SHUKU)", "やど (yado)", "Penginapan / Asrama", "Rumah 宀 dan tikar 百 tempat menginap", "宿泊 (しゅくはく / shukuhaku)", "Menginap di hotel", 11),
    ("泊", "kanji_kehidupan", "tomaru / haku", "ハク (HAKU)", "と・まる (toma-ru), と・める (toma-reru)", "Menginap (Semalam)", "Air 氵 dan putih 白 berlabuh menginap", "一泊 (いっぱく / ippaku)", "Menginap satu malam", 8),
    ("留", "kanji_sosial", "todomaru / ryuu", "リュウ (RYUU), ル (RU)", "と・まる (todo-maru), と・める (todo-meru)", "Tinggal / Menahan", "Membajak 卯 sawah 田 tetap menetap", "留学 (りゅうがく / ryuugaku)", "Studi di luar negeri", 10),
    ("居", "kanji_kehidupan", "iru / kyo", "キョ (KYO)", "い・る (i-ru)", "Tinggal / Berada", "Tubuh 尸 di rumah 古 tempat bermukim", "居間 (いま / ima)", "Ruang keluarga", 8),
    ("在", "kanji_abstrak", "aru / zai", "ザイ (ZAI)", "あ・る (a-ru)", "Berada / Eksis", "Tanah 土 dan kayu 才 ada di lokasi", "存在 (そんざい / sonzai)", "Keberadaan / Eksistensi", 6),
    ("存", "kanji_abstrak", "son / zon", "ソン (SON), ゾン (ZON)", "-", "Eksis / Menyimpan", "Anak 子 dipelihara 才 hidup terus", "保存 (ほぞん / hozon)", "Penyimpanan data", 6),
    ("象", "kanji_alam", "zou / shou", "ゾウ (ZOU), ショウ (SHOU)", "-", "Gajah / Fenomena / Simbol", "Bentuk badan gajah besar", "印象 (いんしょう / inshou)", "Kesan pertama", 12),
    ("表", "kanji_abstrak", "omote / hyou", "ヒョウ (HYOU)", "おもて (omote), あらわ・す (arawa-su)", "Permukaan / Tabel / Menunjukkan", "Baju 衣 bagian luar 龶", "発表 (はっぴょう / happyou)", "Presentasi pengumuman", 8),
    ("裏", "kanji_abstrak", "ura / ri", "リ (RI)", "うら (ura)", "Bagian Belakang / Sisi Dalam", "Bagian dalam baju 衣 di desa 里", "裏口 (うらぐち / uraguchi)", "Pintu belakang", 13),
    ("面", "kanji_abstrak", "omote / men", "メン (MEN)", "おもて (omote), つら (tsura)", "Wajah / Bidang / Sisi", "Garis bingkai 頁 membingkai wajah", "面接 (めんせつ / mensetsu)", "Wawancara kerja", 9),
    ("側", "kanji_abstrak", "gawa / soku", "ソク (SOKU)", "がわ (gawa), そば (soba)", "Sisi / Samping", "Orang イ berdiri di samping 則", "右側 (みぎがわ / migigawa)", "Sisi sebelah kanan", 11),
    ("角", "kanji_abstrak", "kado / kaku", "カク (KAKU)", "かど (kado), つの (tsuno)", "Sudut / Tanduk", "Bentuk tanduk hewan tajam", "角度 (かくど / kakudo)", "Sudut derajat", 7),
    ("隅", "kanji_abstrak", "sumi / guu", "グウ (GUU)", "すみ (sumi)", "Pojok ruangan", "Bukit 阝 dan rumah 禺 di pojokan", "隅 (すみ / sumi)", "Pojokan kamar", 12),
    ("端", "kanji_abstrak", "hashi / tan", "タン (TAN)", "はし (hashi), は (ha)", "Ujung / Pinggir", "Berdiri 立 di sisi gunung 端", "先端 (せんたん / sentan)", "Teknologi paling ujung/terdepan", 14),
    ("縁", "kanji_abstrak", "fuchi / en", "エン (EN)", "ふち (fuchi)", "Pinggiran / Ikatan Takdir", "Benang 糸 mengikat hubungan 彖", "縁 (えん / en)", "Ikatan takdir / Hubungan", 15),
    ("枠", "kanji_abstrak", "waku", "-", "わく (waku)", "Bingkai / Batasan", "Kayu 木 membingkai sembilan 九 puluh", "枠 (わく / waku)", "Bingkai / Kuota batas", 8),
    ("帯", "kanji_kehidupan", "obi / tai", "タイ (TAI)", "おび (obi), お・びる (o-biru)", "Sabuk Obi / Zona", "Kain ikatan pinggang obi", "携帯 (けいたい / keitai)", "Telepon genggam", 10),
    ("境", "kanji_alam", "sakai / kyou", "キョウ (KYOU), ケイ (KEI)", "さかい (sakai)", "Batasan / Perbatasan", "Tanah 土 di kawasan 音 児", "環境 (かんきょう / kankyou)", "Lingkungan hidup", 14),
    ("域", "kanji_alam", "iki", "イキ (IKI)", "-", "Kawasan / Wilayah", "Tanah 土 yang dilindungi 惑", "地域 (ちいき / chiiki)", "Wilayah lokal", 11),
    ("圏", "kanji_alam", "ken", "ケン (KEN)", "-", "Jangkauan / Zona", "Pagar 囗 mengurung 蜷 kawasan", "首都圏 (しゅとけん / shutoken)", "Kawasan metropolitan", 12),
    ("庁", "kanji_sosial", "chou", "チョウ (CHOU)", "-", "Badan / Instansi Pemerintah", "Gedung 庁 instansi", "県庁 (けんちょう / kenchou)", "Kantor gubernur/prefektur", 5),
    ("府", "kanji_sosial", "fu", "フ (FU)", "-", "Kantor Pemerintahan Prefektur", "Gedung 广 menyimpan dokumen 付", "Government 府", "Pemerintahan prefektur perkotaan", 8),
    ("県", "kanji_sosial", "ken", "ケン (KEN)", "-", "Prefektur / Provinsi", "Mata 目 diikat benang 糸", "県 (けん / ken)", "Prefektur Jepang", 9),
    ("市", "kanji_sosial", "shi / ichi", "シ (SHI)", "いち (ichi)", "Kota / Pasar", "Topi 亠 dan kain 巾 pasar kota", "市民 (しみん / shimin)", "Warga kota", 5),
    ("区", "kanji_sosial", "ku", "ク (KU)", "-", "Kecamatan / Distrik Kota", "Waduk 匚 membagi wilayah メ", "区役所 (くやくしょ / kuyakusho)", "Kantor distrik/kecamatan", 4),
    ("村", "kanji_sosial", "mura / son", "ソン (SON)", "むら (mura)", "Desa / Kampung", "Pohon 木 di desa 寸", "農村 (のうそん / nouson)", "Desa pertanian", 7),
    ("島", "kanji_alam", "shima / tou", "トウ (TOU)", "しま (shima)", "Pulau", "Burung 鳥 di atas gunung 山", "半島 (はんとう / hantou)", "Semenanjung pulau", 10),
    ("陸", "kanji_alam", "riku / roku", "リク (RIKU)", "おか (oka)", "Daratan / Benua", "Bukit 阝 dan tanah tinggi 睦", "大陸 (たいりく / tairiku)", "Benua", 11),
    ("州", "kanji_alam", "su / shuu", "シュウ (SHUU)", "す (su)", "Negara Bagian / Wilayah", "Sungai 川 dengan gundukan pasir 川", "九州 (きゅうしゅう / kyuushuu)", "Pulau Kyushu", 6),
    ("港", "kanji_alam", "minato / kou", "コウ (KOU)", "みなと (minato)", "Pelabuhan", "Air 氵 dan lorong 巷 pelabuhan", "空港 (くうこう / kuukou)", "Bandar udara", 12),
    ("湾", "kanji_alam", "wan", "ワン (WAN)", "-", "Teluk Laut", "Air 氵 melengkung 弯 teluk", "東京湾 (とうきょうわん / toukyouwan)", "Teluk Tokyo", 12),
    ("岸", "kanji_alam", "kishi / gan", "ガン (GAN)", "きし (kishi)", "Pesisir / Tepi Laut", "Gunung 山 dan tebing 干 pantai", "海岸 (かいがん / kaigan)", "Pesisir pantai", 8),
    ("浜", "kanji_alam", "hama / hin", "ヒン (HIN)", "はま (hama)", "Pantai Berpasir", "Air 氵 di pantai 兵", "横浜 (よこはま / yokohama)", "Kota Yokohama", 10),
    ("砂", "kanji_alam", "suna / sa", "サ (SA), シャ (SHA)", "すな (suna)", "Pasir", "Batu 石 kecil 少 halus", "砂漠 (さばく / sabaku)", "Padang pasir", 9),
    ("丘", "kanji_alam", "oka / kyuu", "キュウ (KYUU)", "おか (oka)", "Bukit Rendah", "Bentuk bukit landai di tanah", "丘 (おか / oka)", "Bukit", 5),
    ("谷", "kanji_alam", "tani / koku", "コク (KOKU)", "たに (tani)", "Lembah / Jurang", "Air memancar 八 di antara gunung 口", "谷 (たに / tani)", "Lembah hijau", 7),
    ("泉", "kanji_alam", "izumi / sen", "セン (SEN)", "いずみ (izumi)", "Mata Air Jernih", "Air 白 pancaran 水 jernih", "温泉 (おんせん / onsen)", "Pemandian air panas", 9),
    ("原", "kanji_alam", "hara / gen", "ゲン (GEN)", "はら (hara)", "Padang Rumput / Asal Muasal", "Tebing 厂 dan mata air 泉", "原料 (げんりょう / genryou)", "Bahan mentah", 10),
    ("苗", "kanji_pertanian", "nae / byou", "ビョウ (BYOU)", "なえ (nae)", "Bibit Tanaman", "Rumput 草 tumbuh di sawah 田", "苗 (なえ / nae)", "Bibit padi/tanaman", 8),
    ("牧", "kanji_pertanian", "maki / boku", "ボク (BOKU)", "まき (maki)", "Peternakan", "Sapi 牛 diurus orang 攵", "牧場 (ぼくじょう / bokujou)", "Lahan peternakan", 8),
    ("草", "kanji_alam", "kusa / sou", "ソウ (SOU)", "くさ (kusa)", "Rumput", "Tanaman 草 tumbuh di bawah matahari 早", "雑草 (ざっそう / zassou)", "Rumput liar", 9),
    ("葉", "kanji_alam", "ha / you", "ヨウ (YOU)", "は (ha), ば (ba)", "Daun", "Tanaman 草 dan pohon 木 berdaun", "紅葉 (こうよう / kouyou)", "Daun musim gugur merah", 12),
    ("花", "kanji_alam", "hana / ka", "カ (KA), ケ (KE)", "はな (hana)", "Bunga", "Rumput 草 yang berubah 化 indah", "花火 (はなび / hanabi)", "Kembang api", 7),
    ("華", "kanji_sifat", "hana / ka", "カ (KA), ゲ (GE)", "はな (hana)", "Megah / Mewah / Bunga", "Bunga 艹 berkembang indah 十 十", "豪華 (ごうか / gouka)", "Mewah megah", 10),
    ("芽", "kanji_alam", "me / ga", "ガ (GA)", "め (me)", "Tunas / Kecambah", "Rumput 草 bertunas 牙", "芽 (め / me)", "Tunas daun", 8),
    ("咲", "kanji_alam", "saku / shou", "ショウ (SHou)", "さ・く (sa-ku)", "Mekar (Bunga)", "Mulut 口 tersenyum 関 mekar", "咲く (さく / saku)", "Bunga mekar", 9),
    ("枯", "kanji_alam", "kare / ko", "コ (KO)", "かれ・る (kare-ru)", "Layu / Kering", "Pohon 木 tua 古 layu", "枯れる (かれる / kareru)", "Tanaman layu", 9),
    ("種", "kanji_pertanian", "tane / shu", "シュ (SHU)", "たね (tane)", "Biji / Benih / Jenis", "Gandum 禾 dan berat 重 biji", "種類 (しゅるい / shurui)", "Jenis / Kategori", 14),
    ("類", "kanji_abstrak", "rui", "ルイ (RUI)", "-", "Kategori / Jenis", "Biji 種 dan kepala 頁 sejenis", "人類 (じんるい / jinrui)", "Umat manusia", 18),
    ("粒", "kanji_pertanian", "tsubu / ryuu", "リュウ (RYUU)", "つぶ (tsubu)", "Butiran", "Beras 米 berdiri 立 butiran", "粒 (つぶ / tsubu)", "Butir air/beras", 10),
    ("材", "kanji_industri", "zai", "ザイ (ZAI)", "-", "Bahan / Kayu / Material", "Pohon 木 bernilai 才 material", "材料 (ざいりょう / zairyou)", "Bahan baku resep/bangunan", 7),
    ("板", "kanji_industri", "ita / han", "ハン (HAN), バン (BAN)", "いた (ita)", "Papan Kayu", "Pohon 木 dibuat rata 反", "看板 (かんばん / kamban)", "Papan reklame / Toko", 8),
    ("柱", "kanji_bangunan", "hashira / chuu", "チュウ (CHUU)", "はしら (hashira)", "Pilar / Tiang Utama", "Pohon 木 pemberi cahaya 主", "電柱 (でんちゅう / denchuu)", "Tiang listrik", 9),
    ("梁", "kanji_bangunan", "hari / ryou", "リョウ (RYOU)", "はり (hari)", "Balok Atap / Jembatan", "Kayu 木 menyeberangi air 氵", "橋梁 (きょうりょう / kyouryou)", "Jembatan struktur", 11),
    ("房", "kanji_bangunan", "fusa / bou", "ボウ (BOU)", "ふさ (fusa)", "Kamar / Ruangan / Tandan", "Pintu 房 menuju ruangan 方", "暖房 (だんぼう / danbou)", "Pemanas ruang", 8),
    ("倉", "kanji_bangunan", "kura / sou", "ソウ (SOU)", "くら (kura)", "Gudang Penyimpanan", "Atap 𠆢 dan gudang 囗 口", "倉庫 (そうこ / souko)", "Gudang barang", 10),
    ("庫", "kanji_bangunan", "kura / ko", "コ (KO), ク (KU)", "-", "Gudang Mobil / Garasi", "Gedung 广 menyimpan kendaraan 車", "金庫 (きんこ / kinko)", "Brankas besi", 10),
    ("塔", "kanji_bangunan", "tou", "トウ (TOU)", "-", "Menara / Pagoda", "Tanah 土 bertumpuk tinggi 荅", "塔 (とう / tou)", "Menara tinggi", 12),
    ("城", "kanji_bangunan", "shiro / jou", "ジョウ (JOU)", "しろ (shiro)", "Istana / Kastil", "Tanah 土 sempurna 成 jadi kastil", "城 (しろ / shiro)", "Kastil Jepang", 9),
    ("橋", "kanji_bangunan", "hashi / kyou", "キョウ (KYOU)", "はし (hashi)", "Jembatan", "Pohon 木 tinggi 喬 menyeberang", "歩道橋 (ほどうきょう / hodoukyou)", "Jembatan penyeberangan", 16),
    ("堤", "kanji_bangunan", "tsutsumi / tei", "テイ (TEI)", "つつみ (tsutsumi)", "Tanggul Penahan Air", "Tanah 土 menahan air 是", "防波堤 (ぼうはてい / bouhatei)", "Tanggul pemecah ombak", 12),
    ("坊", "kanji_sosial", "bou / bocchan", "ボウ (BOU), ボッ (BOTSU)", "-", "Biksu / Anak laki-laki", "Tanah 土 di kuil 方", "坊さん (ぼうさん / bousan)", "Biksu Buddha", 7),
    ("穴", "kanji_alam", "ana / ketsu", "ケツ (KETSU)", "あな (ana)", "Lubang / Gua", "Atap 宀 dan kaki 八 lubang tanah", "穴 (あな / ana)", "Lubang", 5),
    ("溝", "kanji_bangunan", "mizo / kou", "コウ (KOU)", "みぞ (mizo)", "Parit / Saluran Air", "Air 氵 mengalir di parit 構", "排水溝 (はいすいこう / haisuikou)", "Saluran pembuangan air", 13),
    ("井", "kanji_bangunan", "i / sei", "セイ (SEI), ショウ (SHOU)", "い (i)", "Sumur Air", "Bentuk kisi-kisi sumur tradisional", "井戸 (いど / ido)", "Sumur air minum", 4),
    ("池", "kanji_alam", "ike / chi", "チ (CHI)", "いけ (ike)", "Kolam Air", "Air 氵 menampung cairan 也", "電池 (でんち / denchi)", "Batu baterai", 6),
    ("沼", "kanji_alam", "numa / shou", "ショウ (SHOU)", "ぬま (numa)", "Rawa-rawa", "Air 氵 di tanah rawa 召", "沼 (ぬま / numa)", "Rawa-rawa", 8),
    ("船", "kanji_transportasi", "fune / sen", "セン (SEN)", "ふね (fune), ふな (funa)", "Kapal Laut", "Perahu 舟 membawa penumpang 沿", "船長 (せんちょう / senchou)", "Kapten kapal", 11),
    ("舟", "kanji_transportasi", "fune / shuu", "シュウ (SHUU)", "ふね (fune)", "Perahu Kecil", "Bentuk sampan kayu tradisional", "小舟 (こぶね / kobune)", "Sampan kecil", 6),
    ("艦", "kanji_transportasi", "kan", "カン (KAN)", "-", "Kapal Perang Besar", "Perahu 舟 berukuran raksasa 監", "軍艦 (ぐんかん / gunkan)", "Kapal perang", 21),
    ("荷", "kanji_kehidupan", "ni / ka", "カ (KA)", "に (ni)", "Barang Bawaan / Paket", "Tanaman 草 dipikul orang 何", "荷物 (にもつ / nimotsu)", "Barang bawaan / bagasi", 10),
    ("袋", "kanji_kehidupan", "fukuro / tai", "タイ (TAI)", "ふくろ (fukuro)", "Kantong / Tas", "Baju 代 tertutup 衣 jadi kantong", "手袋 (てぶくろ / tebukuro)", "Sarung tangan", 11),
    ("箱", "kanji_kehidupan", "hako / sou", "ソウ (SOU)", "はこ (hako)", "Kotak / Dus", "Bambu 竹 dipasang rapi 相 jadi kotak", "ゴミ箱 (ごみばこ / gomibako)", "Tempat sampah", 15),
    ("缶", "kanji_kehidupan", "kan", "カン (KAN)", "-", "Kaleng", "Wadah logam penyimpanan", "缶詰 (かんづめ / kandzume)", "Makanan kaleng", 6),
    ("瓶", "kanji_kehidupan", "bin", "ビン (BIN)", "かめ (kame)", "Botol Kaca", "Wadah 瓦 berisi cairan 并", "花瓶 (かびん / kabin)", "Vas bunga", 11),
    ("皿", "kanji_kehidupan", "sara / bei", "ベイ (BEI)", "さら (sara)", "Piring Makanan", "Bentuk piring saji mendatar", "灰皿 (はいざら / haizara)", "Asbak rokok", 5),
    ("箸", "kanji_kehidupan", "hashi / cho", "チョ (CHO)", "はし (hashi)", "Sumpit Makan", "Bambu 竹 dipegang orang 著", "箸 (はし / hashi)", "Sumpit makan kayu", 15),
    ("鉢", "kanji_kehidupan", "hachi / hatsu", "ハツ (HATSU), ハチ (HACHI)", "はち (hachi)", "Mangkuk Besar / Pot", "Logam 金 berbentuk mangkuk 本", "植木鉢 (うえきばち / uekibachi)", "Pot tanaman", 13),
    ("壺", "kanji_kehidupan", "tsubo / ko", "コ (KO)", "つぼ (tsubo)", "Guci / Tempayan", "Wadah guci berleher sempit", "壺 (つぼ / tsubo)", "Guci keramik", 12),
    ("傘", "kanji_kehidupan", "kasa / san", "サン (SAN)", "かさ (kasa)", "Payung", "Bentuk atap payung dengan empat kaki", "傘 (かさ / kasa)", "Payung hujan", 12),
    ("履", "kanji_kehidupan", "haku / ri", "リ (RI)", "は・く (ha-ku)", "Memakai Sepatu/Alas Kaki", "Tubuh 尸 memakai sepatu 復", "履物 (はきもの / hakimono)", "Alas kaki / sepatu", 15),
    ("靴", "kanji_kehidupan", "kutsu / ka", "カ (KA)", "くつ (kutsu)", "Sepatu", "Kulit 革 dibentuk sepatu 化", "靴下 (くつした / kutsushita)", "Kaus kaki", 13),
    ("服", "kanji_kehidupan", "fuku", "フク (FUKU)", "-", "Pakaian / Baju / Obat", "Bulan 月 dan tubuh 卩 memakai baju", "洋服 (ようふく / youfuku)", "Pakaian gaya barat", 8),
    ("装", "kanji_kehidupan", "yosoi / sou", "ソウ (SOU), ショウ (SHOU)", "よそお・う (yosoo-u)", "Pakaian / Dekorasi", "Ksatria 壮 memakai pakaian 衣", "服装 (ふくそう / fukusou)", "Gaya berpakaian", 12),
    ("衣", "kanji_kehidupan", "koromo / i", "イ (I), エ (E)", "ころも (koromo)", "Pakaian Tradisional / Lapisan Tepung", "Bentuk jubah baju tradisional", "衣服 (いふく / ifuku)", "Pakaian busana", 6),
    ("束", "kanji_kehidupan", "taba / sokoku", "ソク (SOKU)", "たば (taba)", "Ikat / Tandan", "Kayu 木 diikat kencang 口", "約束 (やくそく / yakusoku)", "Janji", 7),
    ("包", "kanji_kehidupan", "tsutsumu / hou", "ホウ (HOU)", "つつ・む (tsutsu-mu)", "Membungkus / Paket", "Bayi dalam kandungan membungkus", "小包 (こづつみ / kodzutsumi)", "Paket pos kecil", 5),
    ("紐", "kanji_kehidupan", "himo / juu", "ジュウ (JUU)", "ひも (himo)", "Tali Pengikat", "Benang 糸 diikatkan 紐", "紐 (ひも / himo)", "Tali kain/sepatu", 13),
    ("糸", "kanji_kehidupan", "ito / shi", "シ (SHI)", "いと (ito)", "Benang", "Bintik serat benang terpilin", "糸 (いと / ito)", "Benang jahit", 6),
    ("綿", "kanji_industri", "wata / men", "メン (MEN)", "わた (wata)", "Kapas / Kain Katun", "Benang 糸 dan kain putih 白 katun", "木綿 (もめん / momen)", "Kain katun kapas", 14),
    ("絹", "kanji_industri", "kinu / ken", "ケン (KEN)", "きぬ (kinu)", "Kain Sutra", "Benang 糸 sutra dari ulat 絹", "絹 (きぬ / kinu)", "Sutra halus", 13),
    ("毛", "kanji_alam", "ke / mou", "モウ (MOU)", "け (ke)", "Bulu / Rambut Hewan", "Bentuk helai bulu lembut", "毛布 (もうふ / moufu)", "Selimut bulu hangat", 4),
    ("皮", "kanji_alam", "kawa / hi", "ヒ (HI)", "かわ (kawa)", "Kulit Buah / Kulit Tubuh", "Tangan menguliti lapisan luar", "皮膚 (ひふ / hifu)", "Kulit tubuh manusia", 5),
    ("革", "kanji_industri", "kawa / kaku", "カク (KAKU)", "かわ (kawa)", "Kulit Olahan (Leather)", "Kulit 𠂤 disamak jadi sepatu", "革靴 (かわぐつ / kawagutsu)", "Sepatu kulit", 9),
    ("鉄", "kanji_industri", "tetsu", "テツ (TETSU)", "-", "Besi Logam", "Logam 金 yang hitam kuat 失", "地下鉄 (ちかてつ / chikatetsu)", "Kereta bawah tanah", 13),
    ("銅", "kanji_industri", "dou", "ドウ (DOU)", "あかがね", "Tembaga (Bronze)", "Logam 金 sama 同 tembaga", "銅メダル (どうメダル / dou medaru)", "Medali perunggu", 14),
    ("銀", "kanji_industri", "gin", "ギン (GIN)", "しろがね", "Perak (Silver)", "Logam 金 yang berkilau 艮", "銀行 (ぎんこう / ginkou)", "Bank keuangan", 14),
    ("鉱", "kanji_industri", "kou", "コウ (KOU)", "-", "Batu Tambang / Ore", "Logam 金 melimpah 广", "鉱物 (こうぶつ / koubutsu)", "Mineral tambang", 13),
    ("炭", "kanji_industri", "sumi / tan", "タン (TAN)", "すみ (sumi)", "Batu Bara / Arang", "Gunung 山 dan api 火 arang", "石炭 (せきたん / sekitan)", "Batu bara", 9),
    ("油", "kanji_kehidupan", "abura / yu", "ユ (YU), ユウ (YUU)", "あぶら (abura)", "Minyak", "Air 氵 dari botol 由 minyak", "醤油 (しょうゆ / shouyu)", "Kecap asin Jepang", 8),
    ("脂", "kanji_kesehatan", "abura / shi", "シ (SHI)", "あぶら (abura)", "Lemak Tubuh", "Daging 月 yang mengandung lemak 旨", "脂肪 (しぼう / shibou)", "Lemak tubuh", 10),
    ("燃", "kanji_alam", "moeru / nen", "ネン (NEN)", "も・える (mo-eru), も・やす (mo-yasu)", "Bakar / Menyala", "Api 火 membakar bahan 然", "燃料 (ねんりょう / nenryou)", "Bahan bakar", 16),
    ("焼", "kanji_kehidupan", "yaku / shou", "ショウ (SHOU)", "や・く (ya-ku), や・ける (ya-keru)", "Memanggang / Burn", "Api 火 memanggang makanan 尭", "焼き肉 (やきにく / yakiniku)", "Daging panggang", 12),
    ("煙", "kanji_alam", "kemuri / en", "エン (EN)", "けむり (kemuri), けむ・い (kemu-i)", "Asap", "Api 火 dan tanah  smoke", "禁煙 (きんえん / kinen)", "Dilarang merokok", 13),
    ("灰", "kanji_alam", "hai / kai", "カイ (KAI)", "はい (hai)", "Abu sisa sisa pembakaran", "Tangan 𠂇 mengambil sisa api 火", "灰皿 (はいざら / haizara)", "Asbak abu rokok", 6),
    ("炎", "kanji_alam", "honoo / en", "エン (EN)", "ほのお (honoo)", "Kobaran Api", "Dua api 火 火 berkobar hebat", "炎症 (えんしょう / enshou)", "Peradangan / Inflamasi", 8),
    ("爆", "kanji_alam", "baku", "バク (BAKU)", "-", "Ledakan", "Api 火 meledakkan 暴", "爆発 (ばくはつ / bakuhatsu)", "Ledakan hebat", 19),
    ("震", "kanji_alam", "furu / shin", "シン (SHIN)", "ふる・える (furu-eru)", "Gempa / Gemetar", "Hujan 雨 dan guntur 辰 menggetarkan", "地震 (じしん / jishin)", "Gempa bumi", 15),
    ("災", "kanji_alam", "wasawai / sai", "サイ (SAI)", "わざわい (wazawai)", "Bencana / Musibah", "Sungai 川 dan api 火 musibah", "災害 (さいがい / saigai)", "Bencana alam", 7),
    ("害", "kanji_abstrak", "gai", "ガイ (GAI)", "-", "Kerugian / Bahaya", "Rumah 宀 dan senjata 口 merusak", "被害 (ひがい / higai)", "Kerugian bencana", 10),
    ("命", "kanji_kehidupan", "inochi / mei", "メイ (MEI), ミョウ (MYOU)", "いのち (inochi)", "Nyawa / Jiwa / Perintah", "Atap 𠆢 dan mulut 口 memberi perintah hidup", "生命 (せいめい / seimei)", "Kehidupan nyawa", 8),
    ("福", "kanji_sosial", "fuku", "フク (FUKU)", "-", "Keberuntungan / Kebahagiaan", "Altar 示 berisi wadah 田 kebahagiaan", "幸福 (こうふく / koufuku)", "Kebahagiaan hidup", 13),
    ("望", "kanji_perasaan", "nozomu / bou", "ボウ (BOU), モウ (MOU)", "のぞ・む (nozo-mu)", "Berharap / Memandang", "Bulan 月 dan orang 王 memandang harapan", "希望 (きぼう / kibou)", "Harapan / Cita-cita", 11),
    ("夢", "kanji_perasaan", "yume / mu", "ム (MU)", "ゆめ (yume)", "Mimpi", "Mata 夕 tertutup di malam dream", "夢 (ゆめ / yume)", "Mimpi indah / impian", 13),
    ("志", "kanji_perasaan", "kokorozashi / shi", "シ (SHI)", "こころざし (kokorozashi)", "Cita-cita / Tekat", "Berdiri 士 dengan tekad bulat di hati 心", "意志 (いし / ishi)", "Kehendak tekad kuat", 7),
    ("企", "kanji_pekerjaan", "koku / ki", "キ (KI)", "くわだ・てる (kuwada-teru)", "Merencanakan / Perusahaan", "Orang 𠆢 berdiri 止 merancang", "企業 (きぎょう / kigyou)", "Perusahaan bisnis", 6),
    ("算", "kanji_abstrak", "san", "サン (SAN)", "-", "Menghitung / Kalkulasi", "Bambu 竹 dan alat sempoa 弄", "計算 (けいさん / keisan)", "Perhitungan matematis", 14),
    ("測", "kanji_abstrak", "hakaru / soku", "ソク (SOKU)", "はか・る (haka-ru)", "Mengukur Panjang/Luas", "Air 氵 dan aturan 則 mengukur", "測定 (そくてい / sokutei)", "Pengukuran tepat", 12),
    ("量", "kanji_abstrak", "hakaru / ryou", "リョウ (RYOU)", "はか・る (haka-ru)", "Kapasitas / Bobot Jumlah", "Matahari 日 dan timbangan 里", "大量 (たいりょう / tairyou)", "Jumlah dalam skala besar", 12),
    ("試", "kanji_aktivitas", "tameshi / shi", "シ (SHI)", "ため・す (tame-su), こころ・みる (kokoro-miru)", "Mencoba / Ujian", "Bicara 言 dan hukum 式 menguji", "試験 (しけん / shiken)", "Ujian / Tes", 13),
    ("査", "kanji_aktivitas", "sa", "サ (SA)", "-", "Memeriksa / Audit", "Pohon 木 dan kayu 且 diperiksa teliti", "調査 (ちょうさ / chousa)", "Survei / Penyelidikan", 9),
    ("察", "kanji_aktivitas", "satsu", "サツ (SATSU)", "-", "Mengamati / Meneliti", "Rumah 宀 dan altar 祭 mengamati", "警察 (けいさつ / keisatsu)", "Kepolisian", 14),
    ("講", "kanji_pekerjaan", "kou", "コウ (KOU)", "-", "Kuliah / Ceramah", "Bicara 言 dalam forum  voice", "講義 (こうぎ / kougi)", "Kuliah akademis", 17),
    ("論", "kanji_abstrak", "ron", "ロン (RON)", "-", "Teori / Diskusi", "Bicara 言 yang terstruktur 侖", "論文 (ろんぶん / rombun)", "Skripsi / Jurnal ilmiah", 15),
    ("述", "kanji_abstrak", "noberu / jutsu", "ジュツ (JUTSU)", "のべ・る (nobe-ru)", "Menyatakan / Menguraikan", "Jalan 辶 dan kuas 朮 menuliskan penjelasan", "記述 (きじゅつ / kijutsu)", "Deskripsi tulisan", 8),
    ("語", "kanji_kehidupan", "kataru / go", "ゴ (GO)", "かた・る (kata-ru), かた・らう (kata-rau)", "Bahasa / Bercerita", "Bicara 言 tentang lima 吾 hal", "日本語 (にほんご / nihongo)", "Bahasa Jepang", 14),
    ("説", "kanji_abstrak", "tojo / setsu", "セツ (SETSU), セイ (SEI)", "と・く (to-ku)", "Menjelaskan / Teori", "Bicara 言 dengan gembira 兌 menerangkan", "説明 (せつめい / setsumei)", "Penjelasan", 14),
    ("訳", "kanji_abstrak", "wake / yaku", "ヤク (YAKU)", "わけ (wake)", "Menerjemahkan / Alasan", "Bicara 言 untuk meluruskan 尺", "翻訳 (ほんやく / honyaku)", "Penerjemahan teks", 11),
    ("判", "kanji_abstrak", "han / ban", "ハン (HAN), バン (BAN)", "-", "Keputusan / Cap Stampel", "Separuh 半 dipotong pisau 刀", "判断 (はんだん / handan)", "Keputusan / Penilaian", 7),
    ("断", "kanji_abstrak", "tatoweru / dan", "ダン (DAN)", "た・つ (ta-tsu), ことわ・る (kotowa-ru)", "Memutus / Menolak", "Benang 𢇇 dipotong kapak 斤", "判断 (はんだん / handan)", "Keputusan tegas", 11),
    ("確", "kanji_abstrak", "tashika / kaku", "カク (KAKU)", "たしか (tashika), たしか・める (tashika-meru)", "Pasti / Memastikan", "Batu 石 yang kukuh 隺", "確認 (かくにん / kakunin)", "Konfirmasi / Cek ulang", 15),
    ("証", "kanji_abstrak", "shou", "ショウ (SHOU)", "-", "Bukti / Sertifikat", "Bicara 言 yang benar 正 jadi bukti", "証明 (しょうめい / shoumei)", "Bukti resmi / Sertifikasi", 12),
    ("挙", "kanji_aktivitas", "ageru / kyo", "キョ (KYO)", "あ・げる (a-geru), あ・がる (a-garu)", "Mengangkat / Menggelar", "Tangan 手 mengangkat barang 興", "選挙 (せんきょ / senkyo)", "Pemilu / Pemilihan umum", 10),
    ("供", "kanji_sosial", "sonaeru / kyou", "キョウ (KYOU), ク (KU)", "そな・える (sona-eru), とも (tomo)", "Menyediakan / Pengikut", "Orang イ menyediakan persembahan 共", "提供 (ていきょう / teikyou)", "Penyediaan / Sponsor", 8),
    ("承", "kanji_sosial", "uketamawaru / shou", "ショウ (SHOU)", "うけたまわ・る (uketamawa-ru)", "Menerima / Menyetujui (Sopan)", "Tangan menerima air mengalir 𠄎", "承諾 (しょうだく / shoudaku)", "Persetujuan resmi", 8),
    ("諾", "kanji_sosial", "daku", "ダク (DAKU)", "-", "Persetujuan", "Bicara 言 setuju 若", "承諾 (しょうだく / shoudaku)", "Persetujuan", 15),
    ("拒", "kanji_sosial", "kobarimu / kyo", "キョ (KYO)", "こば・む (koba-mu)", "Menolak tegas", "Tangan 扌 menahan raksasa 巨", "拒否 (きょひ / kyohi)", "Penolakan tegas", 8),
    ("否", "kanji_abstrak", "iia / hi", "ヒ (HI)", "いな (ina)", "Tidak / Menolak", "Mulut 口 berkata tidak 不", "拒否 (きょひ / kyohi)", "Penolakan", 7),
    ("辞", "kanji_sosial", "yameru / ji", "ジ (JI)", "や・める (yame-ru)", "Mundur / Kamus / Kata", "Lidah 舌 dan kait 辛 mengundurkan diri", "辞書 (じしょ / jisho)", "Kamus bahasa", 13),
    ("可", "kanji_abstrak", "ka", "カ (KA)", "-", "Boleh / Memungkinkan", "Mulut 口 menyetujui 口", "可能 (かのう / kanou)", "Mungkin terjadi / Kompatibel", 5),
    ("制", "kanji_sosial", "sei", "セイ (SEI)", "-", "Sistem / Mengatur", "Memotong 牛 dengan pisau 刀 sesuai aturan", "制度 (せいど / seido)", "Sistem / Pranata", 8),
    ("限", "kanji_abstrak", "kagiru / gen", "ゲン (GEN)", "かぎ・る (kagi-ru)", "Batas / Terbatas", "Bukit 阝 menahan batasan 艮", "限界 (げんかい / genkai)", "Batas kemampuan", 9),
    ("禁", "kanji_sosial", "kin", "キン (KIN)", "-", "Larangan keras", "Hutan 林 di area sakral 示 dilarang", "禁止 (きんし / kinshi)", "Dilarang keras", 13),
    ("犯", "kanji_sosial", "okasu / han", "ハン (HAN)", "おか・す (oka-su)", "Melanggar / Kejahatan", "Anjing 犭 menyerang orang 卩", "犯罪 (はんざい / hanzai)", "Tindak pidana", 5),
    ("獄", "kanji_sosial", "goku", "ゴク (GOKU)", "-", "Penjara", "Dua anjing 犭 犬 menjaga tahanan 言", "地獄 (じごく / jigoku)", "Neraka / Penjara", 14),
    ("裁", "kanji_sosial", "sabaku / sai", "サイ (SAI)", "さば・く (saba-ku)", "Adil / Memutus Hukum", "Baju 衣 dipotong kapak 𢦏", "裁判 (さいばん / saiban)", "Persidangan pengadilan", 12),
    ("審", "kanji_sosial", "shin", "シン (SHIN)", "-", "Sidang / Penyelidikan", "Rumah 宀 meneliti hal 審", "審判 (しんぱん / shimpan)", "Wasit / Juri persidangan", 15),
    ("訴", "kanji_sosial", "sutaeru / so", "ソ (SO)", "うった・える (utta-eru)", "Menuntut / Mengadu", "Bicara 言 mengadukan hal 斥", "訴訟 (そしょう / soshou)", "Gugatan hukum", 12),
    ("競", "kanji_kompetisi", "kisou / kyou", "キョウ (KYOU), ケイ (KEI)", "きそ・う (kiso-u), くら・べる (kura-beru)", "Bersaing / Berlomba", "Dua orang 兄 兄 berlari cepat", "競争 (きょうそう / kyousou)", "Persaingan / Kompetisi", 20),
    ("争", "kanji_kompetisi", "arasou / sou", "ソウ (SOU)", "あらそ・う (araso-u)", "Berebut / Pertengkaran", "Tangan 爫 berebut barang 亅", "戦争 (せんそう / sensou)", "Peperangan", 6),
    ("闘", "kanji_kompetisi", "tatakau / tou", "トウ (TOU)", "たたか・う (tataka-u)", "Pertarungan sengit", "Pintu 門 pertarungan 豆 寸", "闘争 (とうそう / tousou)", "Perjuangan keras", 18),
    ("討", "kanji_aktivitas", "utsu / tou", "トウ (TOU)", "う・つ (u-tsu)", "Membahas / Membasmi", "Bicara 言 dengan tegas 寸", "討論 (とうろん / touron)", "Diskusi / Debat", 10),
    ("戦", "kanji_kompetisi", "tatakau / sen", "セン (SEN)", "たたか・う (tataka-u), いくさ (ikusa)", "Perang / Bertanding", "Senjata 単 dan tombak 戈 berjuang", "戦争 (せんそう / sensou)", "Perang dunia", 13),
    ("敗", "kanji_kompetisi", "yabureru / hai", "ハイ (HAI)", "やぶ・れる (yabu-reru)", "Kekalahan", "Kerang 貝 hancur dipukul 攵", "失敗 (しっぱい / shippai)", "Kegagalan", 11),
    ("利", "kanji_abstrak", "kiku / ri", "リ (RI)", "き・く (ki-ku)", "Keuntungan / Tajam", "Gandum 禾 dipotong pisau 刀", "利用 (りよう / riyou)", "Penggunaan / Pengambilan manfaat", 7),
    ("栄", "kanji_abstrak", "sakaeru / ei", "エイ (EI)", "さか・える (saka-eru), は・え (hae)", "Kejayaan / Kehormatan", "Bunga 栄 mekar di pohon 木", "栄光 (えいこう / eikou)", "Kejayaan", 9),
    ("誉", "kanji_abstrak", "homare / yo", "ヨ (YO)", "ほま・れ (homare)", "Pujian / Kehormatan", "Bicara 言 memuji 興 orang", "名誉 (めいよ / meiyo)", "Reputasi / Kehormatan", 13),
    ("賞", "kanji_sosial", "shou", "ショウ (SHOU)", "-", "Penghargaan / Hadiah", "Rumah 尚 memberi kerang 貝", "賞品 (しょうひん / shouhin)", "Hadiah pemenang", 15),
    ("功", "kanji_abstrak", "kou", "コウ (KOU), ク (KU)", "-", "Jasa / Prestasi", "Kerja 工 mengerahkan kekuatan 力", "成功 (せいこう / seikou)", "Keberhasilan / Sukses", 5),
    ("績", "kanji_abstrak", "seki", "セキ (SEKI)", "-", "Hasil Kerja / Catatan", "Benang 糸 dipintal 責", "実績 (じっせき / jisseki)", "Pencapaian nyata", 17),
    ("修", "kanji_aktivitas", "osameru / shuu", "シュウ (SHUU), シュ (SHU)", "おさ・める (osa-meru)", "Mempelajari / Memperbaiki", "Orang イ melatih diri 攸 彡", "研修 (けんしゅう / kenshuu)", "Pelatihan kerja", 10),
    ("熟", "kanji_sifat", "koneru / juku", "ジュク (JUKU)", "こな・れる (kona-reru)", "Matang / Mahir", "Makanan 享 dipanggang 灬 matang", "熟語 (じゅくご / jukugo)", "Idiom kanji gabungan", 15),
    ("達", "kanji_sosial", "tatsu", "タツ (TATSU)", "たち (tachi)", "Mencapai / Teman-teman", "Jalan 辶 mencapai tujuan 幸", "友達 (ともだち / tomodachi)", "Teman-teman", 12),
    ("技", "kanji_kehidupan", "waza / gi", "ギ (GI)", "わざ (waza)", "Keahlian / Teknik", "Tangan 扌 dan kerja 工 mahir", "技術 (ぎじゅつ / gijutsu)", "Teknologi / Keahlian", 7),
    ("術", "kanji_kehidupan", "sube / jutsu", "ジュツ (JUTSU)", "すべ (sube)", "Seni / Cara / Teknik", "Jalan 行 dan padi 朮 bernilai seni", "技術 (ぎじゅつ / gijutsu)", "Teknik / Teknologi", 11),
    ("藝", "kanji_kehidupan", "gei", "ゲイ (GEI)", "-", "Kesenian Tradisional", "Menanam 艹 tanaman 執 bermutu seni", "芸術 (げいじゅつ / geijutsu)", "Karya seni", 18),
    ("才", "kanji_abstrak", "sai", "サイ (SAI)", "-", "Bakat / Usia Tahun", "Tunas tumbuh berbakat", "天才 (てんさい / tensai)", "Orang jenius", 3),
    ("姿", "kanji_sifat", "sugata / shi", "シ (SHI)", "すがた (sugata)", "Penampilan / Postur", "Wanita 女 yang anggun 次", "姿勢 (しせい / shisei)", "Postur tubuh / Sikap", 9),
    ("勢", "kanji_abstrak", "isei / sei", "セイ (SEI)", "いきお・い (ikio-i)", "Kekuatan Momentum", "Tanaman 執 dan kekuatan 力 pesat", "姿勢 (しせい / shisei)", "Sikap / Momentum", 13),
    ("態", "kanji_abstrak", "tai", "タイ (TAI)", "-", "Kondisi / Sikap", "Gajah 能 dan hati 心", "状態 (じょうたい / joutai)", "Kondisi / Keadaan", 14),
    ("度", "kanji_abstrak", "tabi / do", "ド (DO), ト (TO), タク (TAKU)", "たび (tabi), た・い (ta-i)", "Derajat / Kali / Tingkat", "Gedung 广 dan tangan 又 mengukur", "一度 (いちど / ichido)", "Satu kali", 9),
    ("統", "kanji_abstrak", "suberu / tou", "トウ (TOU)", "す・べる (sube-ru)", "Penyatuan / Menguasai", "Benang 糸 menyatukan 充", "統一 (とういつ / touitsu)", "Penyatuan / Unifikasi", 12),
    ("化", "kanji_abstrak", "kakeru / ka", "カ (KA), ケ (KE)", "ば・ける (bake-ru), ば・かす (bake-su)", "Perubahan / Transformasi", "Dua orang 𠂉 七 saling berubah", "文化 (ぶんか / bunka)", "Kebudayaan", 4),
    ("宗", "kanji_sosial", "shuu / sou", "シュウ (SHUU), ソウ (SOU)", "-", "Agama / Sekte", "Atap 宀 dan altar 示 tempat beribadah", "宗教 (しゅうきょう / shuukyou)", "Agama / Kepercayaan", 8),
    ("教", "kanji_sosial", "oshieru / kyou", "キョウ (KYOU)", "おし・える (oshi-eru), おそ・わる (oso-waru)", "Mengajar / Agama", "Anak 孝 diajari dengan tegas 攵", "教科書 (きょうかしょ / kyoukasho)", "Buku pelajaran", 11),
    ("哲", "kanji_abstrak", "tetsu", "テツ (TETSU)", "-", "Filsafat / Kebijaksanaan", "Mulut 口 dan kapak 折 bijak", "哲学 (てつがく / tetsugaku)", "Filsafat", 10),
    ("儀", "kanji_sosial", "gi", "ギ (GI)", "-", "Upacara / Etiket", "Orang イ beretika adil 義", "礼儀 (れいぎ / reigi)", "Sopan santun / Etiket", 15),
    ("節", "kanji_kehidupan", "fushi / setsu", "セツ (SETSU), セチ (SECHI)", "ふし (fushi)", "Buku Bambu / Musim / Hemat", "Bambu 竹 dipotong 即 rapi", "季節 (きせつ / kisetsu)", "Musim cuaca", 13)
]

# Clean & filter out duplicates
added_objects = []
seen = set(all_existing)

for k, subCat, read, ony, kuny, mean, mnem, exJp, exId, strk in new_kanji_raw:
    k_clean = k.strip()
    if k_clean not in seen:
        seen.add(k_clean)
        added_objects.append({
            "id": f"kj-n3-{k_clean}",
            "category": "kanji",
            "subCategory": subCat,
            "japanese": k_clean,
            "reading": read,
            "onyomi": ony,
            "kunyomi": kuny,
            "meaningId": mean,
            "mnemonic": mnem,
            "exampleJp": exJp.strip(),
            "exampleId": exId.strip(),
            "strokes": strk,
            "level": "N3"
        })

print(f"Added new unique N3 kanji count: {len(added_objects)}")
print(f"New total unique Kanji across all sets: {len(seen)}")

if len(seen) < 650:
    print(f"WARNING: Need {650 - len(seen)} more unique kanji chars!")
