import re, json

with open('src/data/kanjiData.ts', 'r', encoding='utf-8') as f:
    text_all = f.read()

n5n4_block = text_all[:text_all.find('export const kanjiData')]
existing_n5n4 = set(re.findall(r'\"japanese\":\s*\"(.*?)\"', n5n4_block))

print(f"Existing N5/N4 kanji count: {len(existing_n5n4)}")

# Read current kanjiN3Data.ts
with open('src/data/kanjiN3Data.ts', 'r', encoding='utf-8') as f:
    text_n3 = f.read()

# Parse current items in kanjiN3Data.ts
# We can extract the items from text_n3 using regex or AST
# Let's see: text_n3 has export const kanjiN3Data: CardItem[] = [ ... ];

seen_kanji = set(existing_n5n4)

# Common 235 additional authentic JLPT N3 Kanji list
additional_n3_kanji_data = [
    # (kanji, subCat, reading, ony, kun, mean, mnem, exJp, exId, stroke)
    ("受", "kanji_aktivitas", "ukeru / ju", "ジュ (JU)", "う・ける (uke-ru)", "Menerima / Ujian", "Tangan 上 menerima benda", "受験 (じゅけん / juken)", "Mengikuti ujian", 8),
    ("付", "kanji_aktivitas", "tsuku / fu", "フ (FU)", "つ・く (tsu-ku)", "Menempel / Lampiran", "Orang イ menempelkan tanda", "受付 (うけつけ / uketsuke)", "Resepsionis", 5),
    ("呼", "kanji_aktivitas", "yobu / ko", "コ (KO)", "よ・ぶ (yo-bu)", "Memanggil", "Mulut 口 memanggil keras", "呼吸 (こきゅう / kokyuu)", "Pernapasan", 8),
    ("頼", "kanji_sosial", "tanomu / rai", "ライ (RAI)", "たの・む (tano-mu)", "Meminta / Mengandalkan", "Permohonan bantuan kepala 頁", "依頼 (いらい / irai)", "Permintaan", 16),
    ("渡", "kanji_gerak", "wataru / to", "ト (TO)", "わた・る (wata-ru)", "Menyeberang", "Air 氵 dan perahu membawa seberang", "渡す (わたす / watasu)", "Menyerahkan", 12),
    ("慣", "kanji_kehidupan", "nareru / kan", "カン (KAN)", "な・れる (na-reru)", "Terbiasa / Adat", "Hati 心 dan konsistensi", "習慣 (しゅうかん / shuukan)", "Kebiasaan", 14),
    ("絡", "kanji_sosial", "karamu / raku", "ラク (RAKU)", "から・む (kara-mu)", "Terhubung", "Benang 糸 terhubung lokasi 各", "連絡 (れんらく / renraku)", "Hubungan / Kontak", 12),
    ("差", "kanji_abstrak", "sasu / sa", "サ (SA)", "さ・す (sa-su)", "Beda / Menunjuk", "Domba 羊 dan tangan 工", "差別 (さべつ / sabetsu)", "Diskriminasi", 10),
    ("残", "kanji_kehidupan", "nokoru / zan", "ザン (ZAN)", "のこ・る (noko-ru)", "Sisa / Menyisakan", "Pisau 戋 menyisakan bagian", "残念 (ざんねん / zannen)", "Sayang sekali", 10),
    ("勝", "kanji_kompetisi", "katsu / shou", "ショウ (SHOU)", "か・つ (ka-tsu)", "Menang", "Kekuatan 力 mengalahkan musuh", "勝利 (しょうり / shouri)", "Kemenangan", 12),
    ("負", "kanji_kompetisi", "makeru / fu", "フ (FU)", "ま・ける (make-ru)", "Kalah", "Membawa beban kerang 貝", "勝負 (しょうぶ / shoubu)", "Pertandingan", 9),
    ("続", "kanji_waktu", "tsuduku / zoku", "ゾク (ZOKU)", "つづ・く (tsudu-ku)", "Berlanjut", "Benang 糸 yang disambung", "継続 (けいぞく / keizoku)", "Kelanjutan", 13),
    ("探", "kanji_aktivitas", "sagasu / tan", "タン (TAN)", "さが・す (saga-su)", "Mencari", "Tangan 扌 mencari di gua 穴", "探す (さがす / sagasu)", "Mencari barang", 11),
    ("祈", "kanji_perasaan", "inoru / ki", "キ (KI)", "いの・る (ino-ru)", "Berdoa", "Altar 示 dan kapak 斤 tempat doa", "祈る (いのる / inoru)", "Berdoa", 8),
    ("願", "kanji_perasaan", "negai / gan", "ガン (GAN)", "ねが・う (nega-u)", "Keinginan", "Asal 原 mengharapkan sesuatu", "願い (ねがい / negai)", "Harapan", 19),
    ("祝", "kanji_sosial", "iwai / shuku", "シュク (SHUKU)", "いわ・う (iwa-u)", "Merayakan", "Altar 示 ucapan selamat", "お祝い (おいわい / oiwai)", "Perayaan", 9),
    ("助", "kanji_sosial", "tasukeru / jo", "ジョ (JO)", "たす・ける (tasuke-ru)", "Membantu", "Sawah 且 dan kekuatan 力", "助ける (たすける / tasukeru)", "Menolong", 7),
    ("努", "kanji_aktivitas", "tsutomeru / do", "ド (DO)", "つと・める (tsutome-ru)", "Berusaha", "Mengerahkan kekuatan 力", "努力 (どりょく / doryoku)", "Kerja keras", 7),
    ("効", "kanji_abstrak", "kou", "コウ (KOU)", "き・く (ki-ku)", "Efektif", "Pertukaran 交 mengerahkan kekuatan", "効果 (こうか / kouka)", "Efek / Khasiat", 8),
    ("働", "kanji_pekerjaan", "hataraku / dou", "ドウ (DOU)", "はたら・く (hatara-ku)", "Bekerja", "Orang イ mengerahkan gerak 重", "労働 (ろうどう / roudou)", "Tenaga kerja", 13),
    ("勧", "kanji_sosial", "susumeru / kan", "カン (KAN)", "すすめ・る (susume-ru)", "Menganjurkan", "Burung 雚 dan kekuatan 力", "勧誘 (かんゆう / kanyuu)", "Ajak bergabung", 13),
    ("恐", "kanji_perasaan", "osoroi / kyou", "キョウ (KYOU)", "おそ・れる (oso-reru)", "Takut", "Hati 心 gemetar bahaya", "恐ろしい (おそろしい / osoroshii)", "Mengerikan", 10),
    ("悲", "kanji_perasaan", "kanashii / hi", "ヒ (HI)", "かな・しい (kana-shii)", "Sedih", "Sayap 非 duka di hati 心", "悲しい (かなしい / kanashii)", "Sedih", 12),
    ("苦", "kanji_perasaan", "kurashii / ku", "ク (KU)", "くる・しい (kuru-shii)", "Pahit / Menderita", "Tanaman 草 tua rasa pahit", "苦しい (くるしい / kurushii)", "Menderita", 8),
    ("痛", "kanji_kesehatan", "itai / tsuu", "ツウ (TSUU)", "いた・い (ita-i)", "Sakit", "Penyakit 疒 di tubuh 通", "痛い (いたい / itai)", "Sakit / Nyeri", 12),
    ("眠", "kanji_kehidupan", "nemuru / min", "ミン (MIN)", "ねむ・る (nemu-ru)", "Tidur", "Mata 目 terpejam di malam 民", "睡眠 (すいみん / suimin)", "Tidur nyenyak", 10),
    ("忙", "kanji_kehidupan", "isogashii / bou", "ボウ (BOU)", "いそが・しい (isoga-shii)", "Sibuk", "Hati 忄 tergesa-gesa", "忙しい (いそがしい / isogashii)", "Sibuk", 6),
    ("困", "kanji_kehidupan", "komaru / kon", "コン (KON)", "こま・る (koma-ru)", "Kesulitan", "Pohon 木 terkurung pagar 囗", "困難 (こんなん / konnan)", "Kesulitan", 7),
    ("疑", "kanji_perasaan", "utagau / gi", "ギ (GI)", "うたが・う (utaga-u)", "Ragu / Curiga", "Orang berdiri menengok", "疑問 (ぎもん / gimon)", "Pertanyaan", 14),
    ("怒", "kanji_perasaan", "okoru / do", "ド (DO)", "おこ・る (oko-ru)", "Marah", "Wanita 女 memendam gusar", "怒る (おこる / okoru)", "Marah", 9),
    ("怖", "kanji_perasaan", "kowai / fu", "フ (FU)", "こわ・い (kowa-i)", "Takut", "Hati 忄 terancam kain 布", "恐怖 (きょうふ / kyoufu)", "Ketakutan", 8),
    ("照", "kanji_alam", "teru / shou", "ショウ (SHOU)", "て・れる (te-reru)", "Menerangi", "Matahari 日 memancarkan cahaya", "照明 (しょうめい / shoumei)", "Lampu / Penerangan", 13),
    ("迷", "kanji_perasaan", "mayou / mei", "メイ (MEI)", "まよ・う (mayo-u)", "Tersesat", "Jalan 米 membuat bingung 辶", "迷子 (まいご / maigo)", "Anak tersesat", 9),
    ("驚", "kanji_perasaan", "odoroku / kyou", "キョウ (KYOU)", "おどろ・く (odoro-ku)", "Terkejut", "Kuda 馬 melonjak kaget", "驚く (おどろく / odoroku)", "Kaget", 22),
    ("悩", "kanji_perasaan", "nayamu / nou", "ノウ (NOU)", "なや・む (naya-mu)", "Cemas", "Hati 忄 pusing memikirkan 脳", "悩み (なやみ / nayami)", "Kecemasan", 10),
    ("恥", "kanji_perasaan", "haji / chi", "チ (CHI)", "はず・かしい (hazu-kashii)", "Malu", "Telinga 耳 merah di hati 心", "恥ずかしい (はずかしい / hazukashii)", "Malu", 10),
    ("浮", "kanji_alam", "ukabu / fu", "フ (FU)", "う・かぶ (u-kabu)", "Mengapung", "Air 氵 mengapung permukaan", "浮く (うく / uku)", "Mengapung", 10),
    ("沈", "kanji_alam", "shizumu / chin", "チン (CHIN)", "しず・む (shizu-mu)", "Tenggelam", "Air 氵 membawa beban 尢", "沈む (しずむ / shizumu)", "Tenggelam", 7),
    ("涼", "kanji_alam", "suzushii / ryou", "リョウ (RYOU)", "すず・しい (suzu-shii)", "Sejuk", "Air 氵 di ibu kota 京", "涼しい (すずしい / suzushii)", "Sejuk", 11),
    ("暖", "kanji_alam", "atatakai / dan", "ダン (DAN)", "あたた・かい (atata-kai)", "Hangat (Cuaca)", "Matahari 日 membawa hangat", "暖房 (だんぼう / danbou)", "Pemanas ruang", 13),
    ("温", "kanji_alam", "atatakai / on", "オン (ON)", "あたた・かい (atata-kai)", "Hangat (Benda)", "Air 氵 wadah 皿 membawa hangat", "温度 (おんど / ondo)", "Suhu", 12),
    ("冷", "kanji_alam", "tsumetai / rei", "レイ (REI)", "つめ・たい (tsume-tai)", "Dingin", "Es 冫 dan perintah 令", "冷蔵庫 (れいぞうこ / reizouko)", "Kulkas", 7),
    ("湿", "kanji_alam", "shimeru / shitsu", "シツ (SHITSU)", "しめ・る (shime-ru)", "Lembab", "Air 氵 tertutup embun 顕", "湿度 (しつど / shitsudo)", "Kelembapan", 12),
    ("乾", "kanji_alam", "kawaku / kan", "カン (KAN)", "かわ・く (kawa-ku)", "Kering", "Matahari mengeringkan tanah", "乾燥 (かんそう / kansou)", "Pengeringan", 11),
    ("薄", "kanji_sifat", "usui / haku", "ハク (HAKU)", "うす・い (usu-i)", "Tipis / Hambar", "Rumput 草 air 氵 tipis", "薄い (うすい / usui)", "Tipis", 16),
    ("濃", "kanji_sifat", "koi / nou", "ノウ (NOU)", "こ・い (ko-i)", "Pekat", "Air 氵 dan pertanian 農", "濃い (こい / koi)", "Kental / Pekat", 16),
    ("豊", "kanji_sifat", "yutaka / hou", "ホウ (HOU)", "ゆた・か (yuta-ka)", "Kaya / Melimpah", "Wadah berisi hasil panen", "豊富 (ほうふ / houfu)", "Melimpah", 13),
    ("富", "kanji_sifat", "tomi / fu", "フ (FU)", "とみ (tomi)", "Kemakmuran", "Rumah 宀 berisi kekayaan", "豊富 (ほうふ / houfu)", "Kaya", 12),
    ("貧", "kanji_sifat", "mazushii / hin", "ヒン (HIN)", "まず・しい (mazu-shii)", "Miskin", "Membagi 分 kerang 貝 berkurang", "貧しい (まずしい / mazushii)", "Miskin", 11),
    ("弱", "kanji_sifat", "yowai / jaku", "ジャク (JAKU)", "よわ・い (yowa-i)", "Lemah", "Dua busur 弓 belum kuat", "弱点 (じゃくてん / jakuten)", "Kelemahan", 10),
    ("浅", "kanji_sifat", "asai / sen", "セン (SEN)", "あさ・い (asa-i)", "Dangkal", "Air 氵 sedikit dangkal", "浅い (あさい / asai)", "Dangkal", 8),
    ("深", "kanji_sifat", "fukai / shin", "シン (SHIN)", "ふか・い (fuka-i)", "Dalam", "Air 氵 di gua 穴", "深刻 (しんこく / shinkoku)", "Mendalam", 11),
    ("細", "kanji_sifat", "hosoi / sai", "サイ (SAI)", "ほそ・い (hoso-i)", "Halus / Detail", "Benang 糸 dipotong kecil", "細かい (こまかい / komakai)", "Rinci / Detail", 11),
    ("太", "kanji_sifat", "futoi / tai", "タイ (TAI)", "ふと・い (futo-i)", "Gemuk / Tebal", "Besar 大 dengan titik", "太平洋 (たいへいよう / taiheiyou)", "Samudra Pasifik", 4),
    ("硬", "kanji_sifat", "katai / kou", "コウ (KOU)", "かた・い (kata-i)", "Keras", "Batu 石 diproses terasa keras", "硬い (かたい / katai)", "Keras", 12),
    ("軟", "kanji_sifat", "yawaraka / nan", "ナン (NAN)", "やわ・らか (yawa-raka)", "Lunak", "Roda 車 dan panah bergerak lentur", "柔軟 (じゅうなん / juunan)", "Fleksibel", 11),
    ("鋭", "kanji_sifat", "surudoi / ei", "エイ (EI)", "するど・い (surudo-i)", "Tajam", "Logam 金 diasah tajam", "鋭い (するどい / surudoi)", "Tajam", 15),
    ("鈍", "kanji_sifat", "nibui / don", "ドン (DON)", "にぶ・い (nibu-i)", "Tumpul", "Logam 金 yang tumpul", "鈍い (にぶい / nibui)", "Tumpul", 12),
    ("幼", "kanji_sifat", "osanai / you", "ヨウ (YOU)", "おさな・い (osana-i)", "Balita", "Benang 幼 anak kecil", "幼児 (ようじ / youji)", "Balita", 5),
    ("老", "kanji_sosial", "oiru / rou", "ロウ (ROU)", "お・いる (o-iru)", "Tua / Lansia", "Orang tua tongkat berdiri", "老人 (ろうじん / roujin)", "Lansia", 6),
    ("若", "kanji_sifat", "wakai / jaku", "ジャク (JAKU)", "わか・い (waka-i)", "Muda", "Rumput 草 muda tumbuh", "若い (わかい / wakai)", "Muda", 8),
    ("貴", "kanji_sifat", "tattoi / ki", "キ (KI)", "たっと・い (tatto-i)", "Mewah / Mulia", "Kerang 貝 berharga mahal", "貴重 (きちょう / kichou)", "Berharga", 12),
    ("尊", "kanji_sosial", "toutoi / son", "ソン (SON)", "とうと・い (touto-i)", "Hormat", "Botol anggur panggung 寸", "尊敬 (そんけい / sonkei)", "Rasa hormat", 12),
    ("敬", "kanji_sosial", "uyamau / kei", "ケイ (KEI)", "うやま・う (uyama-u)", "Menghormati", "Anak dan pimpinan saling hormat", "敬語 (けいご / keigo)", "Bahasa halus", 12),
    ("礼", "kanji_sosial", "rei", "レイ (REI)", "おれい (orei)", "Sopan Santun", "Altar 示 dan penundukan diri", "お礼 (おれい / orei)", "Ucapan terima kasih", 5),
    ("義", "kanji_abstrak", "gi", "ギ (GI)", "-", "Keadilan", "Domba 羊 dan tombak simbol adil", "義務 (ぎむ / gimu)", "Kewajiban", 13),
    ("徳", "kanji_abstrak", "toku", "トク (TOKU)", "-", "Kebajikan", "Langkah 彳 dan hati 直", "道徳 (どうとく / doutoku)", "Moralitas", 14),
    ("仁", "kanji_abstrak", "jin", "ジン (JIN)", "-", "Cinta Kasih", "Dua orang イ 二 saling kasih", "仁義 (じんぎ / jingi)", "Kemanusiaan", 4),
    ("誠", "kanji_abstrak", "makoto / sei", "セイ (SEI)", "まこと (makoto)", "Kejujuran", "Bicara 言 sesuai kenyataan", "誠実 (せいじつ / seijitsu)", "Jujur tulus", 13),
    ("善", "kanji_abstrak", "yoshi / zen", "ゼン (ZEN)", "よ・い (yo-i)", "Kebaikan", "Domba 羊 dan kata 言 baik", "改善 (かいぜん / kaizen)", "Perbaikan", 12),
    ("悪", "kanji_perasaan", "warui / aku", "アク (AKU)", "わる・い (waru-i)", "Buruk", "Atap 亜 dan hati 心 jahat", "悪魔 (あくま / akuma)", "Iblis", 11),
    ("罪", "kanji_sosial", "tsumi / zai", "ザイ (ZAI)", "つみ (tsumi)", "Dosa", "Jaring 网 menahan bersalah", "犯罪 (はんざい / hanzai)", "Kejahatan", 13),
    ("罰", "kanji_sosial", "batsu", "バツ (BATSU)", "-", "Hukuman", "Jaring 网 dan pisau 刀 sanksi", "罰金 (ばっきん / bakkin)", "Denda uang", 14),
    ("許", "kanji_sosial", "yurusu / kyo", "キョ (KYO)", "ゆる・す (yuru-su)", "Memaafkan / Izin", "Bicara 言 memberi izin", "許可 (きょか / kyoka)", "Izin resmi", 11),
    ("認", "kanji_abstrak", "nomeru / nin", "ニン (NIN)", "みと・める (mito-meru)", "Mengakui", "Bicara 言 menyetujui", "確認 (かくにん / kakunin)", "Konfirmasi", 14),
    ("誤", "kanji_abstrak", "ayamaru / go", "ゴ (GO)", "あやま・る (ayama-ru)", "Kesalahan", "Bicara 言 membingungkan", "誤解 (ごかい / gokai)", "Salah paham", 14),
    ("拾", "kanji_aktivitas", "hiroi / shuu", "シュウ (SHUU)", "ひろ・う (hiro-u)", "Memungut", "Tangan 扌 mengumpulkan 合", "拾う (ひろう / hirou)", "Memungut barang", 9),
    ("捨", "kanji_aktivitas", "suteru / sha", "シャ (SHA)", "す・てる (su-teru)", "Membuang", "Tangan 扌 membuang barang", "捨て分 (すてぶち / sutebuchi)", "Membuang sampah", 11),
    ("投", "kanji_aktivitas", "nage / tou", "トウ (TOU)", "な・げる (nage-ru)", "Melempar", "Tangan 扌 melempar barang", "投票 (とうひょう / touhyou)", "Pemungutan suara", 7),
    ("打", "kanji_aktivitas", "utsu / da", "ダ (DA)", "う・つ (u-tsu)", "Memukul", "Tangan 扌 memukul paku", "打つ (うつ / utsu)", "Memukul / Mengetik", 5),
    ("押", "kanji_aktivitas", "osu / ou", "オウ (OU)", "お・す (o-su)", "Menekan", "Tangan 扌 menekan tombol", "押す (おす / osu)", "Menekan", 8),
    ("抱", "kanji_aktivitas", "daku / hou", "ホウ (HOU)", "だ・く (da-ku)", "Memeluk", "Tangan 扌 merangkul 包", "抱く (だく / daku)", "Memeluk", 8),
    ("支", "kanji_aktivitas", "sasaeru / shi", "シ (SHI)", "ささ・える (sasa-eru)", "Menyokong", "Tangan memegang cabang", "支店 (してん / shiten)", "Cabang toko", 4),
    ("払", "kanji_aktivitas", "harau / futsu", "フツ (FUTSU)", "はら・う (hara-u)", "Membayar", "Tangan 扌 menyapu 厶", "支払い (しはらい / shiharai)", "Pembayaran", 5),
    ("掘", "kanji_aktivitas", "horu / kutsu", "クツ (KUTSU)", "ほ・る (ho-ru)", "Menggali", "Tangan 扌 menggali tanah", "掘る (ほる / horu)", "Menggali", 11),
    ("捕", "kanji_aktivitas", "tsukamaeru / ho", "ホ (HO)", "つか・まえる (tsuka-maeru)", "Menangkap", "Tangan 扌 menangkap", "逮捕 (たいほ / taiho)", "Penangkapan", 10),
    ("握", "kanji_aktivitas", "nigiru / aku", "アク (AKU)", "にぎ・る (nigi-ru)", "Mengepal", "Tangan 扌 menggenggam", "握手 (あくしゅ / akushu)", "Jabat tangan", 12),
    ("振", "kanji_aktivitas", "furu / shin", "シン (SHIN)", "ふ・る (fu-ru)", "Mengayun", "Tangan 扌 mengayunkan", "振動 (しんどう / shindou)", "Getaran", 10),
    ("揮", "kanji_aktivitas", "ki", "キ (KI)", "ふる・う", "Mengendalikan", "Tangan 扌 memandu", "指揮 (しき / shiki)", "Instruksi", 12),
    ("操", "kanji_aktivitas", "ayatsuru / sou", "ソウ (SOU)", "あやつ・る (ayatsu-ru)", "Kemudi", "Tangan 扌 mengarahkan", "操作 (そうさ / sousa)", "Pengoperasian", 16),
    ("提", "kanji_aktivitas", "sageru / tei", "テイ (TEI)", "さ・げる (sage-ru)", "Mengajukan", "Tangan 扌 membawa barang", "提案 (ていあん / teian)", "Proposal", 12),
    ("掲", "kanji_aktivitas", "kageru / kei", "ケイ (KEI)", "かか・げる (kaka-geru)", "Memasang", "Tangan 扌 memajang", "掲示板 (けいじばん / keijiban)", "Papan pengumuman", 12),
    ("捜", "kanji_aktivitas", "sagasu / sou", "ソウ (SOU)", "さが・す (saga-su)", "Pelacakan", "Tangan 扌 melacak", "捜査 (そうさ / sousa)", "Penyelidikan", 10),
    ("摘", "kanji_aktivitas", "tsumu / teki", "テキ (TEKI)", "つ・む (tsu-mu)", "Memetik", "Tangan 扌 memetik", "指摘 (してき / shiteki)", "Penunjukan", 14),
    ("摩", "kanji_abstrak", "ma", "マ (MA)", "す・れる", "Gesekan", "Rumah 麻 dan tangan", "摩擦 (まさつ / masatsu)", "Gesekan", 15),
    ("擦", "kanji_abstrak", "suru / satsu", "サツ (SATSU)", "す・る (su-ru)", "Mengusap", "Rumah 察 dan tangan", "摩擦 (まさつ / masatsu)", "Gesekan", 17),
    ("敷", "kanji_kehidupan", "shiku / fu", "フ (FU)", "し・く (shi-ku)", "Gelar Tatami", "Gelaran karpet", "敷地 (しきち / shikichi)", "Kawasan", 15),
    ("畳", "kanji_kehidupan", "tatami / jou", "ジョウ (JOU)", "たたみ (tatami)", "Matras Tatami", "Bidang 田 dilipat rapi", "畳 (たたみ / tatami)", "Matras jerami", 12),
    ("散", "kanji_aktivitas", "chiru / san", "サン (SAN)", "ち・る (chi-ru)", "Berserak / Jalan", "Berhamburan", "散歩 (さんぽ / sampo)", "Jalan santai", 12),
    ("詰", "kanji_aktivitas", "tsumu / kitsu", "キツ (KITSU)", "つ・まる (tsuma-ru)", "Sumbat / Padat", "Padat berisi", "詰める (つめる / tsumeru)", "Mengkemas", 13),
    ("込", "kanji_gerak", "komu", "-", "こ・む (ko-mu)", "Masuk padat", "Jalan 辶 masuk 人", "人込 (ひとごみ / hitogomi)", "Kerumunan", 5),
    ("折", "kanji_aktivitas", "oru / setsu", "セツ (SETSU)", "お・る (o-ru)", "Melipat / Patah", "Tangan 扌 mematahkan", "骨折 (こっせつ / kossetsu)", "Patah tulang", 7),
    ("破", "kanji_aktivitas", "yaburu / ha", "ハ (HA)", "やぶ・る (yabu-ru)", "Robek / Rusak", "Batu 石 merobek", "破壊 (はかい / hakai)", "Kerusakan", 10),
    ("割", "kanji_aktivitas", "wari / katsu", "カツ (KATSU)", "わ・る (wa-ru)", "Membagi", "Pisau 刀 membagi", "割合 (わりあい / wariai)", "Rasio", 12),
    ("裂", "kanji_aktivitas", "sakaru / retsu", "レツ (RETSU)", "さ・ける (sake-ru)", "Terbelah", "Baju 衣 terbelah", "分裂 (ぶんれつ / bunretsu)", "Perpecahan", 12),
    ("砕", "kanji_aktivitas", "kudaku / sai", "サイ (SAI)", "くだ・く (kuda-ku)", "Hancur", "Batu 石 dihantam pecah", "砕く (くだく / kudaku)", "Menghancurkan", 9),
    ("減", "kanji_abstrak", "heru / gen", "ゲン (GEN)", "へ・る (he-ru)", "Berkurang", "Air 氵 berkurang", "減少 (げんしょう / genshou)", "Penurunan", 12),
    ("増", "kanji_abstrak", "fueru / zou", "ゾウ (ZOU)", "ふ・える (fue-ru)", "Bertambah", "Tanah 土 makin banyak", "増加 (ぞうか / zouka)", "Peningkatan", 14),
    ("満", "kanji_abstrak", "michiru / man", "マン (MAN)", "み・ちる (michi-ru)", "Penuh / Puas", "Air 氵 memenuhi wadah", "満足 (まんぞく / manzoku)", "Puas", 12),
    ("漏", "kanji_alam", "moreru / rou", "ロウ (ROU)", "も・れる (mo-reru)", "Bocor", "Air 氵 menetes rumah", "雨漏り (あまもり / amamori)", "Atap bocor", 14),
    ("滴", "kanji_alam", "shizuku / teki", "テキ (TEKI)", "しずく (shizuku)", "Tetesan air", "Air 氵 menetes atap", "水滴 (すいてき / suiteki)", "Tetesan air", 14),
    ("沸", "kanji_alam", "waku / futsu", "フツ (FUTSU)", "わ・く (wa-ku)", "Mendidih", "Air 氵 bergolak mendidih", "沸騰 (ふっとう / futtou)", "Mendidih", 8),
    ("湧", "kanji_alam", "waku / yuu", "ユウ (YUU)", "わ・く (wa-ku)", "Mata Air Pancar", "Air 氵 memancar tanah", "湧き水 (わきみず / wakimizu)", "Mata air", 12),
    ("溶", "kanji_alam", "tokeru / you", "ヨウ (YOU)", "と・ける (toke-ru)", "Larut", "Air 氵 melarutkan", "溶ける (とける / tokeru)", "Larut", 13),
    ("凝", "kanji_alam", "koru / gyou", "ギョウ (GYOU)", "こ・る (ko-ru)", "Membeku", "Es 冫 membekukan", "凝縮 (ぎょうしゅく / gyoushuku)", "Kondensasi", 16),
    ("蒸", "kanji_alam", "musu / jou", "ジョウ (JOU)", "む・す (mu-su)", "Mengukus", "Rumput 草 air menguap", "蒸気 (じょうき / jouki)", "Uap air", 13),
    ("濁", "kanji_alam", "nigoru / daku", "ダク (DAKU)", "にご・る (nigo-ru)", "Keruh", "Air 氵 bercampur lumpur", "濁る (にごる / nigoru)", "Air keruh", 16),
    ("澄", "kanji_alam", "sumu / chou", "チョウ (CHOU)", "す・む (su-mu)", "Jernih", "Air 氵 jernih sungai", "澄む (すむ / sumu)", "Air jernih", 15),
    ("染", "kanji_kehidupan", "somaru / sen", "セン (SEN)", "そ・める (some-ru)", "Mewarnai", "Air 氵 mewarnai", "感染 (かんせん / kansen)", "Infeksi", 9),
    ("漂", "kanji_alam", "tadayou / hyou", "ヒョウ (HYOU)", "ただよ・う (tadayo-u)", "Hanyut", "Air 氵 membawa hanyut", "漂流 (ひょうりゅう / hyouryuu)", "Hanyut", 14),
    ("崩", "kanji_alam", "kuzureru / hou", "ホウ (HOU)", "くず・れる (kuzu-reru)", "Runtuh", "Gunung 山 runtuh", "崩壊 (ほうかい / houkai)", "Keruntuhan", 11),
    ("荒", "kanji_alam", "arai / kou", "コウ (KOU)", "あら・い (ara-i)", "Ganas / Liar", "Rumput 草 liar memusnahkan", "荒い (あらい / arai)", "Ganas", 9),
    ("倒", "kanji_gerak", "taoreru / tou", "トウ (TOU)", "たお・れる (tao-reru)", "Tumbang", "Orang イ dan menara roboh", "倒産 (とうさん / tousan)", "Bangkrut", 10),
    ("損", "kanji_abstrak", "son", "ソン (SON)", "そこ・なう (soko-nau)", "Rugi / Kerusakan", "Tangan 扌 dan uang 員", "損害 (そんがい / songai)", "Kerugian", 10),
    ("暴", "kanji_perasaan", "abareru / bou", "ボウ (BOU)", "あば・れる (aba-reru)", "Ngamuk / Kekerasan", "Matahari 日 kekacauan", "暴力 (ぼうりょく / bouryoku)", "Kekerasan", 15),
    ("撃", "kanji_aktivitas", "utsu / geki", "ゲキ (GEKI)", "う・つ (u-tsu)", "Hantaman", "Kereta 車 dan tangan 手", "攻撃 (こうげき / kougeki)", "Serangan", 15),
    ("射", "kanji_aktivitas", "itsuru / sha", "シャ (SHA)", "い・つ (i-tsu)", "Melesat", "Badan 身 dan panah 寸", "発射 (はっしゃ / hassha)", "Peluncuran", 10),
    ("攻", "kanji_aktivitas", "semeru / kou", "コウ (KOU)", "せ・める (se-meru)", "Menyerang", "Kerja 工 dan senjata 攵", "攻撃 (こうげき / kougeki)", "Serangan", 7),
    ("防", "kanji_aktivitas", "fusegu / bou", "ボウ (BOU)", "ふせ・ぐ (fuse-gu)", "Mencegah", "Bukit 阝 menahan musuh", "防止 (ぼうし / boushi)", "Pencegahan", 7),
    ("避", "kanji_aktivitas", "sakeru / hi", "ヒ (HI)", "さ・ける (sake-ru)", "Menghindari", "Jalan 辶 melarikan bahaya", "避難 (ひなん / hinan)", "Evakuasi", 16),
    ("警", "kanji_sosial", "kei", "ケイ (KEI)", "-", "Waspada", "Bicara 言 tegas", "警察 (けいさつ / keisatsu)", "Kepolisian", 19),
    ("守", "kanji_sosial", "mamoru / shu", "シュ (SHU)", "まも・る (mamo-ru)", "Melindungi", "Atap 宀 melindungi rumah", "留守 (るす / rusu)", "Rumah kosong", 6),
    ("救", "kanji_sosial", "sukuu / kyuu", "キュウ (KYUU)", "すく・う (suku-u)", "Menyelamatkan", "Membantu 求 dengan kekuatan", "救急車 (きゅうきゅうしゃ / kyuukyuusha)", "Ambulans", 11),
    ("逃", "kanji_gerak", "nigeru / tou", "トウ (TOU)", "に・げる (nige-ru)", "Kabur", "Jalan 辶 melarikan diri", "逃げる (にげる / nigeru)", "Kabur", 9),
    ("追", "kanji_gerak", "oi / tsui", "ツイ (TSUI)", "お・う (o-u)", "Mengejar", "Jalan 辶 mengejar", "追加 (ついか / tsuika)", "Penambahan", 9),
    ("越", "kanji_gerak", "kosu / etsu", "エツ (ETSU)", "こ・す (ko-su)", "Melampaui", "Lari 走 melompati batas", "引っ越し (ひっこし / hikkoshi)", "Pindah rumah", 12),
    ("導", "kanji_sosial", "michibiku / dou", "ドウ (DOU)", "みちび・く (michibi-ku)", "Membimbing", "Jalan 道 dan petunjuk 寸", "指導 (しどう / shidou)", "Bimbingan", 15),
    ("招", "kanji_sosial", "maneku / shou", "ショウ (SHOU)", "まね・く (mane-ku)", "Mengundang", "Tangan 扌 dan mulut 口", "招待 (しょうたい / shoutai)", "Undangan", 8),
    ("誘", "kanji_sosial", "sasou / yuu", "ユウ (YUU)", "さそ・う (saso-u)", "Mengajak", "Bicara 言 membujuk", "誘導 (ゆうどう / yuudou)", "Pengarahan", 14),
    ("迎", "kanji_sosial", "mukaeru / gei", "ゲイ (GEI)", "むか・える (mukae-ru)", "Menyambut", "Jalan 辶 menyambut", "歓迎 (かんげい / kangei)", "Penyambutan", 7),
    ("戻", "kanji_gerak", "modoru / rei", "レイ (REI)", "もど・る (modo-ru)", "Kembali", "Pintu 房 tertutup menahan", "戻る (もどる / modoru)", "Kembali", 7),
    ("換", "kanji_aktivitas", "kaeru / kan", "カン (KAN)", "か・える (ka-eru)", "Menukar", "Tangan 扌 menukar barang", "交換 (こうかん / koukan)", "Pertukaran", 12),
    ("替", "kanji_aktivitas", "kaeru / tai", "タイ (TAI)", "か・える (ka-eru)", "Mengganti", "Orang 夫 夫 bergantian", "両替 (りょうがえ / ryougae)", "Penukaran uang", 12),
    ("旅", "kanji_kehidupan", "tabi / ryo", "リョ (RYO)", "たび (tabi)", "Perjalanan", "Bendera 方 bepergian", "旅行 (りょこう / ryokou)", "Wisata", 10),
    ("訪", "kanji_sosial", "tazuneru / hou", "ホウ (HOU)", "たず・ねる (tazu-neru)", "Mengunjungi", "Bicara 言 mengunjungi", "訪問 (ほうもん / houmon)", "Kunjungan", 11),
    ("宿", "kanji_kehidupan", "yado / shuku", "シュク (SHUKU)", "やど (yado)", "Penginapan", "Rumah 宀 menginap", "宿泊 (しゅくはく / shukuhaku)", "Menginap", 11),
    ("泊", "kanji_kehidupan", "tomaru / haku", "ハク (HAKU)", "と・まる (toma-ru)", "Menginap", "Air 氵 berlabuh menginap", "一泊 (いっぱく / ippaku)", "Menginap 1 malam", 8),
    ("留", "kanji_sosial", "todomaru / ryuu", "リュウ (RYUU)", "と・まる (todo-maru)", "Tinggal / Menahan", "Membajak sawah 田 tetap", "留学 (りゅうがく / ryuugaku)", "Studi di luar negeri", 10),
    ("居", "kanji_kehidupan", "iru / kyo", "キョ (KYO)", "い・る (i-ru)", "Tinggal", "Tubuh 尸 di rumah 古", "居間 (いま / ima)", "Ruang keluarga", 8),
    ("在", "kanji_abstrak", "aru / zai", "ザイ (ZAI)", "あ・る (a-ru)", "Berada", "Tanah 土 dan kayu 才", "存在 (そんざい / sonzai)", "Keberadaan", 6),
    ("存", "kanji_abstrak", "son / zon", "ソン (SON)", "-", "Menyimpan / Eksis", "Anak 子 dipelihara", "保存 (ほぞん / hozon)", "Penyimpanan", 6),
    ("象", "kanji_alam", "zou / shou", "ゾウ (ZOU)", "-", "Gajah / Simbol", "Bentuk badan gajah", "印象 (いんしょう / inshou)", "Kesan", 12),
    ("表", "kanji_abstrak", "omote / hyou", "ヒョウ (HYOU)", "おもて (omote)", "Permukaan / Tabel", "Baju 衣 bagian luar", "発表 (はっぴょう / happyou)", "Pengumuman", 8),
    ("裏", "kanji_abstrak", "ura / ri", "リ (RI)", "うら (ura)", "Bagian Belakang", "Bagian dalam baju", "裏口 (うらぐち / uraguchi)", "Pintu belakang", 13),
    ("面", "kanji_abstrak", "omote / men", "メン (MEN)", "おもて (omote)", "Wajah / Bidang", "Bingkai membingkai wajah", "面接 (めんせつ / mensetsu)", "Wawancara", 9),
    ("側", "kanji_abstrak", "gawa / soku", "ソク (SOKU)", "がわ (gawa)", "Sisi / Samping", "Orang イ berdiri di samping", "右側 (みぎがわ / migigawa)", "Sisi kanan", 11),
    ("角", "kanji_abstrak", "kado / kaku", "カク (KAKU)", "かど (kado)", "Sudut / Tanduk", "Bentuk tanduk tajam", "角度 (かくど / kakudo)", "Sudut derajat", 7),
    ("隅", "kanji_abstrak", "sumi / guu", "グウ (GUU)", "すみ (sumi)", "Pojok", "Bukit 阝 di pojokan", "隅 (すみ / sumi)", "Pojokan", 12),
    ("端", "kanji_abstrak", "hashi / tan", "タン (TAN)", "はし (hashi)", "Ujung / Pinggir", "Berdiri 立 di sisi gunung", "先端 (せんたん / sentan)", "Teknologi terdepan", 14),
    ("縁", "kanji_abstrak", "fuchi / en", "エン (EN)", "ふち (fuchi)", "Pinggiran / Takdir", "Benang 糸 mengikat takdir", "縁 (えん / en)", "Takdir / Hubungan", 15),
    ("枠", "kanji_abstrak", "waku", "-", "わく (waku)", "Bingkai", "Kayu 木 membingkai", "枠 (わく / waku)", "Bingkai / Kuota", 8),
    ("帯", "kanji_kehidupan", "obi / tai", "タイ (TAI)", "おび (obi)", "Sabuk Obi / Zona", "Kain ikatan pinggang", "携帯 (けいたい / keitai)", "HP / Ponsel", 10),
    ("境", "kanji_alam", "sakai / kyou", "キョウ (KYOU)", "さかい (sakai)", "Batasan / Perbatasan", "Tanah 土 di kawasan", "環境 (かんきょう / kankyou)", "Lingkungan", 14),
    ("域", "kanji_alam", "iki", "イキ (IKI)", "-", "Kawasan", "Tanah 土 dilindungi", "地域 (ちいき / chiiki)", "Wilayah lokal", 11),
    ("圏", "kanji_alam", "ken", "ケン (KEN)", "-", "Zona / Jangkauan", "Pagar 囗 mengurung kawasan", "首都圏 (しゅとけん / shutoken)", "Kawasan megapolitan", 12),
    ("庁", "kanji_sosial", "chou", "チョウ (CHOU)", "-", "Badan Instansi", "Gedung instansi", "県庁 (けんちょう / kenchou)", "Kantor gubernur", 5),
    ("府", "kanji_sosial", "fu", "フ (FU)", "-", "Kantor Prefektur", "Gedung 广 menyimpan dokumen", "政府 (せいふ / seifu)", "Pemerintah", 8),
    ("県", "kanji_sosial", "ken", "ケン (KEN)", "-", "Prefektur", "Mata 目 diikat benang 糸", "県 (けん / ken)", "Prefektur", 9),
    ("市", "kanji_sosial", "shi / ichi", "シ (SHI)", "いち (ichi)", "Kota / Pasar", "Topi 亠 dan kain 巾 pasar", "市民 (しみん / shimin)", "Warga kota", 5),
    ("区", "kanji_sosial", "ku", "ク (KU)", "-", "Kecamatan / Distrik", "Waduk 匚 membagi wilayah", "区役所 (くやくしょ / kuyakusho)", "Kantor distrik", 4),
    ("村", "kanji_sosial", "mura / son", "ソン (SON)", "むら (mura)", "Desa", "Pohon 木 di desa 寸", "農村 (のうそん / nouson)", "Desa pertanian", 7),
    ("島", "kanji_alam", "shima / tou", "トウ (TOU)", "しま (shima)", "Pulau", "Burung 鳥 di atas gunung", "半島 (はんとう / hantou)", "Semenanjung", 10),
    ("陸", "kanji_alam", "riku / roku", "リク (RIKU)", "おか (oka)", "Daratan / Benua", "Bukit 阝 tanah tinggi", "大陸 (たいりく / tairiku)", "Benua", 11),
    ("州", "kanji_alam", "su / shuu", "シュウ (SHUU)", "す (su)", "Wilayah / State", "Sungai 川 dengan gundukan", "九州 (きゅうしゅう / kyuushuu)", "Pulau Kyushu", 6),
    ("港", "kanji_alam", "minato / kou", "コウ (KOU)", "みなと (minato)", "Pelabuhan", "Air 氵 dan lorong pelabuhan", "空港 (くうこう / kuukou)", "Bandara", 12),
    ("湾", "kanji_alam", "wan", "ワン (WAN)", "-", "Teluk", "Air 氵 melengkung teluk", "東京湾 (とうきょうわん / toukyouwan)", "Teluk Tokyo", 12),
    ("岸", "kanji_alam", "kishi / gan", "ガン (GAN)", "きし (kishi)", "Pesisir", "Gunung 山 dan tebing", "海岸 (かいがん / kaigan)", "Pesisir pantai", 8),
    ("浜", "kanji_alam", "hama / hin", "ヒン (HIN)", "はま (hama)", "Pantai", "Air 氵 di pantai", "横浜 (よこはま / yokohama)", "Kota Yokohama", 10),
    ("砂", "kanji_alam", "suna / sa", "サ (SA)", "すな (suna)", "Pasir", "Batu 石 kecil halus", "砂漠 (さばく / sabaku)", "Padang pasir", 9),
    ("丘", "kanji_alam", "oka / kyuu", "キュウ (KYUU)", "おか (oka)", "Bukit", "Bentuk bukit landai", "丘 (おか / oka)", "Bukit", 5),
    ("谷", "kanji_alam", "tani / koku", "コク (KOKU)", "たに (tani)", "Lembah", "Air memancar di antara gunung", "谷 (たに / tani)", "Lembah", 7),
    ("泉", "kanji_alam", "izumi / sen", "セン (SEN)", "いずみ (izumi)", "Mata Air", "Air 白 pancaran 水 jernih", "温泉 (おんせん / onsen)", "Onsen air panas", 9),
    ("原", "kanji_alam", "hara / gen", "ゲン (GEN)", "はら (hara)", "Padang / Asal", "Tebing 厂 dan mata air 泉", "原料 (げんりょう / genryou)", "Bahan mentah", 10),
    ("苗", "kanji_pertanian", "nae / byou", "ビョウ (BYOU)", "なえ (nae)", "Bibit", "Rumput 草 di sawah 田", "苗 (なえ / nae)", "Bibit tanaman", 8),
    ("牧", "kanji_pertanian", "maki / boku", "ボク (BOKU)", "まき (maki)", "Peternakan", "Sapi 牛 diurus orang", "牧場 (ぼくじょう / bokujou)", "Peternakan", 8),
    ("草", "kanji_alam", "kusa / sou", "ソウ (SOU)", "くさ (kusa)", "Rumput", "Tanaman 草 di bawah matahari", "雑草 (ざっそう / zassou)", "Rumput liar", 9),
    ("葉", "kanji_alam", "ha / you", "ヨウ (YOU)", "は (ha)", "Daun", "Tanaman 草 dan pohon 木", "紅葉 (こうよう / kouyou)", "Daun gugur merah", 12),
    ("花", "kanji_alam", "hana / ka", "カ (KA)", "はな (hana)", "Bunga", "Rumput 草 yang berubah indah", "花火 (はなび / hanabi)", "Kembang api", 7),
    ("華", "kanji_sifat", "hana / ka", "カ (KA)", "はな (hana)", "Mewah / Megah", "Bunga 艹 berkembang indah", "豪華 (ごうか / gouka)", "Mewah", 10),
    ("芽", "kanji_alam", "me / ga", "ガ (GA)", "め (me)", "Tunas", "Rumput 草 bertunas 牙", "芽 (め / me)", "Tunas daun", 8),
    ("咲", "kanji_alam", "saku / shou", "ショウ (SHOU)", "さ・く (sa-ku)", "Mekar", "Mulut 口 tersenyum mekar", "咲く (さく / saku)", "Bunga mekar", 9),
    ("枯", "kanji_alam", "kare / ko", "コ (KO)", "かれ・る (kare-ru)", "Layu", "Pohon 木 tua 古 layu", "枯れる (かれる / kareru)", "Tanaman layu", 9),
    ("種", "kanji_pertanian", "tane / shu", "シュ (SHU)", "たね (tane)", "Biji / Jenis", "Gandum 禾 dan berat 重", "種類 (しゅるい / shurui)", "Jenis / Kategori", 14),
    ("類", "kanji_abstrak", "rui", "ルイ (RUI)", "-", "Kategori", "Biji 種 dan kepala 頁", "人類 (じんるい / jinrui)", "Manusia", 18),
    ("粒", "kanji_pertanian", "tsubu / ryuu", "リュウ (RYUU)", "つぶ (tsubu)", "Butiran", "Beras 米 berdiri 立", "粒 (つぶ / tsubu)", "Butir beras/air", 10),
    ("材", "kanji_industri", "zai", "ザイ (ZAI)", "-", "Bahan Kayu", "Pohon 木 bernilai 才", "材料 (ざいりょう / zairyou)", "Bahan baku", 7),
    ("板", "kanji_industri", "ita / han", "ハン (HAN)", "いた (ita)", "Papan Kayu", "Pohon 木 dibuat rata", "看板 (かんばん / kamban)", "Papan reklame", 8),
    ("柱", "kanji_bangunan", "hashira / chuu", "チュウ (CHUU)", "はしら (hashira)", "Pilar Utama", "Pohon 木 pemberi cahaya 主", "電柱 (でんちゅう / denchuu)", "Tiang listrik", 9),
    ("梁", "kanji_bangunan", "hari / ryou", "リョウ (RYOU)", "はり (hari)", "Balok Atap", "Kayu 木 menyeberangi air", "橋梁 (きょうりょう / kyouryou)", "Jembatan", 11),
    ("房", "kanji_bangunan", "fusa / bou", "ボウ (BOU)", "ふさ (fusa)", "Ruangan / Tandan", "Pintu 房 menuju ruangan", "暖房 (だんぼう / danbou)", "Pemanas ruang", 8),
    ("倉", "kanji_bangunan", "kura / sou", "ソウ (SOU)", "くら (kura)", "Gudang", "Atap 𠆢 dan gudang", "倉庫 (そうこ / souko)", "Gudang barang", 10),
    ("庫", "kanji_bangunan", "kura / ko", "コ (KO)", "-", "Garasi / Gudang", "Gedung 广 menyimpan mobil", "金庫 (きんこ / kinko)", "Brankas", 10),
    ("塔", "kanji_bangunan", "tou", "トウ (TOU)", "-", "Menara", "Tanah 土 bertumpuk tinggi", "塔 (とう / tou)", "Menara", 12),
    ("城", "kanji_bangunan", "shiro / jou", "ジョウ (JOU)", "しろ (shiro)", "Kastil / Istana", "Tanah 土 sempurna jadi kastil", "城 (しろ / shiro)", "Kastil Jepang", 9),
    ("橋", "kanji_bangunan", "hashi / kyou", "キョウ (KYOU)", "はし (hashi)", "Jembatan", "Pohon 木 tinggi menyeberang", "歩道橋 (ほどうきょう / hodoukyou)", "Jembatan penyeberangan", 16),
    ("堤", "kanji_bangunan", "tsutsumi / tei", "テイ (TEI)", "つつみ (tsutsumi)", "Tanggul", "Tanah 土 menahan air", "防波堤 (ぼうはてい / bouhatei)", "Tanggul pemecah ombak", 12),
    ("坊", "kanji_sosial", "bou", "ボウ (BOU)", "-", "Biksu", "Tanah 土 di kuil", "坊さん (ぼうさん / bousan)", "Biksu", 7),
    ("穴", "kanji_alam", "ana / ketsu", "ケツ (KETSU)", "あな (ana)", "Lubang", "Atap 宀 dan kaki 八", "穴 (あな / ana)", "Lubang", 5),
    ("溝", "kanji_bangunan", "mizo / kou", "コウ (KOU)", "みぞ (mizo)", "Parit", "Air 氵 mengalir parit", "排水溝 (はいすいこう / haisuikou)", "Saluran pembuangan", 13),
    ("井", "kanji_bangunan", "i / sei", "セイ (SEI)", "い (i)", "Sumur", "Bentuk sumur tradisional", "井戸 (いど / ido)", "Sumur air", 4),
    ("池", "kanji_alam", "ike / chi", "チ (CHI)", "いけ (ike)", "Kolam Air", "Air 氵 menampung cairan", "電池 (でんち / denchi)", "Batu baterai", 6),
    ("沼", "kanji_alam", "numa / shou", "ショウ (SHOU)", "ぬま (numa)", "Rawa", "Air 氵 di tanah rawa", "沼 (ぬま / numa)", "Rawa", 8),
    ("船", "kanji_transportasi", "fune / sen", "セン (SEN)", "ふね (fune)", "Kapal Laut", "Perahu 舟 membawa penumpang", "船長 (せんちょう / senchou)", "Kapten kapal", 11),
    ("舟", "kanji_transportasi", "fune / shuu", "シュウ (SHUU)", "ふね (fune)", "Perahu Kecil", "Bentuk sampan kayu", "小舟 (こぶね / kobune)", "Sampan kecil", 6),
    ("艦", "kanji_transportasi", "kan", "カン (KAN)", "-", "Kapal Perang", "Perahu 舟 berukuran raksasa", "軍艦 (ぐんかん / gunkan)", "Kapal perang", 21),
    ("荷", "kanji_kehidupan", "ni / ka", "カ (KA)", "に (ni)", "Barang Bawaan", "Tanaman 草 dipikul orang", "荷物 (にもつ / nimotsu)", "Barang bagasi", 10),
    ("袋", "kanji_kehidupan", "fukuro / tai", "タイ (TAI)", "ふくろ (fukuro)", "Kantong / Tas", "Baju 代 tertutup jadi kantong", "手袋 (てぶくろ / tebukuro)", "Sarung tangan", 11),
    ("箱", "kanji_kehidupan", "hako / sou", "ソウ (SOU)", "はこ (hako)", "Kotak Dus", "Bambu 竹 dipasang rapi", "ゴミ箱 (ごみばこ / gomibako)", "Tempat sampah", 15),
    ("缶", "kanji_kehidupan", "kan", "カン (KAN)", "-", "Kaleng", "Wadah logam penyimpanan", "缶詰 (かんづめ / kandzume)", "Makanan kaleng", 6),
    ("瓶", "kanji_kehidupan", "bin", "ビン (BIN)", "かめ (kame)", "Botol Kaca", "Wadah 瓦 berisi cairan", "花瓶 (かびん / kabin)", "Vas bunga", 11),
    ("皿", "kanji_kehidupan", "sara / bei", "ベイ (BEI)", "さら (sara)", "Piring", "Bentuk piring saji", "灰皿 (はいざら / haizara)", "Asbak", 5),
    ("箸", "kanji_kehidupan", "hashi / cho", "チョ (CHO)", "はし (hashi)", "Sumpit", "Bambu 竹 dipegang orang", "箸 (はし / hashi)", "Sumpit makan", 15),
    ("鉢", "kanji_kehidupan", "hachi / hatsu", "ハツ (HATSU)", "はち (hachi)", "Mangkuk Besar", "Logam 金 berbentuk mangkuk", "植木鉢 (うえきばち / uekibachi)", "Pot tanaman", 13),
    ("壺", "kanji_kehidupan", "tsubo / ko", "コ (KO)", "つぼ (tsubo)", "Guci", "Guci berleher sempit", "壺 (つぼ / tsubo)", "Guci keramik", 12),
    ("傘", "kanji_kehidupan", "kasa / san", "サン (SAN)", "かさ (kasa)", "Payung", "Bentuk atap payung", "傘 (かさ / kasa)", "Payung hujan", 12),
    ("履", "kanji_kehidupan", "haku / ri", "リ (RI)", "は・く (ha-ku)", "Alas Kaki", "Tubuh 尸 memakai sepatu", "履物 (はきもの / hakimono)", "Alas kaki", 15),
    ("靴", "kanji_kehidupan", "kutsu / ka", "カ (KA)", "くつ (kutsu)", "Sepatu", "Kulit 革 dibentuk sepatu", "靴下 (くつした / kutsushita)", "Kaus kaki", 13),
    ("服", "kanji_kehidupan", "fuku", "フク (FUKU)", "-", "Pakaian / Baju", "Bulan 月 dan tubuh 卩 memakai baju", "洋服 (ようふく / youfuku)", "Pakaian barat", 8),
    ("装", "kanji_kehidupan", "yosoi / sou", "ソウ (SOU)", "よそお・う (yosoo-u)", "Pakaian / Dekorasi", "Ksatria 壮 memakai pakaian", "服装 (ふくそう / fukusou)", "Gaya berpakaian", 12),
    ("衣", "kanji_kehidupan", "koromo / i", "イ (I)", "ころも (koromo)", "Pakaian Jubah", "Bentuk jubah baju", "衣服 (いふく / ifuku)", "Pakaian busana", 6),
    ("束", "kanji_kehidupan", "taba / sokoku", "ソク (SOKU)", "たば (taba)", "Ikat / Tandan", "Kayu 木 diikat kencang", "約束 (やくそく / yakusoku)", "Janji", 7),
    ("包", "kanji_kehidupan", "tsutsumu / hou", "ホウ (HOU)", "つつ・む (tsutsu-mu)", "Membungkus", "Bayi membungkus kandungan", "小包 (こづつmi / kodzutsumi)", "Paket pos", 5),
    ("紐", "kanji_kehidupan", "himo / juu", "ジュウ (JUU)", "ひも (himo)", "Tali Pengikat", "Benang 糸 diikatkan", "紐 (ひも / himo)", "Tali sepatu", 13),
    ("糸", "kanji_kehidupan", "ito / shi", "シ (SHI)", "いと (ito)", "Benang", "Bintik serat benang", "糸 (いと / ito)", "Benang jahit", 6),
    ("綿", "kanji_industri", "wata / men", "メン (MEN)", "わた (wata)", "Kapas Katun", "Benang 糸 kain putih", "木綿 (もめん / momen)", "Kain katun", 14),
    ("絹", "kanji_industri", "kinu / ken", "ケン (KEN)", "きぬ (kinu)", "Kain Sutra", "Benang 糸 sutra halus", "絹 (きぬ / kinu)", "Sutra halus", 13),
    ("毛", "kanji_alam", "ke / mou", "モウ (MOU)", "け (ke)", "Bulu Hewan", "Helai bulu lembut", "毛布 (もうふ / moufu)", "Selimut bulu", 4),
    ("皮", "kanji_alam", "kawa / hi", "ヒ (HI)", "かわ (kawa)", "Kulit Buah/Tubuh", "Menguliti lapisan luar", "皮膚 (ひふ / hifu)", "Kulit tubuh", 5),
    ("革", "kanji_industri", "kawa / kaku", "カク (KAKU)", "かわ (kawa)", "Kulit Olahan", "Kulit 𠂤 disamak jadi sepatu", "革靴 (かわぐつ / kawagutsu)", "Sepatu kulit", 9),
    ("鉄", "kanji_industri", "tetsu", "テツ (TETSU)", "-", "Besi Logam", "Logam 金 yang hitam kuat", "地下鉄 (ちかてつ / chikatetsu)", "Kereta bawah tanah", 13),
    ("銅", "kanji_industri", "dou", "ドウ (DOU)", "-", "Tembaga", "Logam 金 sama 同 tembaga", "銅メダル (どうメダル / dou medaru)", "Medali perunggu", 14),
    ("銀", "kanji_industri", "gin", "ギン (GIN)", "-", "Perak", "Logam 金 berkilau 艮", "銀行 (ぎんこう / ginkou)", "Bank", 14),
    ("鉱", "kanji_industri", "kou", "コウ (KOU)", "-", "Batu Tambang", "Logam 金 melimpah", "鉱物 (こうぶつ / koubutsu)", "Mineral", 13),
    ("炭", "kanji_industri", "sumi / tan", "タン (TAN)", "すみ (sumi)", "Batu Bara", "Gunung 山 dan api 火 arang", "石炭 (せきたん / sekitan)", "Batu bara", 9),
    ("油", "kanji_kehidupan", "abura / yu", "ユ (YU)", "あぶら (abura)", "Minyak", "Air 氵 dari botol 由", "醤油 (しょうゆ / shouyu)", "Kecap asin", 8),
    ("脂", "kanji_kesehatan", "abura / shi", "シ (SHI)", "あぶら (abura)", "Lemak Tubuh", "Daging 月 mengandung lemak", "脂肪 (しぼう / shibou)", "Lemak tubuh", 10),
    ("燃", "kanji_alam", "moeru / nen", "ネン (NEN)", "も・える (mo-eru)", "Bakar / Menyala", "Api 火 membakar bahan", "燃料 (ねんりょう / nenryou)", "Bahan bakar", 16),
    ("焼", "kanji_kehidupan", "yaku / shou", "ショウ (SHOU)", "や・く (ya-ku)", "Memanggang", "Api 火 memanggang makanan", "焼き肉 (やきにく / yakiniku)", "Daging panggang", 12),
    ("煙", "kanji_alam", "kemuri / en", "エン (EN)", "けむり (kemuri)", "Asap", "Api 火 dan tanah", "禁煙 (きんえん / kinen)", "Dilarang merokok", 13),
    ("灰", "kanji_alam", "hai / kai", "カイ (KAI)", "はい (hai)", "Abu Sisa Api", "Tangan 𠂇 mengambil sisa api", "灰皿 (はいざら / haizara)", "Asbak", 6),
    ("炎", "kanji_alam", "honoo / en", "エン (EN)", "ほのお (honoo)", "Kobaran Api", "Dua api 火 火 berkobar", "炎症 (えんしょう / enshou)", "Peradangan", 8),
    ("爆", "kanji_alam", "baku", "バク (BAKU)", "-", "Ledakan", "Api 火 meledakkan", "爆発 (ばくはつ / bakuhatsu)", "Ledakan", 19),
    ("震", "kanji_alam", "furu / shin", "シン (SHIN)", "ふる・える (furu-eru)", "Gempa Gemetar", "Hujan 雨 menggetarkan", "地震 (じしん / jishin)", "Gempa bumi", 15),
    ("災", "kanji_alam", "wasawai / sai", "サイ (SAI)", "わざわい (wazawai)", "Bencana", "Sungai 川 dan api 火 musibah", "災害 (さいがい / saigai)", "Bencana alam", 7),
    ("害", "kanji_abstrak", "gai", "ガイ (GAI)", "-", "Kerugian Bahaya", "Rumah 宀 dan senjata 口", "被害 (ひがい / higai)", "Kerugian bencana", 10),
    ("命", "kanji_kehidupan", "inochi / mei", "メイ (MEI)", "いのち (inochi)", "Nyawa Jiwa", "Atap 𠆢 dan mulut 口 perintah", "生命 (せいめい / seimei)", "Kehidupan", 8),
    ("福", "kanji_sosial", "fuku", "フク (FUKU)", "-", "Keberuntungan", "Altar 示 berisi wadah 田", "幸福 (こうふく / koufuku)", "Kebahagiaan", 13),
    ("望", "kanji_perasaan", "nozomu / bou", "ボウ (BOU)", "のぞ・む (nozo-mu)", "Berharap", "Bulan 月 dan orang 王 memandang", "希望 (きぼう / kibou)", "Harapan", 11),
    ("夢", "kanji_perasaan", "yume / mu", "ム (MU)", "ゆめ (yume)", "Mimpi", "Mata 夕 tertutup di malam", "夢 (ゆめ / yume)", "Mimpi indah", 13),
    ("志", "kanji_perasaan", "kokorozashi / shi", "シ (SHI)", "こころざし (kokorozashi)", "Cita-cita Tekad", "Berdiri 士 dengan tekad di hati", "意志 (いし / ishi)", "Tekad kuat", 7),
    ("企", "kanji_pekerjaan", "koku / ki", "キ (KI)", "くわだ・てる (kuwada-teru)", "Merencanakan", "Orang 𠆢 berdiri merancang", "企業 (きぎょう / kigyou)", "Perusahaan", 6),
    ("算", "kanji_abstrak", "san", "サン (SAN)", "-", "Kalkulasi", "Bambu 竹 dan alat sempoa", "計算 (けいさん / keisan)", "Perhitungan", 14),
    ("測", "kanji_abstrak", "hakaru / soku", "ソク (SOKU)", "はか・る (haka-ru)", "Mengukur", "Air 氵 dan aturan 則", "測定 (そくてい / sokutei)", "Pengukuran", 12),
    ("量", "kanji_abstrak", "hakaru / ryou", "リョウ (RYOU)", "はか・る (haka-ru)", "Bobot Jumlah", "Matahari 日 dan timbangan 里", "大量 (たいりょう / tairyou)", "Jumlah besar", 12),
    ("試", "kanji_aktivitas", "tameshi / shi", "シ (SHI)", "ため・す (tame-su)", "Mencoba Ujian", "Bicara 言 dan hukum 式", "試験 (しけん / shiken)", "Ujian", 13),
    ("査", "kanji_aktivitas", "sa", "サ (SA)", "-", "Memeriksa", "Pohon 木 dan kayu diperiksa", "調査 (ちょうさ / chousa)", "Survei", 9),
    ("察", "kanji_aktivitas", "satsu", "サツ (SATSU)", "-", "Mengamati", "Rumah 宀 dan altar 祭", "警察 (けいさつ / keisatsu)", "Polisi", 14),
    ("講", "kanji_pekerjaan", "kou", "コウ (KOU)", "-", "Kuliah Ceramah", "Bicara 言 dalam forum", "講義 (こうぎ / kougi)", "Kuliah", 17),
    ("論", "kanji_abstrak", "ron", "ロン (RON)", "-", "Teori / Skripsi", "Bicara 言 terstruktur 侖", "論文 (ろんぶん / rombun)", "Skripsi", 15),
    ("述", "kanji_abstrak", "noberu / jutsu", "ジュツ (JUTSU)", "のべ・る (nobe-ru)", "Menyatakan", "Jalan 辶 dan kuas 朮", "記述 (きじゅつ / kijutsu)", "Deskripsi", 8),
    ("語", "kanji_kehidupan", "kataru / go", "ゴ (GO)", "かた・る (kata-ru)", "Bahasa / Bercerita", "Bicara 言 lima 吾 hal", "日本語 (にほんご / nihongo)", "Bahasa Jepang", 14),
    ("説", "kanji_abstrak", "tojo / setsu", "セツ (SETSU)", "と・く (to-ku)", "Menjelaskan", "Bicara 言 dengan gembira", "説明 (せつめい / setsumei)", "Penjelasan", 14),
    ("訳", "kanji_abstrak", "wake / yaku", "ヤク (YAKU)", "わけ (wake)", "Menerjemahkan", "Bicara 言 untuk meluruskan 尺", "翻訳 (ほんやく / honyaku)", "Penerjemahan", 11),
    ("判", "kanji_abstrak", "han / ban", "ハン (HAN)", "-", "Keputusan", "Separuh 半 dipotong pisau 刀", "判断 (はんだん / handan)", "Keputusan", 7),
    ("断", "kanji_abstrak", "tatoweru / dan", "ダン (DAN)", "た・つ (ta-tsu)", "Memutus", "Benang dipotong kapak 斤", "判断 (はんだん / handan)", "Keputusan tegas", 11),
    ("確", "kanji_abstrak", "tashika / kaku", "カク (KAKU)", "たしか (tashika)", "Memastikan", "Batu 石 yang kukuh", "確認 (かくにん / kakunin)", "Konfirmasi", 15),
    ("証", "kanji_abstrak", "shou", "ショウ (SHOU)", "-", "Bukti / Sertifikat", "Bicara 言 yang benar 正", "証明 (しょうめい / shoumei)", "Bukti resmi", 12),
    ("挙", "kanji_aktivitas", "ageru / kyo", "キョ (KYO)", "あ・げる (a-geru)", "Mengangkat Pemilu", "Tangan 手 mengangkat barang", "選挙 (せんきょ / senkyo)", "Pemilu", 10),
    ("供", "kanji_sosial", "sonaeru / kyou", "キョウ (KYOU)", "そな・える (sona-eru)", "Menyediakan", "Orang イ menyediakan persembahan", "提供 (ていきょう / teikyou)", "Penyediaan", 8),
    ("承", "kanji_sosial", "shou", "ショウ (SHOU)", "うけたまわ・る", "Menyetujui Sopan", "Tangan menerima air mengalir", "承諾 (しょうだく / shoudaku)", "Persetujuan", 8),
    ("諾", "kanji_sosial", "daku", "ダク (DAKU)", "-", "Persetujuan", "Bicara 言 setuju", "承諾 (しょうだく / shoudaku)", "Persetujuan", 15),
    ("拒", "kanji_sosial", "kyo", "キョ (KYO)", "こば・む (koba-mu)", "Menolak", "Tangan 扌 menahan raksasa", "拒否 (きょひ / kyohi)", "Penolakan", 8),
    ("否", "kanji_abstrak", "hi", "ヒ (HI)", "いな (ina)", "Menolak Tidak", "Mulut 口 berkata tidak 不", "拒否 (きょひ / kyohi)", "Penolakan", 7),
    ("辞", "kanji_sosial", "yameru / ji", "ジ (JI)", "や・める (yame-ru)", "Mundur / Kamus", "Lidah 舌 dan kait 辛", "辞書 (じしょ / jisho)", "Kamus", 13),
    ("可", "kanji_abstrak", "ka", "カ (KA)", "-", "Boleh / Mungkin", "Mulut 口 menyetujui", "可能 (かのう / kanou)", "Mungkin", 5),
    ("制", "kanji_sosial", "sei", "セイ (SEI)", "-", "Sistem / Aturan", "Memotong 牛 dengan pisau 刀", "制度 (せいど / seido)", "Sistem", 8),
    ("限", "kanji_abstrak", "kagiru / gen", "ゲン (GEN)", "かぎ・る (kagi-ru)", "Batas Terbatas", "Bukit 阝 menahan batasan", "限界 (げんかい / genkai)", "Batas", 9),
    ("禁", "kanji_sosial", "kin", "キン (KIN)", "-", "Larangan keras", "Hutan 林 di area sakral 示", "禁止 (きんし / kinshi)", "Dilarang keras", 13),
    ("犯", "kanji_sosial", "okasu / han", "ハン (HAN)", "おか・す (oka-su)", "Kejahatan", "Anjing 犭 menyerang orang", "犯罪 (はんざい / hanzai)", "Kejahatan", 5),
    ("獄", "kanji_sosial", "goku", "ゴク (GOKU)", "-", "Penjara", "Dua anjing 犭 犬 menjaga", "地獄 (じごく / jigoku)", "Penjara", 14),
    ("裁", "kanji_sosial", "sabaku / sai", "サイ (SAI)", "さば・く (saba-ku)", "Adil Persidangan", "Baju 衣 dipotong kapak", "裁判 (さいばん / saiban)", "Persidangan", 12),
    ("審", "kanji_sosial", "shin", "シン (SHIN)", "-", "Sidang Wasit", "Rumah 宀 meneliti hal", "審判 (しんぱん / shimpan)", "Wasit", 15),
    ("訴", "kanji_sosial", "so", "ソ (SO)", "うった・える (utta-eru)", "Menuntut Mengadu", "Bicara 言 mengadukan hal", "訴訟 (そしょう / soshou)", "Gugatan hukum", 12),
    ("競", "kanji_kompetisi", "kisou / kyou", "キョウ (KYOU)", "きそ・う (kiso-u)", "Bersaing Berlomba", "Dua orang 兄 兄 berlari", "競争 (きょうそう / kyousou)", "Persaingan", 20),
    ("争", "kanji_kompetisi", "arasou / sou", "ソウ (SOU)", "あらそ・う (araso-u)", "Berebut / Perang", "Tangan 爫 berebut barang", "戦争 (せんそう / sensou)", "Perang", 6),
    ("闘", "kanji_kompetisi", "tatakau / tou", "トウ (TOU)", "たたか・う (tataka-u)", "Pertarungan", "Pintu 門 pertarungan", "闘争 (とうそう / tousou)", "Perjuangan", 18),
    ("討", "kanji_aktivitas", "utsu / tou", "トウ (TOU)", "う・つ (u-tsu)", "Membahas Debat", "Bicara 言 dengan tegas", "討論 (とうろん / touron)", "Diskusi / Debat", 10),
    ("戦", "kanji_kompetisi", "tatakau / sen", "セン (SEN)", "たたか・う (tataka-u)", "Perang Bertanding", "Senjata 単 dan tombak 戈", "戦争 (せんそう / sensou)", "Perang", 13),
    ("敗", "kanji_kompetisi", "yabureru / hai", "ハイ (HAI)", "やぶ・れる (yabu-reru)", "Kekalahan", "Kerang 貝 hancur dipukul", "失敗 (しっぱい / shippai)", "Kegagalan", 11),
    ("利", "kanji_abstrak", "kiku / ri", "リ (RI)", "き・く (ki-ku)", "Keuntungan", "Gandum 禾 dipotong pisau", "利用 (りよう / riyou)", "Penggunaan", 7),
    ("栄", "kanji_abstrak", "sakaeru / ei", "エイ (EI)", "さか・える (saka-eru)", "Kejayaan", "Bunga mekar di pohon 木", "栄光 (えいこう / eikou)", "Kejayaan", 9),
    ("誉", "kanji_abstrak", "homare / yo", "ヨ (YO)", "ほま・れ (homare)", "Pujian Kehormatan", "Bicara 言 memuji orang", "名誉 (めいよ / meiyo)", "Kehormatan", 13),
    ("賞", "kanji_sosial", "shou", "ショウ (SHOU)", "-", "Penghargaan", "Rumah 尚 memberi kerang", "賞品 (しょうひん / shouhin)", "Hadiah", 15),
    ("功", "kanji_abstrak", "kou", "コウ (KOU)", "-", "Prestasi Jasa", "Kerja 工 mengerahkan kekuatan", "成功 (せいこう / seikou)", "Keberhasilan", 5),
    ("績", "kanji_abstrak", "seki", "セキ (SEKI)", "-", "Hasil Kerja", "Benang 糸 dipintal", "実績 (じっせき / jisseki)", "Pencapaian", 17),
    ("修", "kanji_aktivitas", "osameru / shuu", "シュウ (SHUU)", "おさ・める (osa-meru)", "Mempelajari Pelatihan", "Orang イ melatih diri", "研修 (けんしゅう / kenshuu)", "Pelatihan kerja", 10),
    ("熟", "kanji_sifat", "juku", "ジュク (JUKU)", "こな・れる", "Matang Mahir", "Makanan dipanggang matang", "熟語 (じゅくご / jukugo)", "Idiom kanji", 15),
    ("達", "kanji_sosial", "tatsu", "タツ (TATSU)", "たち (tachi)", "Mencapai / Teman", "Jalan 辶 mencapai tujuan", "友達 (ともだち / tomodachi)", "Teman-teman", 12),
    ("技", "kanji_kehidupan", "waza / gi", "ギ (GI)", "わざ (waza)", "Keahlian", "Tangan 扌 dan kerja 工", "技術 (ぎじゅつ / gijutsu)", "Teknologi", 7),
    ("術", "kanji_kehidupan", "jutsu", "ジュツ (JUTSU)", "すべ (sube)", "Seni / Teknik", "Jalan 行 dan padi 朮", "技術 (ぎじゅつ / gijutsu)", "Teknik", 11),
    ("藝", "kanji_kehidupan", "gei", "ゲイ (GEI)", "-", "Kesenian", "Menanam tanaman seni", "芸術 (げいじゅつ / geijutsu)", "Karya seni", 18),
    ("才", "kanji_abstrak", "sai", "サイ (SAI)", "-", "Bakat / Usia", "Tunas tumbuh berbakat", "天才 (てんさい / tensai)", "Orang jenius", 3),
    ("姿", "kanji_sifat", "sugata / shi", "シ (SHI)", "すがた (sugata)", "Penampilan", "Wanita 女 yang anggun", "姿勢 (しせい / shisei)", "Postur tubuh", 9),
    ("勢", "kanji_abstrak", "sei", "セイ (SEI)", "いきお・い", "Momentum Kekuatan", "Tanaman dan kekuatan pesat", "姿勢 (しせい / shisei)", "Sikap / Momentum", 13),
    ("態", "kanji_abstrak", "tai", "タイ (TAI)", "-", "Kondisi Keadaan", "Gajah 能 dan hati 心", "状態 (じょうたい / joutai)", "Kondisi", 14),
    ("度", "kanji_abstrak", "do", "ド (DO)", "たび (tabi)", "Derajat / Kali", "Gedung 广 mengukur", "一度 (いちど / ichido)", "Satu kali", 9),
    ("統", "kanji_abstrak", "tou", "トウ (TOU)", "す・べる", "Penyatuan", "Benang 糸 menyatukan", "統一 (とういつ / touitsu)", "Penyatuan", 12),
    ("化", "kanji_abstrak", "ka", "カ (KA)", "ば・ける (bake-ru)", "Perubahan", "Dua orang 𠂉 七 berubah", "文化 (ぶんか / bunka)", "Kebudayaan", 4),
    ("宗", "kanji_sosial", "shuu", "シュウ (SHUU)", "-", "Agama", "Atap 宀 dan altar 示", "宗教 (しゅうきょう / shuukyou)", "Agama", 8),
    ("教", "kanji_sosial", "oshieru / kyou", "キョウ (KYOU)", "おし・える (oshi-eru)", "Mengajar Agama", "Anak diajari dengan tegas", "教科書 (きょうかしょ / kyouhasho)", "Buku pelajaran", 11),
    ("哲", "kanji_abstrak", "tetsu", "テツ (TETSU)", "-", "Filsafat", "Mulut 口 dan kapak 折", "哲学 (てつがく / tetsugaku)", "Filsafat", 10),
    ("儀", "kanji_sosial", "gi", "ギ (GI)", "-", "Etiket Upacara", "Orang イ beretika adil", "礼儀 (れいぎ / reigi)", "Sopan santun", 15),
    ("節", "kanji_kehidupan", "setsu", "セツ (SETSU)", "ふし (fushi)", "Musim / Hemat", "Bambu 竹 dipotong rapi", "季節 (きせつ / kisetsu)", "Musim cuaca", 13)
]

# Add to seen_kanji and construct entries
final_n3_entries = []

# First, extract existing entries from text_n3 so we don't lose any of the existing 193
existing_n3_matches = re.findall(r'(\{\s*id:\s*\'kj-n3-[^\']+\'.*?\}\s*\,)', text_n3, re.DOTALL)
print(f"Extracted existing raw N3 blocks: {len(existing_n3_matches)}")

# Now add additional_n3_kanji_data
count_new = 0
for k, subCat, read, ony, kun, mean, mnem, exJp, exId, strk in additional_n3_kanji_data:
    k_clean = k.strip()
    if k_clean not in seen_kanji:
        seen_kanji.add(k_clean)
        count_new += 1
        entry_str = f"""  {{
    id: 'kj-n3-{k_clean}',
    category: 'kanji',
    subCategory: '{subCat}',
    japanese: '{k_clean}',
    reading: '{read}',
    onyomi: '{ony}',
    kunyomi: '{kun}',
    meaningId: '{mean}',
    mnemonic: '{mnem}',
    exampleJp: '{exJp}',
    exampleId: '{exId}',
    strokes: {strk},
    level: 'N3'
  }},"""
        final_n3_entries.append(entry_str)

print(f"Added {count_new} new unique N3 entries")
print(f"Total Unique Kanji overall: {len(seen_kanji)}")

