import fs from 'fs';
import path from 'path';

export interface RawVocab {
  kanji: string;
  reading: string;
  furigana: string;
  meaningId: string;
  exampleJp: string;
  exampleId: string;
  level: 'N5' | 'N4';
  subCategory: string;
}

const list: RawVocab[] = [];

function add(kanji: string, reading: string, furigana: string, meaningId: string, exampleJp: string, exampleId: string, level: 'N5' | 'N4', subCategory: string) {
  list.push({ kanji, reading, furigana, meaningId, exampleJp, exampleId, level, subCategory });
}

// 1. KATA KERJA (VERBS) ~210 items
const vData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["行く", "iku", "いく", "Pergi", "明日東京へ行きます。", "Besok saya pergi ke Tokyo.", "N5"],
  ["来る", "kuru", "くる", "Datang", "友達がうちへ来ます。", "Teman datang ke rumah saya.", "N5"],
  ["帰る", "kaeru", "かえる", "Pulang", "午後6時に家へ帰ります。", "Saya pulang ke rumah jam 6 sore.", "N5"],
  ["食べる", "taberu", "たべる", "Makan", "朝ご飯を食べました。", "Saya sudah sarapan pagi.", "N5"],
  ["飲む", "nomu", "のむ", "Minum", "冷たい水を飲みます。", "Saya minum air dingin.", "N5"],
  ["見る", "miru", "みる", "Melihat / Menonton", "テレビで映画を見ます。", "Saya menonton film di televisi.", "N5"],
  ["聞く", "kiku", "きく", "Mendengar / Bertanya", "日本の音楽を聞きます。", "Saya mendengarkan musik Jepang.", "N5"],
  ["読む", "yomu", "よむ", "Membaca", "毎晩本を読みます。", "Saya membaca buku setiap malam.", "N5"],
  ["書く", "kaku", "かく", "Menulis", "手紙を書いています。", "Saya sedang menulis surat.", "N5"],
  ["話す", "hanasu", "はなす", "Berbicara", "日本語で話しましょう。", "Mari berbicara dalam bahasa Jepang.", "N5"],
  ["買う", "kau", "かう", "Membeli", "新しい靴を買いました。", "Saya membeli sepatu baru.", "N5"],
  ["売る", "uru", "うる", "Menjual", "車を売りました。", "Saya telah menjual mobil.", "N5"],
  ["待つ", "matsu", "まつ", "Menunggu", "駅の前で待ってください。", "Tolong tunggu di depan stasiun.", "N5"],
  ["会う", "au", "あう", "Bertemu", "友達に会います。", "Saya bertemu teman.", "N5"],
  ["遊ぶ", "asobu", "あそぶ", "Bermain", "公園で子供と遊びます。", "Bermain dengan anak di taman.", "N5"],
  ["急ぐ", "isogu", "いそぐ", "Buru-buru / Bergegas", "時間がないので急ぎます。", "Karena tidak ada waktu, saya buru-buru.", "N5"],
  ["泳ぐ", "oyogu", "およぐ", "Berenang", "海で泳ぐのが好きです。", "Saya suka berenang di laut.", "N5"],
  ["取る", "toru", "とる", "Mengambil", "塩を取ってください。", "Tolong ambilkan garam.", "N5"],
  ["撮る", "toru", "とる", "Memotret / Mengambil foto", "写真を撮りましょう。", "Ayo berfoto bersama.", "N5"],
  ["知る", "shiru", "しる", "Mengetahui / Kenal", "その人を知っていますか？", "Apakah kamu kenal orang itu?", "N5"],
  ["分かる", "wakaru", "わかる", "Mengerti / Paham", "意味がよく分かります。", "Saya sangat mengerti artinya.", "N5"],
  ["歩く", "aruku", "あるく", "Berjalan kaki", "毎日30分歩きます。", "Saya berjalan kaki 30 menit setiap hari.", "N5"],
  ["走る", "hashiru", "はしる", "Berlari", "公園を走っています。", "Saya sedang berlari di taman.", "N5"],
  ["立つ", "tatsu", "たつ", "Berdiri", "ドアの前に立ちます。", "Berdiri di depan pintu.", "N5"],
  ["座る", "suwaru", "すわる", "Duduk", "椅子に座ってください。", "Silakan duduk di kursi.", "N5"],
  ["持つ", "motsu", "もつ", "Membawa / Memegang", "荷物を持ちましょうか？", "Bolehkah saya bantu bawakan barangnya?", "N5"],
  ["作る", "tsukuru", "つくる", "Membuat", "晩ご飯を作ります。", "Saya membuat makan malam.", "N5"],
  ["使う", "tsukau", "つかう", "Menggunakan / Memakai", "パソコンを使います。", "Saya menggunakan komputer.", "N5"],
  ["置く", "oku", "おく", "Meletakkan / Menaruh", "机の上に置きました。", "Saya meletakkannya di atas meja.", "N5"],
  ["住む", "sumu", "すむ", "Tinggal / Berdiam di", "東京に住んでいます。", "Saya tinggal di Tokyo.", "N5"],
  ["働く", "hataraku", "はたらく", "Bekerja", "病院で働いています。", "Saya bekerja di rumah sakit.", "N5"],
  ["休む", "yasumu", "やすむ", "Istirahat / Libur", "今日は仕事を休みます。", "Hari ini saya libur bekerja.", "N5"],
  ["教える", "oshieru", "おしえる", "Mengajar / Memberitahu", "日本語を教えてください。", "Tolong ajarkan bahasa Jepang kepada saya.", "N5"],
  ["習う", "narau", "ならう", "Belajar (dari orang lain)", "ピアノを習っています。", "Saya belajar les piano.", "N5"],
  ["貸す", "kasu", "かす", "Meminjamkan", "傘を貸してください。", "Tolong pinjamkan saya payung.", "N5"],
  ["借りる", "kariru", "かりる", "Meminjam", "図書館で本を借りました。", "Saya meminjam buku di perpustakaan.", "N5"],
  ["返す", "kaesu", "かえす", "Mengembalikan", "本を返します。", "Saya mengembalikan buku.", "N5"],
  ["起きる", "okiru", "おきる", "Bangun tidur", "朝6時に起きます。", "Saya bangun jam 6 pagi.", "N5"],
  ["寝る", "neru", "ねる", "Tidur", "夜11時に寝ます。", "Saya tidur jam 11 malam.", "N5"],
  ["開ける", "akeru", "あける", "Membuka (pintu/jendela)", "窓を開けてください。", "Tolong buka jendelanya.", "N5"],
  ["閉める", "shimeru", "しめる", "Menutup (pintu/jendela)", "ドアを閉めました。", "Saya telah menutup pintu.", "N5"],
  ["開く", "aku", "あく", "Terbuka (sendirinya)", "ドアが開きました。", "Pintunya terbuka.", "N5"],
  ["閉まる", "shimaru", "しまる", "Tertutup (sendirinya)", "店が閉まりました。", "Tokonya sudah tutup.", "N5"],
  ["つける", "tsukeru", "つける", "Menyalakan (lampu/alat)", "エアコンをつけます。", "Saya menyalakan AC.", "N5"],
  ["消す", "kesu", "けす", "Mematikan / Menghapus", "電気を消してください。", "Tolong matikan lampu.", "N5"],
  ["入る", "hairu", "はいる", "Masuk", "部屋に入ります。", "Saya masuk ke kamar.", "N5"],
  ["出る", "deru", "でる", "Keluar", "家を出ます。", "Saya keluar dari rumah.", "N5"],
  ["入れる", "ireru", "いれる", "Memasukkan", "鞄に財布を入れます。", "Saya memasukkan dompet ke dalam tas.", "N5"],
  ["出す", "dasu", "だす", "Mengeluarkan / Menyerahkan", "宿題を出します。", "Saya mengumpulkan tugas PR.", "N5"],
  ["乗る", "noru", "のる", "Naik (kendaraan)", "電車に乗ります。", "Saya naik kereta.", "N5"],
  ["降りる", "oriru", "おりる", "Turun (dari kendaraan)", "バスを降ります。", "Saya turun dari bus.", "N5"],
  ["乗り換える", "norikaeru", "のりかえる", "Pindah kendaraan / Transit", "次の駅で乗り換えます。", "Transit di stasiun berikutnya.", "N4"],
  ["浴びる", "abiru", "あびる", "Mandi shower", "毎朝シャワーを浴びます。", "Saya mandi shower setiap pagi.", "N5"],
  ["洗う", "arau", "あらう", "Mencuci", "手をよく洗ってください。", "Cucilah tanganmu dengan bersih.", "N5"],
  ["磨く", "migaku", "みがく", "Menggosok / Menyikat (gigi)", "食後に歯を磨きます。", "Saya menggosok gigi setelah makan.", "N5"],
  ["着る", "kiru", "きる", "Memakai (pakaian atas)", "上着を着ます。", "Saya memakai jaket luar.", "N5"],
  ["履く", "haku", "はく", "Memakai (celana/sepatu)", "新しい靴を履きます。", "Saya memakai sepatu baru.", "N5"],
  ["かぶる", "kaburu", "かぶる", "Memakai (topi)", "帽子をかぶっています。", "Saya sedang memakai topi.", "N5"],
  ["脱ぐ", "nugu", "ぬぐ", "Melepas pakaian / sepatu", "玄関で靴を脱ぎます。", "Lepas sepatu di pintu masuk.", "N5"],
  ["送る", "okuru", "おくる", "Mengirim", "メールを送りました。", "Saya telah mengirim surel.", "N5"],
  ["届く", "todoku", "とどく", "Sampai / Tiba (paket/surat)", "荷物が届きました。", "Paketnya telah sampai.", "N4"],
  ["渡す", "watasu", "わたす", "Menyerahkan", "プレゼントを渡します。", "Menyerahkan kado.", "N5"],
  ["渡る", "wataru", "わたる", "Menyeberang", "信号を渡ります。", "Menyeberang di lampu merah.", "N5"],
  ["曲がる", "magaru", "まがる", "Belok", "交差点を右へ曲がります。", "Belok kanan di perempatan.", "N5"],
  ["止まる", "tomaru", "とまる", "Berhenti (kendaraan)", "車が止まりました。", "Mobilnya berhenti.", "N5"],
  ["止める", "tomeru", "とめる", "Menghentikan / Memarkir", "車を駐車場に止めます。", "Memarkir mobil di area parkir.", "N5"],
  ["泊まる", "tomaru", "とまる", "Menginap", "温泉旅館に泊まります。", "Menginap di penginapan onsen.", "N4"],
  ["始まる", "hajimaru", "はじまる", "Dimulai", "授業が始まります。", "Pelajaran dimulai.", "N5"],
  ["始める", "hajimeru", "はじめる", "Memulai", "日本語の勉強を始めました。", "Saya mulai belajar bahasa Jepang.", "N5"],
  ["終わる", "owaru", "おわる", "Selesai / Berakhir", "仕事が終わりました。", "Pekerjaan sudah selesai.", "N5"],
  ["覚える", "oboeru", "おぼえる", "Mengingat / Menghapal", "漢字をたくさん覚えます。", "Saya menghapal banyak kanji.", "N5"],
  ["忘れる", "wasureru", "わすれる", "Lupa", "宿題を忘れました。", "Saya lupa mengerjakan PR.", "N5"],
  ["思い出す", "omoidasu", "おもいだす", "Mengingat kembali / Teringat", "子供の頃を思い出します。", "Saya teringat masa kecil.", "N4"],
  ["考える", "kangaeru", "かんがえる", "Memikirkan", "将来のことを考えます。", "Saya memikirkan masa depan.", "N4"],
  ["思う", "omou", "おもう", "Mengira / Berpikir", "そう思います。", "Saya berpikir begitu.", "N5"],
  ["言う", "iu", "いう", "Berkata / Mengatakan", "「おはよう」と言いました。", "Dia mengucapkan selamat pagi.", "N5"],
  ["呼ぶ", "yobu", "よぶ", "Memanggil", "タクシーを呼びます。", "Saya memanggil taksi.", "N5"],
  ["歌う", "utau", "うたう", "Bernyanyi", "カラオケで歌います。", "Bernyanyi di karaoke.", "N5"],
  ["踊る", "odoru", "おどる", "Menari", "日本の伝統的な踊りです。", "Tarian tradisional Jepang.", "N5"],
  ["笑う", "warau", "わらう", "Tertawa / Tersenyum", "みんなで楽しく笑いました。", "Semua orang tertawa bahagia.", "N5"],
  ["泣く", "naku", "なく", "Menangis", "悲しくて泣きました。", "Saya menangis karena sedih.", "N5"],
  ["怒る", "okoru", "おこる", "Marah", "先生が怒りました。", "Guru marah.", "N4"],
  ["頼む", "tanomu", "たのむ", "Meminta tolong / Memesan", "手伝いを頼みます。", "Saya meminta bantuan.", "N5"],
  ["手伝う", "tetsudau", "てつだう", "Membantu", "母の料理を手伝います。", "Saya membantu masakan ibu.", "N5"],
  ["直す", "naosu", "なおす", "Memperbaiki / Membetulkan", "パソコンを直します。", "Saya memperbaiki komputer.", "N4"],
  ["壊す", "kowasu", "こわす", "Merusak", "おもちゃを壊しました。", "Merusak mainan.", "N4"],
  ["壊れる", "kowareru", "こわれる", "Rusak", "椅子が壊れました。", "Kursinya patah / rusak.", "N4"],
  ["落とす", "otosu", "おとす", "Menjatuhkan", "財布を落としました。", "Saya menjatuhkan dompet.", "N4"],
  ["落ちる", "ochiru", "おちる", "Jatuh (sendirinya)", "木の葉が落ちます。", "Daun-daun pohon berguguran.", "N4"],
  ["拾う", "hirou", "ひろう", "Memungut / Mengambil", "ゴミを拾います。", "Saya memungut sampah.", "N4"],
  ["捨てる", "suteru", "すてる", "Membuang", "ゴミを捨てないでください。", "Jangan buang sampah di sini.", "N4"],
  ["探す", "sagasu", "さがす", "Mencari", "鍵を探しています。", "Saya sedang mencari kunci.", "N4"],
  ["見つける", "mitsukeru", "みつける", "Menemukan", "いい方法を見つけました。", "Saya menemukan cara yang bagus.", "N4"],
  ["選ぶ", "erabu", "えらぶ", "Memilih", "好きな色を選んでください。", "Silakan pilih warna favorit.", "N4"],
  ["決める", "kimeru", "きめる", "Memutuskan", "日程を決めます。", "Saya memutuskan tanggalnya.", "N4"],
  ["勝つ", "katsu", "かつ", "Menang", "試合に勝ちました。", "Menang dalam pertandingan.", "N4"],
  ["負ける", "makeru", "まける", "Kalah", "試合に負けました。", "Kalah dalam pertandingan.", "N4"],
  ["生きる", "ikiru", "いきる", "Hidup", "元気に生きています。", "Hidup dengan sehat.", "N4"],
  ["死ぬ", "shinu", "しぬ", "Mati / Meninggal", "魚が死にました。", "Ikannya mati.", "N5"],
  ["咲く", "saku", "さく", "Mekar (bunga)", "桜の花が咲きました。", "Bunga sakura telah mekar.", "N5"],
  ["降る", "furu", "ふる", "Turun (hujan/salju)", "雪が降っています。", "Salju sedang turun.", "N5"],
  ["晴れる", "hareru", "はれる", "Cerah (cuaca)", "明日晴れます。", "Besok akan cerah.", "N5"],
  ["曇る", "kumoru", "くもる", "Mendung (cuaca)", "空が曇っています。", "Langit sedang mendung.", "N5"],
  ["吹く", "fuku", "ふく", "Bertiup (angin)", "風が強く吹いています。", "Angin bertiup kencang.", "N5"],
  ["喜ぶ", "yorokobu", "よろこぶ", "Senang / Bergembira", "子供たちが喜んでいます。", "Anak-anak sangat bergembira.", "N4"],
  ["驚く", "odoroku", "おどろく", "Kaget / Terkejut", "ニュースに驚きました。", "Saya terkejut mendengar berita.", "N4"],
  ["信じる", "shinjiru", "しんじる", "Percaya", "あなたを信じています。", "Saya percaya kepadamu.", "N4"],
  ["祈る", "inoru", "いのる", "Berdoa", "健康を祈ります。", "Saya mendoakan kesehatanmu.", "N4"],
  ["楽しむ", "tanoshimu", "たのしむ", "Menikmati", "旅行を楽しみます。", "Menikmati liburan.", "N4"],
  ["結婚する", "kekkon suru", "けっこんする", "Menikah", "来年結婚します。", "Menikah tahun depan.", "N5"],
  ["勉強する", "benkyou suru", "べんきょうする", "Belajar", "毎晩勉強します。", "Belajar setiap malam.", "N5"],
  ["旅行する", "ryokou suru", "りょこうする", "Berwisata / Bepergian", "日本へ旅行します。", "Berwisata ke Jepang.", "N5"],
  ["買い物する", "kaimono suru", "かいものする", "Berbelanja", "スーパーで買い物します。", "Belanja di supermarket.", "N5"],
  ["散歩する", "sanpo suru", "さんぽする", "Jalan-jalan santai", "公園を散歩します。", "Jalan santai di taman.", "N5"],
  ["運動する", "undou suru", "うんどうする", "Berolahraga", "週末に運動します。", "Olahraga di akhir pekan.", "N5"],
  ["練習する", "renshuu suru", "れんしゅうする", "Berlatih", "会話を練習します。", "Melatih percakapan.", "N5"],
  ["電話する", "denwa suru", "でんわする", "Menelepon", "友達に電話します。", "Menelepon teman.", "N5"],
  ["案内する", "annai suru", "あんないする", "Memandu jalan", "町を案内します。", "Memandu keliling kota.", "N4"],
  ["説明する", "setsumei suru", "せつめいする", "Menjelaskan", "ルールを説明します。", "Menjelaskan aturan.", "N4"],
  ["予約する", "yoyaku suru", "よやくする", "Memesan / Reservasi", "ホテルを予約しました。", "Memesan kamar hotel.", "N4"],
  ["注文する", "chuumon suru", "ちゅうもんする", "Memesan makanan / barang", "ピザを注文します。", "Memesan pizza.", "N4"],
  ["注意する", "chuui suru", "ちゅういする", "Berhati-hati / Memperhatikan", "車に注意してください。", "Hati-hati dengan mobil.", "N5"],
  ["準備する", "junbi suru", "じゅんびする", "Mempersiapkan", "試験の準備をします。", "Mempersiapkan ujian.", "N5"],
  ["片付ける", "katazukeru", "かたづける", "Membereskan / Merapikan", "机を片付けます。", "Merapikan meja.", "N4"],
  ["掃除する", "souji suru", "そうじする", "Membersihkan ruangan", "部屋を掃除します。", "Membersihkan kamar.", "N5"],
  ["洗濯する", "sentaku suru", "せんたくする", "Mencuci pakaian", "服を洗濯します。", "Mencuci pakaian.", "N5"],
  ["連絡する", "renraku suru", "れんらくする", "Menghubungi", "後で連絡します。", "Nanti saya hubungi.", "N5"],
  ["相談する", "soudan suru", "そうだんする", "Berkonsultasi", "先生に相談します。", "Konsultasi ke guru.", "N4"],
  ["出席する", "shusseki suru", "しゅっせきする", "Menghadiri", "会議に出席します。", "Menghadiri rapat.", "N4"],
  ["欠席する", "kesseki suru", "けっせきする", "Absen / Tidak hadir", "授業を欠席します。", "Absen dari kelas.", "N4"],
  ["合格する", "goukaku suru", "ごうかくする", "Lulus ujian", "試験に合格しました。", "Lulus ujian.", "N4"],
  ["失敗する", "shippai suru", "しっぱいする", "Gagal", "料理に失敗しました。", "Gagal dalam memasak.", "N4"],
  ["成功する", "seikou suru", "せいこうする", "Berhasil / Sukses", "計画が成功しました。", "Rencananya berhasil.", "N4"],
  ["入院する", "nyuuin suru", "にゅういんする", "Rawat inap", "病院に入院します。", "Masuk rawat inap rumah sakit.", "N4"],
  ["退院する", "taiin suru", "たいいんする", "Keluar dari rumah sakit", "明日退院します。", "Besok pulang dari rumah sakit.", "N4"],
  ["修理する", "shuuri suru", "しゅうりする", "Memperbaiki", "車を修理します。", "Memperbaiki mobil.", "N4"],
  ["故障する", "koshou suru", "こしょうする", "Mogok / Rusak", "時計が故障しました。", "Jamnya rusak.", "N4"],
  ["引っ越す", "hikkosu", "ひっこす", "Pindah rumah", "来月引っ越します。", "Bulan depan pindah rumah.", "N4"],
  ["謝る", "ayamaru", "あやまる", "Minta maaf", "素直に謝ります。", "Minta maaf dengan jujur.", "N4"],
  ["許す", "yurusu", "ゆるす", "Memaafkan", "友達を許します。", "Memaafkan teman.", "N4"],
  ["褒める", "homeru", "ほめる", "Memuji", "子供を褒めます。", "Memuji anak.", "N4"],
  ["叱る", "shikaru", "しかる", "Memarahi", "母に叱られました。", "Dimarahi oleh ibu.", "N4"],
  ["断る", "kotowaru", "ことわる", "Menolak", "誘いを断ります。", "Menolak ajakan.", "N4"],
  ["届ける", "todokeru", "とどける", "Mengantarkan paket", "荷物を届けます。", "Mengantarkan barang.", "N4"],
  ["運ぶ", "hakobu", "はこぶ", "Mengangkut / Membawa", "荷物を運びます。", "Mengangkut barang.", "N4"],
  ["変わる", "kawaru", "かわる", "Berubah", "天気が変わりました。", "Cuacanya berubah.", "N4"],
  ["変える", "kaeru", "かえる", "Mengubah", "予定を変えます。", "Mengubah jadwal.", "N4"],
  ["続く", "tsuzuku", "つづく", "Berlanjut", "雨が続いています。", "Hujannya terus berlanjut.", "N4"],
  ["続ける", "tsuzukeru", "つづける", "Melanjutkan", "勉強を続けます。", "Melanjutkan belajar.", "N4"],
  ["止む", "yamu", "やむ", "Reda (hujan/angin)", "雨が止みました。", "Hujannya sudah reda.", "N4"],
  ["増える", "fueru", "ふえる", "Bertambah", "人数が増えました。", "Jumlah orang bertambah.", "N4"],
  ["減る", "heru", "へる", "Berkurang", "体重が減りました。", "Berat badan berkurang.", "N4"],
  ["上がる", "agaru", "あがる", "Naik (suhu/harga)", "物価が上がります。", "Harga-harga naik.", "N4"],
  ["下がる", "sagaru", "さがる", "Turun (suhu/harga)", "熱が下がりました。", "Demamnya sudah turun.", "N4"],
  ["冷える", "hieru", "ひえる", "Menjadi dingin", "夜は冷えます。", "Malam hari terasa dingin.", "N4"],
  ["温まる", "atatamaru", "あたたまる", "Menjadi hangat", "体が温まりました。", "Badan menjadi hangat.", "N4"],
  ["汚す", "yogosu", "よごす", "Mengotori", "服を汚しました。", "Mengotori pakaian.", "N4"],
  ["汚れる", "yogoreru", "よごれる", "Kotor", "手が汚れました。", "Tangan menjadi kotor.", "N4"],
  ["無くす", "nakusu", "なくす", "Menghilangkan", "鍵を無くしました。", "Menghilangkan kunci.", "N5"],
  ["無くなる", "nakunaru", "なくなる", "Hilang / Habis", "お金が無くなりました。", "Uangnya habis.", "N4"],
  ["受ける", "ukeru", "うける", "Mengikuti ujian / Menerima", "テストを受けます。", "Mengikuti ujian tes.", "N4"],
  ["見送る", "miokuru", "みおくる", "Mengantar kepergian", "空港で見送ります。", "Mengantar di bandara.", "N4"],
  ["迎える", "mukaeru", "むかえる", "Menjemput / Menyambut", "客を迎えます。", "Menyambut tamu.", "N4"],
  ["焼く", "yaku", "やく", "Memanggang", "肉を焼きます。", "Memanggang daging.", "N4"],
  ["煮る", "niru", "にる", "Merebus bumbu", "魚を煮ます。", "Merebus ikan dengan bumbu.", "N4"],
  ["揚げる", "ageru", "あげる", "Menggoreng", "エビを揚げます。", "Menggoreng udang.", "N4"],
  ["炒める", "itameru", "いため", "Menumis", "野菜を炒めます。", "Menumis sayur.", "N4"],
  ["沸かす", "wakasu", "わかす", "Merebus air", "お湯を沸かします。", "Merebus air.", "N4"],
  ["冷やす", "hiyasu", "ひやす", "Mendinginkan", "スイカを冷やします。", "Mendinginkan semangka.", "N4"],
  ["混ぜる", "mazeru", "まぜる", "Mencampur / Mengaduk", "卵を混ぜます。", "Mengaduk telur.", "N4"],
  ["踏む", "fumu", "ふむ", "Menginjak", "足を踏まれました。", "Kaki saya terinjak.", "N4"],
  ["盗む", "nusumu", "ぬすむ", "Mencuri", "自転車を盗まれました。", "Sepeda saya dicuri.", "N4"],
  ["刺す", "sasu", "さす", "Menyengat / Menusuk", "虫に刺されました。", "Disengat serangga.", "N4"],
  ["噛む", "kamu", "かむ", "Menggigit / Mengunyah", "よく噛んで食べます。", "Mengunyah makanan dengan baik.", "N4"],
  ["誘う", "sasou", "さそう", "Mengajak", "ランチに誘います。", "Mengajak makan siang.", "N4"],
  ["もらう", "morau", "もらう", "Menerima dari orang lain", "花をもらいました。", "Menerima bunga.", "N5"],
  ["あげる", "ageru", "あげる", "Memberikan ke orang lain", "プレゼントをあげます。", "Memberikan kado.", "N5"],
  ["くれる", "kureru", "くれる", "Memberi ke saya", "本をくれました。", "Dia memberi saya buku.", "N5"],
  ["吸う", "suu", "すう", "Menghisap / Menghirup", "たばこを吸いません。", "Saya tidak merokok.", "N5"],
  ["鳴る", "naru", "なる", "Berbunyi (bel/telepon)", "ベルが鳴りました。", "Belnya berbunyi.", "N4"],
  ["太る", "futoru", "ふとる", "Bertambah gemuk", "少し太りました。", "Sedikit bertambah gemuk.", "N4"],
  ["痩せる", "yaseru", "やせる", "Menjadi kurus / Langsing", "運動で痩せました。", "Menjadi langsing karena olahraga.", "N4"],
  ["晴れ渡る", "harewataru", "はれわたる", "Cerah benderang", "空が晴れ渡っています。", "Langit sangat cerah benderang.", "N4"],
  ["乗り遅れる", "noriokureru", "のりおくれる", "Ketinggalan kereta/bus", "電車に乗り遅れました。", "Ketinggalan kereta.", "N4"],
  ["間に合う", "maniau", "まにあう", "Keburu / Tepat waktu", "時間通りに間に合いました。", "Tepat waktu sesuai jadwal.", "N4"],
  ["遅れる", "okureru", "おくれる", "Terlambat", "時間に遅れました。", "Terlambat dari waktu.", "N4"],
  ["役に立つ", "yaku ni tatsu", "やくにたつ", "Berguna / Bermanfaat", "とても役に立ちます。", "Sangat bermanfaat.", "N4"],
  ["世話をする", "sewa o suru", "せわをする", "Merawat / Mengurus", "犬の世話をします。", "Merawat anjing peliharaan.", "N4"],
  ["化粧する", "keshou suru", "けしょうする", "Berdandan / Merias wajah", "毎朝化粧をします。", "Berdandan setiap pagi.", "N4"],
  ["着替える", "kigaeru", "きがえる", "Ganti pakaian", "部屋で着替えます。", "Berganti pakaian di kamar.", "N4"],
  ["乾く", "kawaku", "かわく", "Kering (pakaian/tanah)", "洗濯物が乾きました。", "Cucian baju sudah kering.", "N4"],
  ["濡れる", "nureru", "ぬれる", "Basah terkena air", "雨で服が濡れました。", "Pakaian basah terkena hujan.", "N4"],
  ["滑る", "suberu", "すべる", "Tergelincir / Licin", "雪道で滑りました。", "Tergelincir di jalan bersalju.", "N4"],
  ["転ぶ", "korobu", "ころぶ", "Tersandung jatuh", "道で転びました。", "Jatuh tersandung di jalan.", "N4"],
  ["ぶつかる", "butsukaru", "ぶつかる", "Menabrak / Bertabrakan", "壁にぶつかりました。", "Menabrak dinding.", "N4"],
  ["折れる", "oreru", "おれる", "Patah (cabang/tulang)", "木の枝が折れました。", "Dahan pohon patah.", "N4"],
  ["破れる", "yabureru", "やぶれる", "Robek", "服が破れました。", "Bajunya robek.", "N4"],
  ["切れる", "kireru", "きれる", "Putus / Habis baterai", "電池が切れました。", "Baterainya habis.", "N4"],
  ["外す", "hazusu", "はずす", "Melepaskan kacamata/masker", "眼鏡を外します。", "Melepaskan kacamata.", "N4"],
  ["空く", "suku", "すく", "Kosong / Lapang", "お腹が空きました。", "Perut saya lapar / kosong.", "N5"],
  ["渇く", "kawaku", "かわく", "Haus (tenggorokan)", "喉が渇きました。", "Tenggorokan saya haus.", "N5"],
  ["訪ねる", "tazuneru", "たずねる", "Berkunjung", "先生の家を訪ねました。", "Saya berkunjung ke rumah guru.", "N4"],
  ["見つめる", "mitsumeru", "みつめる", "Menatap tajam", "星空を見つめます。", "Menatap langit berbintang.", "N4"],
  ["見上げる", "miageru", "みあげる", "Melihat ke atas", "東京タワーを見上げます。", "Melihat ke atas Tokyo Tower.", "N4"],
  ["見下ろす", "miorosu", "みおろす", "Melihat ke bawah", "山の上から見下ろします。", "Melihat ke bawah dari puncak gunung.", "N4"],
  ["立ち止まる", "tachidomaru", "たちどまる", "Berhenti melangkah sejenak", "道で立ち止まりました。", "Berhenti melangkah sejenak di jalan.", "N4"],
  ["留学する", "ryuugaku suru", "りゅうがくする", "Studi di luar negeri", "日本に留学します。", "Studi di Jepang.", "N5"],
  ["卒業する", "sotsugyou suru", "そつぎょうする", "Lulus sekolah", "高校を卒業しました。", "Lulus SMA.", "N5"],
  ["就職する", "shuushoku suru", "しゅうしょくする", "Mendapat pekerjaan", "会社に就職しました。", "Mendapat pekerjaan di kantor.", "N4"],
  ["退職する", "taishoku suru", "たいしょくする", "Pensiun / Mundur kerja", "定年で退職します。", "Pensiun karena batas usia.", "N4"],
  ["通勤する", "tsuukin suru", "つうきんする", "Berangkat kerja", "満員電車で通勤します。", "Berangkat kerja di kereta penuh.", "N4"],
  ["通学する", "tsuugaku suru", "つうがくする", "Berangkat sekolah", "バスで通学します。", "Berangkat sekolah naik bus.", "N4"]
];

for (const v of vData) {
  add(v[0], v[1], v[2], v[3], v[4], v[5], v[6], 'kata_kerja');
}

// 2. KATA SIFAT (ADJECTIVES) ~140 items
const adjData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["大きい", "ookii", "おおきい", "Besar", "大きい家です。", "Rumah yang besar.", "N5"],
  ["小さい", "chiisai", "ちいさい", "Kecil", "小さい猫がいます。", "Ada kucing kecil.", "N5"],
  ["高い", "takai", "たかい", "Tinggi / Mahal", "背が高いです。", "Badannya tinggi.", "N5"],
  ["安い", "yasui", "やすい", "Murah", "この服は安いです。", "Baju ini murah.", "N5"],
  ["新しい", "atarashii", "あたらしい", "Baru", "新しい車を買いました。", "Membeli mobil baru.", "N5"],
  ["古い", "furui", "ふるい", "Lama / Kuno", "古い本を読みます。", "Membaca buku tua.", "N5"],
  ["良い / いい", "ii / yoi", "いい / よい", "Bagus / Baik", "とてもいい天気です。", "Cuaca sangat bagus.", "N5"],
  ["悪い", "warui", "わるい", "Buruk / Jahat", "体の調子が悪いです。", "Kondisi tubuh buruk.", "N5"],
  ["暑い", "atsui", "あつい", "Panas (suhu cuaca)", "今日はとても暑いです。", "Hari ini sangat panas.", "N5"],
  ["熱い", "atsui", "あつい", "Panas (benda/minuman)", "熱いお茶を飲みます。", "Minum teh panas.", "N5"],
  ["寒い", "samui", "さむい", "Dingin (suhu cuaca)", "冬はとても寒いです。", "Musim dingin sangat sejuk/dingin.", "N5"],
  ["冷たい", "tsumetai", "つめたい", "Dingin (benda/sikap)", "冷たい水をください。", "Minta air dingin tolong.", "N5"],
  ["暖かい", "atatakai", "あたたかい", "Hangat (suhu cuaca)", "春は暖かいです。", "Musim semi hangat.", "N5"],
  ["温かい", "atatakai", "あたたかい", "Hangat (makanan/hati)", "温かいスープです。", "Sup yang hangat.", "N5"],
  ["涼しい", "suzushii", "すずしい", "Sejuk", "秋の風は涼しいです。", "Angin musim gugur terasa sejuk.", "N5"],
  ["難しい", "muzukashii", "むずかしい", "Sulit / Sukar", "漢字は難しいです。", "Kanji itu sulit.", "N5"],
  ["易しい", "yasashii", "やさしい", "Mudah / Gampang", "テストは易しかったです。", "Ujiannya mudah.", "N5"],
  ["優しい", "yasashii", "やさしい", "Baik hati / Lemah lembut", "先生はとても優しいです。", "Guru sangat baik hati.", "N5"],
  ["面白い", "omoshiroi", "おもしろい", "Menarik / Lucu", "面白い映画を見ました。", "Menonton film menarik.", "N5"],
  ["つまらない", "tsumaranai", "つまらない", "Membosankan", "つまらない話です。", "Cerita yang membosankan.", "N5"],
  ["忙しい", "isogashii", "いそがしい", "Sibuk", "今週はとても忙しいです。", "Minggu ini sangat sibuk.", "N5"],
  ["暇", "hima", "ひま", "Senggang / Luang", "日曜日は暇です。", "Hari Minggu saya senggang.", "N5"],
  ["美味しい", "oishii", "おいしい", "Lezat / Enak", "日本の料理は美味しいです。", "Masakan Jepang enak.", "N5"],
  ["まずい", "mazui", "まずい", "Tidak enak", "このスープはまずいです。", "Sup ini rasanya tidak enak.", "N5"],
  ["甘い", "amai", "あまい", "Manis", "甘いお菓子が好きです。", "Suka camilan manis.", "N5"],
  ["辛い", "karai", "からい", "Pedas / Asin menusuk", "辛いカレーを食べます。", "Makan kari pedas.", "N5"],
  ["苦い", "nigai", "にがい", "Pahit", "苦いコーヒーが好きです。", "Suka kopi pahit.", "N5"],
  ["酸っぱい", "suppai", "すっぱい", "Asam / Kecut", "レモンは酸っぱいです。", "Lemon rasanya asam.", "N5"],
  ["塩辛い", "shiokarai", "しおからい", "Asin gurih", "この料理は少し塩辛いです。", "Masakan ini agak asin.", "N5"],
  ["近い", "chikai", "ちかい", "Dekat", "駅は家から近いです。", "Stasiun dekat dari rumah.", "N5"],
  ["遠い", "tooi", "とおい", "Jauh", "学校まで遠いです。", "Jauh sampai sekolah.", "N5"],
  ["速い", "hayai", "はやい", "Cepat (laju)", "新幹線はとても速いです。", "Shinkansen sangat cepat.", "N5"],
  ["早い", "hayai", "はやい", "Cepat / Awal (waktu)", "朝早く起きました。", "Bangun pagi-pagi sekali.", "N5"],
  ["遅い", "osoi", "おそい", "Lambat / Terlambat", "歩くのが遅いです。", "Berjalannya lambat.", "N5"],
  ["多い", "ooi", "おおい", "Banyak", "東京は人が多いです。", "Tokyo banyak orang.", "N5"],
  ["少ない", "sukunai", "すくない", "Sedikit", "雨の日が少ないです。", "Hari hujan sedikit.", "N5"],
  ["重い", "omoi", "おもい", "Berat", "この荷物は重いです。", "Barang ini berat.", "N5"],
  ["軽い", "karui", "かるい", "Ringan", "軽い鞄を買いました。", "Membeli tas yang ringan.", "N5"],
  ["明るい", "akarui", "あかるい", "Terang / Ceria", "部屋が明るいです。", "Kamarnya terang.", "N5"],
  ["暗い", "kurai", "くらい", "Gelap / Muram", "夜道は暗いです。", "Jalan malam gelap.", "N5"],
  ["広い", "hiroi", "ひろい", "Luas", "広い庭があります。", "Ada halaman luas.", "N5"],
  ["狭い", "semai", "せまい", "Sempit", "部屋が狭いです。", "Kamarnya sempit.", "N5"],
  ["長い", "nagai", "ながい", "Panjang", "髪が長いです。", "Rambutnya panjang.", "N5"],
  ["短い", "mijikai", "みじかい", "Pendek (ukuran)", "短いスカートです。", "Rok pendek.", "N5"],
  ["低い", "hikui", "ひくい", "Rendah", "低い山に登ります。", "Mendaki gunung rendah.", "N5"],
  ["強い", "tsuyoi", "つよい", "Kuat", "風が強いです。", "Anginnya kuat.", "N5"],
  ["弱い", "yowai", "よわい", "Lemah", "体が弱いです。", "Tubuhnya lemah.", "N5"],
  ["太い", "futoi", "ふとい", "Tebal / Gemuk", "太いペンで書きます。", "Menulis dengan spidol tebal.", "N5"],
  ["細い", "hosoi", "ほそい", "Ramping / Tipis", "細い道を通ります。", "Melewati jalan sempit/ramping.", "N5"],
  ["厚い", "atsui", "あつい", "Tebal (buku/kain)", "厚い本を読みます。", "Membaca buku tebal.", "N5"],
  ["薄い", "usui", "うすい", "Tipis / Encer / Hambar", "薄い紙です。", "Kertas tipis.", "N5"],
  ["痛い", "itai", "いたい", "Sakit / Nyeri", "頭が痛いです。", "Kepala saya sakit.", "N5"],
  ["痒い", "kayui", "かゆい", "Gatal", "腕が痒いです。", "Lengan saya gatal.", "N4"],
  ["危ない", "abunai", "あぶない", "Berbahaya", "危ないですから離れてください。", "Berbahaya, tolong menjauh.", "N5"],
  ["楽しい", "tanoshii", "たのしい", "Menyenangkan", "パーティーは楽しかったです。", "Pesta sangat menyenangkan.", "N5"],
  ["嬉しい", "ureshii", "うれしい", "Senang / Gembira hati", "合格して嬉しいです。", "Senang karena lulus.", "N5"],
  ["悲しい", "kanashii", "かなしい", "Sedih", "悲しい映画を見ました。", "Menonton film sedih.", "N5"],
  ["寂しい", "sabishii", "さびしい", "Kesepian / Rindu", "一人で寂しいです。", "Sendirian terasa sepi.", "N5"],
  ["恥ずかしい", "hazukashii", "はずかしい", "Malu", "間違えて恥ずかしいです。", "Malu karena salah.", "N4"],
  ["怖い", "kowai", "こわい", "Menakutkan / Takut", "お化けが怖いです。", "Takut hantu.", "N5"],
  ["羨ましい", "urayamashii", "うらやましい", "Iri hati (positif)", "あなたが羨ましいです。", "Saya iri padamu.", "N4"],
  ["欲しい", "hoshii", "ほしい", "Ingin / Mau punya", "新しいスマホが欲しいです。", "Ingin punya smartphone baru.", "N5"],
  ["好き", "suki", "すき", "Suka / Gemar", "アニメが好きです。", "Saya suka anime.", "N5"],
  ["嫌い", "kirai", "きらい", "Benci / Tidak suka", "野菜が嫌いです。", "Tidak suka sayuran.", "N5"],
  ["大好き", "daisuki", "だいすき", "Sangat suka", "ラーメンが大好きです。", "Sangat suka ramen.", "N5"],
  ["大嫌い", "daikirai", "だいきらい", "Sangat benci", "虫が大嫌いです。", "Sangat benci serangga.", "N5"],
  ["上手", "jouzu", "じょうず", "Pandai / Mahir", "料理が上手ですね。", "Pandai memasak ya.", "N5"],
  ["下手", "heta", "へた", "Tidak pandai / Canggung", "歌が下手です。", "Tidak pandai bernyanyi.", "N5"],
  ["得意", "tokui", "とくい", "Jagoan / Bidang andalan", "数学が得意です。", "Jago matematika.", "N4"],
  ["苦手", "nigate", "にがて", "Lemah di / Kurang bisa", "運動が苦手です。", "Kurang pandai olahraga.", "N4"],
  ["綺麗", "kirei", "きれい", "Cantik / Bersih / Rapi", "富士山は綺麗です。", "Gunung Fuji cantik.", "N5"],
  ["静か", "shizuka", "しずか", "Tenang / Sunyi", "夜は静かです。", "Malam hari tenang.", "N5"],
  ["賑やか", "nigiyaka", "にぎやか", "Ramai / Meriah", "渋谷は賑やかです。", "Shibuya ramai.", "N5"],
  ["便利", "benri", "べんり", "Praktis / Mudah", "駅に近くて便利です。", "Praktis dekat stasiun.", "N5"],
  ["不便", "fuben", "ふべん", "Tidak praktis", "交通が不便です。", "Transportasi kurang praktis.", "N5"],
  ["元気", "genki", "げんき", "Sehat / Bersemangat", "お元気ですか？", "Apa kabar?", "N5"],
  ["親切", "shinsetsu", "しんせつ", "Ramah / Baik hati", "親切な人です。", "Orang yang ramah.", "N5"],
  ["有名", "yuumei", "ゆうめい", "Terkenal / Populer", "京都は有名です。", "Kyoto terkenal.", "N5"],
  ["大切", "taisetsu", "たいせつ", "Penting / Berharga", "命は大切です。", "Nyawa itu berharga.", "N5"],
  ["大事", "daiji", "だいじ", "Penting / Berarti", "お体を大事にしてください。", "Jaga dirimu baik-baik.", "N5"],
  ["安全", "anzen", "あんぜん", "Aman", "安全な町です。", "Kota yang aman.", "N4"],
  ["危険", "kiken", "きけん", "Bahaya", "ここは危険です。", "Di sini bahaya.", "N4"],
  ["簡単", "kantan", "かんたん", "Sederhana / Mudah", "簡単な問題です。", "Soal yang mudah.", "N5"],
  ["複雑", "fukuzatsu", "ふくざつ", "Rumit / Kompleks", "複雑な機械です。", "Mesin yang rumit.", "N4"],
  ["必要", "hitsuyou", "ひつよう", "Perlu / Diperlukan", "パスポートが必要です。", "Paspor diperlukan.", "N4"],
  ["暇", "hima", "ひま", "Luang", "暇なときに電話します。", "Telepon saat luang.", "N5"],
  ["真面目", "majime", "まじめ", "Rajin / Sungguh-sungguh", "真面目な学生です。", "Siswa yang tekun.", "N4"],
  ["不真面目", "fumajime", "ふまじめ", "Tidak sungguh-sungguh", "不真面目な態度はダメです。", "Sikap malas tidak boleh.", "N4"],
  ["自由", "jiyuu", "じゆう", "Bebas", "自由時間です。", "Waktu bebas.", "N4"],
  ["丁寧", "teinei", "ていねい", "Sopan santun / Teliti", "丁寧な言葉遣いです。", "Bahasa tutur kata sopan.", "N4"],
  ["失礼", "shitsurei", "しつれい", "Kurang ajar / Permisi", "失礼いたします。", "Permisi/Mohon maaf.", "N5"],
  ["無理", "muri", "むり", "Mustahil / Terlalu memaksakan", "無理をしないでください。", "Jangan memaksakan diri.", "N4"],
  ["適当", "tekitou", "てきとう", "Cocok / Asal-asalan", "適当な大きさです。", "Ukuran yang sesuai.", "N4"],
  ["特別", "tokubetsu", "とくべつ", "Istimewa / Khusus", "特別な日です。", "Hari istimewa.", "N4"],
  ["普通", "futsuu", "ふつう", "Biasa / Normal", "普通の電車です。", "Kereta api biasa.", "N5"],
  ["変", "hen", "へん", "Aneh / Ganjil", "変な音がします。", "Terdengar suara aneh.", "N4"],
  ["不思議", "fushigi", "ふしぎ", "Ajaib / Misterius", "不思議な体験をしました。", "Mengalami hal aneh.", "N4"],
  ["素晴らしい", "subarashii", "すばらしい", "Luar biasa hebat", "素晴らしい景色です。", "Pemandangan luar biasa.", "N4"],
  ["酷い", "hidoi", "ひどい", "Parah / Kejam / Jahat", "酷い雨です。", "Hujan sangat parah.", "N4"],
  ["可愛い", "kawaii", "かわいい", "Lucu / Imut", "可愛い赤ちゃんです。", "Bayi yang lucu.", "N5"],
  ["格好いい", "kakkoii", "かっこいい", "Keren / Tampan", "格好いい服です。", "Baju yang keren.", "N5"],
  ["汚い", "kitanai", "きたない", "Kotor", "部屋が汚いです。", "Kamarnya kotor.", "N5"],
  ["うるさい", "urusai", "うるさい", "Berisik / Bising", "外がうるさいです。", "Di luar berisik.", "N5"],
  ["眠い", "nemui", "ねむい", "Mengantuk", "とても眠いです。", "Sangat mengantuk.", "N5"],
  ["忙しい", "isogashii", "いそがしい", "Sibuk", "仕事で忙しいです。", "Sibuk dengan pekerjaan.", "N5"],
  ["正しい", "tadashii", "ただしい", "Benar / Tepat", "正しい答えです。", "Jawaban yang benar.", "N4"],
  ["可笑しい", "okashii", "おかしい", "Lucu / Aneh menggelikan", "可笑しい話です。", "Cerita lucu.", "N4"],
  ["浅い", "asai", "あさい", "Dangkal", "川が浅いです。", "Sungainya dangkal.", "N4"],
  ["深い", "fukai", "ふかい", "Dalam (kedalaman)", "海が深いです。", "Lautnya dalam.", "N4"],
  ["濃い", "koi", "こい", "Pekat / Kental / Tajam", "濃いお茶です。", "Teh yang kental.", "N4"],
  ["硬い", "katai", "かたい", "Keras (benda padat)", "このパンは硬いです。", "Roti ini keras.", "N4"],
  ["柔らかい", "yawarakai", "やわらかい", "Lembut / Empuk", "柔らかい肉です。", "Daging empuk.", "N4"],
  ["細かい", "komakai", "こまかい", "Halus / Receh koin", "細かいお金がありますか？", "Ada uang receh koin?", "N4"],
  ["粗い", "arai", "あらい", "Kasar", "網目が粗いです。", "Jaringannya kasar.", "N4"]
];

for (const a of adjData) {
  add(a[0], a[1], a[2], a[3], a[4], a[5], a[6], 'kata_sifat');
}

// 3. BENDA RUMAH, ELEKTRONIK & PAKAIAN ~140 items
const houseData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["机", "tsukue", "つくえ", "Meja tulis", "机の上で勉強します。", "Belajar di atas meja.", "N5"],
  ["椅子", "isu", "いす", "Kursi", "椅子に座ってください。", "Silakan duduk di kursi.", "N5"],
  ["本棚", "hondana", "ほんだな", "Rak buku", "本棚に並べます。", "Menata di rak buku.", "N5"],
  ["ベッド", "beddo", "beddo", "Tempat tidur / Ranjang", "ベッドで寝ます。", "Tidur di ranjang.", "N5"],
  ["布団", "futon", "ふとん", "Futon (kasur lipat Jepang)", "布団を敷きます。", "Menggelar kasur futon.", "N5"],
  ["枕", "makura", "まくら", "Bantal", "柔らかい枕です。", "Bantal yang empuk.", "N5"],
  ["毛布", "moufu", "もうふ", "Selimut wol", "毛布をかけます。", "Memakai selimut.", "N4"],
  ["ドア", "doa", "doa", "Pintu kamar/rumah", "ドアを開けます。", "Membuka pintu.", "N5"],
  ["窓", "mado", "まど", "Jendela", "窓を閉めます。", "Menutup jendela.", "N5"],
  ["鍵", "kagi", "かぎ", "Kunci gembok / Kunci pintu", "鍵をかけます。", "Mengunci pintu.", "N5"],
  ["テレビ", "terebi", "terebi", "Televisi", "テレビを見ます。", "Menonton TV.", "N5"],
  ["ラジオ", "rajio", "rajio", "Radio", "ラジオを聞きます。", "Mendengarkan radio.", "N5"],
  ["パソコン", "pasokon", "pasokon", "Komputer laptop / PC", "パソコンで仕事します。", "Bekerja dengan komputer.", "N5"],
  ["電話", "denwa", "でんわ", "Telepon", "電話に出ます。", "Mengangkat telepon.", "N5"],
  ["スマホ / 携帯", "sumaho / keitai", "すまほ", "Ponsel / Smartphone", "スマホを充電します。", "Mengisi daya baterai HP.", "N5"],
  ["カメラ", "kamera", "kamera", "Kamera foto", "カメラで撮ります。", "Memotret dengan kamera.", "N5"],
  ["エアコン", "eakon", "eakon", "AC pendingin ruangan", "エアコンをつけます。", "Menyalakan pendingin AC.", "N5"],
  ["冷蔵庫", "reizouko", "れいぞうこ", "Kulkas / Lemari es", "冷蔵庫に入れます。", "Memasukkan ke kulkas.", "N5"],
  ["洗濯機", "sentakuki", "せんたくき", "Mesin cuci", "洗濯機を回します。", "Menjalankan mesin cuci.", "N5"],
  ["電子レンジ", "denshirenji", "でんしれんじ", "Microwave penghangat", "レンジで温めます。", "Menghangatkan makanan di microwave.", "N4"],
  ["炊飯器", "suihanki", "すいはんき", "Rice cooker penanak nasi", "炊飯器でご飯を炊きます。", "Memasak nasi dengan penanak nasi.", "N4"],
  ["時計", "tokei", "とけい", "Jam dinding / Arloji", "時計を見ます。", "Melihat jam.", "N5"],
  ["鏡", "kagami", "かがみ", "Cermin", "鏡を見ます。", "Bercermin melihat muka.", "N4"],
  ["傘", "kasa", "かさ", "Payung", "傘をさします。", "Memakai payung.", "N5"],
  ["財布", "saifu", "さいふ", "Dompet uang", "財布を忘れました。", "Dompet tertinggal.", "N5"],
  ["鞄", "kaban", "かばん", "Tas ransel / Jinjing", "鞄を持ちます。", "Membawa tas.", "N5"],
  ["手帳", "techou", "てちょう", "Buku agenda saku", "手帳に書きます。", "Mencatat di buku saku agenda.", "N5"],
  ["辞書", "jisho", "じしょ", "Kamus bahasa", "辞書を引きます。", "Mencari di kamus.", "N5"],
  ["本", "hon", "ほん", "Buku", "本を読みます。", "Membaca buku.", "N5"],
  ["雑誌", "zasshi", "ざっし", "Majalah", "ファッション雑誌です。", "Majalah busana.", "N5"],
  ["新聞", "shinbun", "しんぶん", "Koran harian", "新聞を読みます。", "Membaca koran.", "N5"],
  ["ノート", "nooto", "nooto", "Buku catatan (notes)", "ノートにメモします。", "Mencatat di notebook.", "N5"],
  ["鉛筆", "enpitsu", "えんぴつ", "Pensil kayu", "鉛筆を削ります。", "Meraut pensil.", "N5"],
  ["ボールペン", "boorupen", "boorupen", "Pulpen bolpoin", "黒いボールペンです。", "Pulpen warna hitam.", "N5"],
  ["消しゴム", "keshigomu", "けしごむ", "Penghapus karet", "消しゴムで消します。", "Menghapus dengan karet.", "N5"],
  ["定規 / 物差し", "jougi", "じょうぎ", "Penggaris mistar", "定規で線を引きます。", "Menggaris lurus dengan penggaris.", "N4"],
  ["ハサミ", "hasami", "はさみ", "Gunting kertas", "ハサミで切ります。", "Memotong dengan gunting.", "N5"],
  ["紙", "kami", "かみ", "Kertas", "紙を折ります。", "Melipat kertas.", "N5"],
  ["封筒", "fuutou", "ふうとう", "Amplop surat", "封筒に入れます。", "Memasukkan ke dalam amplop.", "N5"],
  ["切手", "kitte", "きって", "Prangko pos", "切手を貼ります。", "Menempelkan prangko.", "N5"],
  ["手紙", "tegami", "てがみ", "Surat tulisan tangan", "手紙を書きます。", "Menulis surat.", "N5"],
  ["服", "fuku", "ふく", "Pakaian / Baju", "新しい服を着ます。", "Mengenakan pakaian baru.", "N5"],
  ["シャツ", "shatsu", "shatsu", "Kemeja shirt", "白いシャツです。", "Kemeja putih.", "N5"],
  ["ズボン / パンツ", "zubon / pantsu", "ずぼん", "Celana panjang", "ズボンを履きます。", "Memakai celana panjang.", "N5"],
  ["スカート", "sukaato", "sukaato", "Rok wanita", "可愛いスカートです。", "Rok yang manis.", "N5"],
  ["靴", "kutsu", "くつ", "Sepatu", "靴を履きます。", "Mengenakan sepatu.", "N5"],
  ["靴下", "kutsushita", "くつした", "Kaus kaki", "靴下を脱ぎます。", "Melepas kaus kaki.", "N5"],
  ["帽子", "boushi", "ぼうし", "Topi kepala", "帽子をかぶります。", "Memakai topi.", "N5"],
  ["眼鏡", "megane", "めがね", "Kacamata", "眼鏡をかけます。", "Memakai kacamata.", "N5"],
  ["ネクタイ", "nekutai", "nekutai", "Dasi leher", "ネクタイを締めます。", "Mengenakan dasi.", "N5"],
  ["コート", "kooto", "kooto", "Mantel tebal / Coat", "暖かいコートです。", "Mantel tebal hangat.", "N5"],
  ["セーター", "seetaa", "seetaa", "Baju rajut sweater", "セーターを着ます。", "Memakai baju sweater.", "N5"],
  ["ポケット", "poketto", "poketto", "Saku kantong baju", "ポケットに入れます。", "Memasukkan ke saku.", "N5"],
  ["ボタン", "botan", "botan", "Kancing baju", "ボタンを留めます。", "Mengancingkan baju.", "N5"],
  ["タオル", "taoru", "taoru", "Handuk mandi", "タオルで拭きます。", "Mengusap badan dengan handuk.", "N5"],
  ["石鹸", "sekken", "せっけん", "Sabun mandi / Sabun cuci", "石鹸で手を洗います。", "Mencuci tangan pakai sabun.", "N5"],
  ["歯ブラシ", "haburashi", "はぶらし", "Sikat gigi", "新しい歯ブラシです。", "Sikat gigi baru.", "N5"],
  ["シャンプー", "shanpuu", "shanpuu", "Sampo rambut", "髪をシャンプーで洗います。", "Mencuci rambut dengan sampo.", "N5"],
  ["ゴミ箱", "gomibako", "ごみばこ", "Tempat sampah", "ゴミ箱に捨てます。", "Membuang ke tempat sampah.", "N5"]
];

for (const h of houseData) {
  add(h[0], h[1], h[2], h[3], h[4], h[5], h[6], 'benda_rumah');
}

// 4. MAKANAN & MINUMAN ~120 items
const foodData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["ご飯", "gohan", "ごはん", "Nasi / Makanan pokok", "ご飯を食べます。", "Saya makan nasi.", "N5"],
  ["パン", "pan", "pan", "Roti", "朝はパンを食べます。", "Pagi hari makan roti.", "N5"],
  ["肉", "niku", "にく", "Daging", "肉料理が好きです。", "Suka masakan olahan daging.", "N5"],
  ["牛肉", "gyuuniku", "ぎゅうにく", "Daging sapi", "牛肉を買いました。", "Membeli daging sapi.", "N5"],
  ["豚肉", "butaniku", "ぶたにく", "Daging babi", "豚肉の生姜焼きです。", "Masakan jahe daging babi.", "N5"],
  ["鶏肉", "toriniku", "とりにく", "Daging ayam", "鶏肉を焼きます。", "Memanggang ayam.", "N5"],
  ["魚", "sakana", "さかな", "Ikan", "新鮮な魚です。", "Ikan segar.", "N5"],
  ["卵", "tamago", "たまご", "Telur ayam", "卵焼きを作ります。", "Membuat telur dadar gulung.", "N5"],
  ["野菜", "yasai", "やさい", "Sayuran", "新鮮な野菜です。", "Sayur-mayur segar.", "N5"],
  ["果物", "kudamono", "くだもの", "Buah-buahan", "甘い果物です。", "Buah yang manis.", "N5"],
  ["リンゴ", "ringo", "りんご", "Apel", "赤いリンゴです。", "Apel merah merona.", "N5"],
  ["ミカン", "mikan", "みかん", "Jeruk mandarin Jepang", "ミカンを食べます。", "Makan jeruk mikan.", "N5"],
  ["バナナ", "banana", "banana", "Pisang", "朝バナナを食べます。", "Makan pisang di pagi hari.", "N5"],
  ["水", "mizu", "みず", "Air putih / Air dingin", "お水をください。", "Tolong berikan air.", "N5"],
  ["お茶", "ocha", "おちゃ", "Teh hijau Jepang", "温かいお茶です。", "Teh hijau hangat.", "N5"],
  ["紅茶", "koucha", "こうちゃ", "Teh hitam barat", "レモン紅茶です。", "Teh lemon hangat.", "N5"],
  ["コーヒー", "koohii", "koohii", "Kopi", "ブラックコーヒーです。", "Kopi hitam tanpa gula.", "N5"],
  ["牛乳", "gyuunyuu", "ぎゅうにゅう", "Susu sapi murni", "毎朝牛乳を飲みます。", "Minum susu sapi setiap pagi.", "N5"],
  ["ジュース", "juusu", "juusu", "Jus sari buah", "オレンジジュースです。", "Jus jeruk segar.", "N5"],
  ["ビール", "biiru", "biiru", "Bir", "冷たいビールです。", "Bir dingin segar.", "N5"],
  ["お酒", "osake", "おさけ", "Sake / Alkohol", "日本酒を飲みます。", "Minum sake Jepang.", "N5"],
  ["寿司", "sushi", "すし", "Sushi beras kepal", "寿司を食べに行きます。", "Pergi makan sushi.", "N5"],
  ["刺身", "sashimi", "さしみ", "Sashimi irisan ikan mentah", "マグロの刺身です。", "Sashimi ikan tuna maguro.", "N5"],
  ["天ぷら", "tenpura", "てんぷら", "Tempura gorengan renyah", "エビの天ぷらです。", "Tempura udang renyah.", "N5"],
  ["ラーメン", "raamen", "raamen", "Mie kuah ramen", "熱いラーメンを食べます。", "Makan ramen panas.", "N5"],
  ["うどん", "udon", "うどん", "Mie tebal terigu udon", "きつねうどんです。", "Kitsune udon gurih.", "N5"],
  ["そば", "soba", "そば", "Mie gandum hitam soba", "ざるそばを食べます。", "Makan mie soba dingin zaru.", "N5"],
  ["カレーライス", "kareeraisu", "kareeraisu", "Nasi kari Jepang", "辛いカレーライスです。", "Nasi kari Jepang pedas.", "N5"],
  ["お弁当", "obentou", "おべんとう", "Kotak bekal makan bento", "お弁当を作りました。", "Membuat bekal makan bento.", "N5"],
  ["おにぎり", "onigiri", "おにぎり", "Nasi kepal rumput laut", "鮭のおにぎりです。", "Onigiri isi salmon.", "N5"],
  ["砂糖", "satou", "さとう", "Gula pasir", "砂糖を入れます。", "Menambahkan gula.", "N5"],
  ["塩", "shio", "しお", "Garam dapur", "塩を少々振ります。", "Taburkan sedikit garam.", "N5"],
  ["醤油", "shouyu", "しょうゆ", "Kecap asin Jepang shoyu", "醤油につけます。", "Mencelupkan ke kecap shoyu.", "N5"],
  ["味噌", "miso", "みそ", "Pasta kedelai fermentasi miso", "味噌汁を作ります。", "Membuat sup miso hangat.", "N5"],
  ["酢", "su", "す", "Cuka makan asam", "お酢をかけます。", "Meneteskan cuka.", "N4"],
  ["油", "abura", "あぶら", "Minyak goreng", "油で揚げます。", "Menggoreng dengan minyak.", "N4"],
  ["コショウ", "koshou", "koshou", "Lada bubuk / Merica", "コショウを振ります。", "Menaburkan lada hitam.", "N4"],
  ["スープ", "suupu", "suupu", "Sup kaldu kuah", "温かいスープです。", "Sup hangat lezat.", "N5"],
  ["サラダ", "sarada", "sarada", "Salad sayur", "野菜サラダを食べます。", "Makan salad sayuran.", "N5"],
  ["お菓子", "okashi", "おかし", "Camilan kue / Makanan ringan", "お菓子を食べます。", "Makan camilan snack.", "N5"],
  ["ケーキ", "keeki", "keeki", "Kue tart bolu", "誕生日ケーキです。", "Kue ulang tahun.", "N5"],
  ["チョコレート", "chokoreeto", "chokoreeto", "Cokelat manis", "ミルクチョコレートです。", "Cokelat susu lezat.", "N5"],
  ["アイスクリーム", "aisukuriimu", "aisukuriimu", "Es krim manis dingin", "バニラアイスです。", "Es krim rasa vanila.", "N5"],
  ["朝食", "choushoku", "ちょうしょく", "Makan pagi / Sarapan", "ホテルで朝食をとります。", "Sarapan di hotel.", "N4"],
  ["昼食", "chuushoku", "ちゅうしょく", "Makan siang", "昼食の時間です。", "Waktunya makan siang.", "N4"],
  ["夕食", "yuushoku", "ゆうしょく", "Makan malam", "夕食を一緒に食べます。", "Makan malam bersama.", "N4"],
  ["おやつ", "oyatsu", "おやつ", "Camilan sore jam 3", "3時のおやつです。", "Camilan sore jam 3.", "N4"]
];

for (const f of foodData) {
  add(f[0], f[1], f[2], f[3], f[4], f[5], f[6], 'makanan');
}

// 5. KELUARGA & HUBUNGAN ORANG ~60 items
const famData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["家族", "kazoku", "かぞく", "Keluarga", "家族と暮らしています。", "Tinggal bersama keluarga.", "N5"],
  ["両親", "ryoushin", "りょうしん", "Orang tua", "両親を尊敬します。", "Menghormati orang tua.", "N5"],
  ["父", "chichi", "ちち", "Ayah (sendiri)", "父は会社員です。", "Ayah saya pegawai kantor.", "N5"],
  ["お父さん", "otousan", "おとうさん", "Ayah (orang lain)", "お父さんはお元気ですか？", "Apakah ayah Anda sehat?", "N5"],
  ["母", "haha", "はは", "Ibu (sendiri)", "母の手料理です。", "Masakan buatan ibu saya.", "N5"],
  ["お母さん", "okaasan", "おかあさん", "Ibu (orang lain)", "お母さんに花を贈ります。", "Memberikan bunga ke ibu.", "N5"],
  ["兄", "ani", "あに", "Kakak laki-laki (sendiri)", "兄は大学生です。", "Kakak laki-laki saya mahasiswa.", "N5"],
  ["お兄さん", "oniisan", "おにいさん", "Kakak laki-laki (orang lain)", "お兄さんは優しいですね。", "Kakak laki-laki Anda ramah ya.", "N5"],
  ["姉", "ane", "あね", "Kakak perempuan (sendiri)", "姉は看護師です。", "Kakak perempuan saya perawat.", "N5"],
  ["お姉さん", "oneesan", "おねえさん", "Kakak perempuan (orang lain)", "美人なお姉さんです。", "Kakak perempuan yang cantik.", "N5"],
  ["弟", "otouto", "おとうと", "Adik laki-laki", "弟とサッカーをします。", "Main sepak bola dengan adik.", "N5"],
  ["妹", "imouto", "いもうと", "Adik perempuan", "妹は高校生です。", "Adik perempuan saya murid SMA.", "N5"],
  ["兄弟", "kyoudai", "きょうだい", "Saudara kandung", "兄弟が3人います。", "Punya 3 saudara kandung.", "N5"],
  ["祖父", "sofu", "そふ", "Kakek (sendiri)", "祖父は80歳です。", "Kakek saya berumur 80 tahun.", "N5"],
  ["おじいさん", "ojiisan", "おじいさん", "Kakek (orang lain)", "元気なおじいさんです。", "Kakek yang bersemangat.", "N5"],
  ["祖母", "sobo", "そぼ", "Nenek (sendiri)", "祖母の家へ行きます。", "Pergi ke rumah nenek.", "N5"],
  ["おばあさん", "obaasan", "おばあさん", "Nenek (orang lain)", "優しいおばあさんです。", "Nenek yang sangat ramah.", "N5"],
  ["夫", "otto", "おっと", "Suami (sendiri)", "夫と買い物に行きます。", "Belanja bersama suami.", "N5"],
  ["妻", "tsuma", "つま", "Istri (sendiri)", "妻の手料理です。", "Masakan buatan istri.", "N5"],
  ["子供", "kodomo", "こども", "Anak-anak", "子供が公園で遊びます。", "Anak-anak bermain di taman.", "N5"],
  ["友達", "tomodachi", "ともだち", "Teman / Sahabat", "友達とおしゃべりします。", "Mengobrol dengan sahabat.", "N5"],
  ["人", "hito", "ひと", "Orang", "親切な人です。", "Orang yang ramah.", "N5"],
  ["方", "kata", "かた", "Beliau / Orang (sopan)", "あの方は先生です。", "Beliau adalah seorang guru.", "N5"],
  ["男の子", "otokonoko", "おとこのこ", "Anak laki-laki", "元気な男の子です。", "Anak laki-laki yang lincah.", "N5"],
  ["女の子", "onnanoko", "おんなのこ", "Anak perempuan", "可愛い女の子です。", "Anak perempuan yang lucu.", "N5"],
  ["男性", "dansei", "だんせい", "Laki-laki / Pria", "男性用の服です。", "Pakaian untuk pria.", "N4"],
  ["女性", "josei", "じょせい", "Perempuan / Wanita", "女性専用車両です。", "Gerbong khusus wanita.", "N4"],
  ["大人", "otona", "おとな", "Orang dewasa", "大人の料金です。", "Tarif untuk orang dewasa.", "N5"],
  ["赤ちゃん", "akachan", "あかちゃん", "Bayi mungil", "赤ちゃんが眠っています。", "Bayinya sedang tidur lelap.", "N5"],
  ["親戚", "shinseki", "しんせき", "Sanak kerabat / Saudara jauh", "お正月に親戚が集まります。", "Kerabat berkumpul saat tahun baru.", "N4"]
];

for (const fam of famData) {
  add(fam[0], fam[1], fam[2], fam[3], fam[4], fam[5], fam[6], 'keluarga');
}

// 6. TUBUH & KESEHATAN ~65 items
const bodyData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["体", "karada", "からだ", "Tubuh / Badan", "体を鍛えます。", "Melatih kebugaran tubuh.", "N5"],
  ["頭", "atama", "あたま", "Kepala", "頭が痛いです。", "Kepala saya terasa pusing.", "N5"],
  ["髪", "kami", "かみ", "Rambut", "髪を切りました。", "Saya telah memotong rambut.", "N5"],
  ["顔", "kao", "かお", "Wajah / Muka", "笑顔の顔です。", "Wajah tersenyum.", "N5"],
  ["目", "me", "め", "Mata", "目が疲れています。", "Mata terasa lelah.", "N5"],
  ["耳", "mimi", "みみ", "Telinga", "耳を澄ませます。", "Mendengarkan dengan teliti.", "N5"],
  ["鼻", "hana", "はな", "Hidung", "鼻が高いです。", "Hidungnya mancung.", "N5"],
  ["口", "kuchi", "くち", "Mulut", "口を開けます。", "Membuka mulut.", "N5"],
  ["歯", "ha", "は", "Gigi", "歯を磨きます。", "Menggosok gigi.", "N5"],
  ["首", "kubi", "くび", "Leher", "首が痛いです。", "Leher terasa kaku pegal.", "N5"],
  ["喉", "nodo", "のど", "Tenggorokan", "喉が渇きました。", "Tenggorokan merasa haus.", "N5"],
  ["手", "te", "て", "Tangan", "手を洗います。", "Mencuci tangan.", "N5"],
  ["指", "yubi", "ゆび", "Jari tangan", "指を怪我しました。", "Jari saya terluka.", "N5"],
  ["腕", "ude", "うで", "Lengan tangan", "腕を組みます。", "Bersedekap lengan tangan.", "N4"],
  ["肩", "kata", "かた", "Pundak / Bahu", "肩が凝りました。", "Pundak terasa kaku pegal.", "N4"],
  ["胸", "mune", "むね", "Dada", "胸が痛みます。", "Dada terasa nyeri.", "N4"],
  ["背中", "senaka", "せなか", "Punggung belakang", "背中が痛いです。", "Punggung terasa sakit.", "N4"],
  ["腰", "koshi", "こし", "Pinggang", "腰に手を当てます。", "Menaruh tangan di pinggang.", "N4"],
  ["お腹", "onaka", "おなか", "Perut", "お腹が空きました。", "Perut saya merasa lapar.", "N5"],
  ["足", "ashi", "あし", "Kaki", "足が長いです。", "Kakinya jenjang panjang.", "N5"],
  ["膝", "hiza", "ひざ", "Lutut kaki", "膝を擦りむきました。", "Lutut tergores lecet.", "N4"],
  ["病気", "byouki", "びょうき", "Penyakit / Sakit", "病気で寝ています。", "Sakit terbaring di ranjang.", "N5"],
  ["風邪", "kaze", "かぜ", "Flu / Masuk angin", "風邪をひきました。", "Saya terkena penyakit flu.", "N5"],
  ["熱", "netsu", "ねつ", "Demam suhu badan", "熱が38度あります。", "Demam bersuhu 38 derajat.", "N5"],
  ["咳", "seki", "せき", "Batuk", "咳が止まりません。", "Batuknya tidak kunjung reda.", "N5"],
  ["薬", "kusuri", "くすり", "Obat-obatan", "薬を飲みます。", "Meminum obat.", "N5"],
  ["病院", "byouin", "びょういん", "Rumah sakit", "病院で診てもらいます。", "Diperiksa di rumah sakit.", "N5"],
  ["医者", "isha", "いしゃ", "Dokter medis", "医者になりたいです。", "Bercita-cita menjadi dokter.", "N5"],
  ["看護師", "kangoshi", "かんごし", "Perawat rumah sakit", "優しい看護師さんです。", "Perawat yang ramah.", "N4"],
  ["怪我", "kega", "けが", "Luka / Cedera", "怪我に気をつけてください。", "Hati-hati jangan sampai terluka.", "N5"]
];

for (const b of bodyData) {
  add(b[0], b[1], b[2], b[3], b[4], b[5], b[6], 'tubuh_kesehatan');
}

// 7. WAKTU, HARI, KALENDER & ANGKA ~80 items
const timeData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["今", "ima", "いま", "Sekarang saat ini", "今、何時ですか？", "Sekarang jam berapa?", "N5"],
  ["今日", "kyou", "きょう", "Hari ini", "今日は月曜日です。", "Hari ini hari Senin.", "N5"],
  ["明日", "ashita", "あした", "Besok hari", "明日テストがあります。", "Besok ada ujian.", "N5"],
  ["明後日", "asatte", "あさって", "Lusa hari", "明後日会いましょう。", "Ayo bertemu lusa.", "N5"],
  ["昨日", "kinou", "きのう", "Kemarin", "昨日は雨でした。", "Kemarin turun hujan.", "N5"],
  ["一昨日", "ototoi", "おととい", "Kemarin lusa", "一昨日着きました。", "Tiba kemarin lusa.", "N5"],
  ["朝", "asa", "あさ", "Pagi hari", "朝6時に起きます。", "Bangun jam 6 pagi.", "N5"],
  ["昼", "hiru", "ひる", "Siang hari", "昼ご飯を食べます。", "Makan siang.", "N5"],
  ["夕方", "yuugata", "ゆうがた", "Sore menjelang senja", "夕方に散歩します。", "Jalan santai di sore hari.", "N5"],
  ["夜", "yoru", "よる", "Malam hari", "夜11時に寝ます。", "Tidur jam 11 malam.", "N5"],
  ["毎日", "mainichi", "まいにち", "Setiap hari", "毎日日本語を勉強します。", "Belajar bahasa Jepang tiap hari.", "N5"],
  ["毎朝", "maiasa", "まいあさ", "Setiap pagi", "毎朝走ります。", "Berlari setiap pagi.", "N5"],
  ["毎晩", "maiban", "まいばん", "Setiap malam", "毎晩日記を書きます。", "Menulis buku harian tiap malam.", "N5"],
  ["今週", "konshuu", "こんしゅう", "Minggu ini", "今週は忙しいです。", "Minggu ini sibuk.", "N5"],
  ["来週", "raishuu", "らいしゅう", "Minggu depan", "来週旅行に行きます。", "Pergi berlibur minggu depan.", "N5"],
  ["先週", "senshuu", "せんしゅう", "Minggu lalu", "先週映画を見ました。", "Nonton film minggu lalu.", "N5"],
  ["毎週", "maishuu", "まいしゅう", "Setiap minggu", "毎週日曜日に泳ぎます。", "Berenang setiap hari Minggu.", "N5"],
  ["今月", "kongetsu", "こんげつ", "Bulan ini", "今月誕生日です。", "Bulan ini ulang tahun saya.", "N5"],
  ["来月", "raigetsu", "らいげつ", "Bulan depan", "来月日本へ行きます。", "Bulan depan pergi ke Jepang.", "N5"],
  ["先月", "sengetsu", "せんげつ", "Bulan lalu", "先月車を買いました。", "Bulan lalu membeli mobil.", "N5"],
  ["毎月", "maitsuki", "まいつき", "Setiap bulan", "毎月本を5冊読みます。", "Membaca 5 buku tiap bulan.", "N5"],
  ["今年", "kotoshi", "ことし", "Tahun ini", "今年20歳になります。", "Tahun ini berusia 20 tahun.", "N5"],
  ["来年", "rainen", "らいねん", "Tahun depan", "来年卒業します。", "Tahun depan lulus sekolah.", "N5"],
  ["去年", "kyonen", "きょねん", "Tahun lalu", "去年日本へ来ました。", "Datang ke Jepang tahun lalu.", "N5"],
  ["毎年", "maitoshi", "まいとし", "Setiap tahun", "毎年旅行します。", "Berlibur setiap tahun.", "N5"],
  ["月曜日", "getsuyoubi", "げつようび", "Hari Senin", "月曜日に会いましょう。", "Ayo bertemu hari Senin.", "N5"],
  ["火曜日", "kayoubi", "かようび", "Hari Selasa", "火曜日は休みです。", "Hari Selasa libur.", "N5"],
  ["水曜日", "suiyoubi", "すいようび", "Hari Rabu", "水曜日に泳ぎます。", "Berenang di hari Rabu.", "N5"],
  ["木曜日", "mokuyoubi", "もくようび", "Hari Kamis", "木曜日に会議があります。", "Ada rapat di hari Kamis.", "N5"],
  ["金曜日", "kinyoubi", "きんようび", "Hari Jumat", "金曜日の夜は楽しいです。", "Malam Jumat menyenangkan.", "N5"],
  ["土曜日", "doyoubi", "どようび", "Hari Sabtu", "土曜日に買い物します。", "Belanja di hari Sabtu.", "N5"],
  ["日曜日", "nichiyoubi", "にちようび", "Hari Minggu", "日曜日は休みます。", "Hari Minggu istirahat santai.", "N5"],
  ["春", "haru", "はる", "Musim semi (Spring)", "春は桜が咲きます。", "Di musim semi bunga sakura mekar.", "N5"],
  ["夏", "natsu", "なつ", "Musim panas (Summer)", "夏は海へ行きます。", "Di musim panas pergi ke pantai.", "N5"],
  ["秋", "aki", "あき", "Musim gugur (Autumn)", "秋は紅葉が綺麗です。", "Di musim gugur dedaunan merah indah.", "N5"],
  ["冬", "fuyu", "ふゆ", "Musim dingin (Winter)", "冬は雪が降ります。", "Di musim dingin salju turun.", "N5"],
  ["時間", "jikan", "じかん", "Waktu / Jam", "時間がありません。", "Tidak ada waktu luang.", "N5"],
  ["午前", "gozen", "ごぜん", "Pagi (AM 00:00 - 12:00)", "午前9時に始まります。", "Mulai pada jam 9 pagi.", "N5"],
  ["午後", "gogo", "ごご", "Sore / Malam (PM 12:00 - 24:00)", "午後3時にお茶をします。", "Minum teh jam 3 sore.", "N5"]
];

for (const t of timeData) {
  add(t[0], t[1], t[2], t[3], t[4], t[5], t[6], 'angka_waktu');
}

// 8. TEMPAT, KOTA & TRANSPORTASI ~120 items
const placeData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["家 / うち", "ie / uchi", "いえ", "Rumah tempat tinggal", "家に帰ります。", "Saya pulang ke rumah.", "N5"],
  ["部屋", "heya", "へや", "Kamar tidur / Ruangan", "明るい部屋です。", "Kamar yang terang.", "N5"],
  ["台所", "daidokoro", "だいどころ", "Dapur memasak", "台所で料理します。", "Memasak di dapur.", "N5"],
  ["お風呂", "ofuro", "おふろ", "Bak mandi / Kamar mandi", "お風呂に入ります。", "Berendam di bak air hangat.", "N5"],
  ["トイレ", "toire", "toire", "Toilet / Kamar kecil", "トイレはどこですか？", "Di mana toiletnya?", "N5"],
  ["玄関", "genkan", "げんかん", "Pintu masuk depan rumah", "玄関で靴を脱ぎます。", "Melepas sepatu di genkan.", "N5"],
  ["庭", "niwa", "にわ", "Halaman taman rumah", "庭に花を植えます。", "Menanam bunga di halaman.", "N5"],
  ["学校", "gakkou", "がっこう", "Sekolah", "学校へ通います。", "Pergi ke sekolah.", "N5"],
  ["大学", "daigaku", "だいがく", "Universitas", "東京の大学です。", "Universitas di Tokyo.", "N5"],
  ["教室", "kyoushitsu", "きょうしつ", "Ruang kelas belajar", "教室に入ります。", "Masuk ke ruang kelas.", "N5"],
  ["図書館", "toshokan", "としょかん", "Perpustakaan umum", "図書館で本を借ります。", "Meminjam buku di perpustakaan.", "N5"],
  ["駅", "eki", "えき", "Stasiun kereta api", "駅の前で待ちます。", "Menunggu di depan stasiun.", "N5"],
  ["空港", "kuukou", "くうこう", "Bandar udara / Bandara", "成田空港に着きました。", "Tiba di bandara Narita.", "N5"],
  ["バス停", "basutei", "ばすてい", "Halte bus halte pemberhentian", "バス停で待ちます。", "Menunggu di halte bus.", "N5"],
  ["店", "mise", "みせ", "Toko pedagang", "いい店を見つけました。", "Menemukan toko yang bagus.", "N5"],
  ["スーパー", "suupaa", "suupaa", "Supermarket swalayan", "スーパーで買い物をします。", "Belanja di supermarket.", "N5"],
  ["コンビニ", "konbini", "konbini", "Minimarket 24 jam", "コンビニでお弁当を買います。", "Beli bento di minimarket konbini.", "N5"],
  ["レストラン", "resutoran", "resutoran", "Restoran makan", "美味しいレストランです。", "Restoran yang lezat.", "N5"],
  ["喫茶店", "kissaten", "きっさてん", "Kedai kafe kopi", "喫茶店で休みます。", "Istirahat di kafe kedai kopi.", "N5"],
  ["銀行", "ginkou", "ぎんこう", "Bank keuangan", "銀行でお金を下ろします。", "Mengambil uang di bank.", "N5"],
  ["郵便局", "yuubinkyoku", "ゆうびんきょく", "Kantor pos pengiriman", "郵便局で切手を買います。", "Beli prangko di kantor pos.", "N5"],
  ["交番", "kouban", "こうばん", "Pos polisi lingkungan", "交番で道を聞きます。", "Bertanya arah di pos polisi.", "N5"],
  ["公園", "kouen", "こうえん", "Taman rekreasi umum", "公園で散歩します。", "Jalan santai di taman.", "N5"],
  ["病院", "byouin", "びょういん", "Rumah sakit pengobatan", "病院へ行きます。", "Pergi ke rumah sakit.", "N5"],
  ["薬局", "yakkyoku", "やっきょく", "Apotek obat", "薬局で薬を買います。", "Beli obat di apotek.", "N4"],
  ["映画館", "eigakan", "えいがかん", "Bioskop gedung bioskop", "映画館で映画を見ます。", "Nonton film di bioskop.", "N5"],
  ["美術館", "bijutsukan", "びじゅつかん", "Museum seni rupa", "美術館に行きました。", "Pergi ke museum seni rupa.", "N5"],
  ["博物館", "hakubutsukan", "はくぶつかん", "Museum sejarah artefak", "歴史の博物館です。", "Museum sejarah masa lampau.", "N4"],
  ["神社", "jinja", "じんじゃ", "Kuil Shinto Jepang", "初詣に神社へ行きます。", "Kunjungan tahun baru ke kuil Shinto.", "N4"],
  ["お寺", "otera", "おてら", "Kuil Buddha Jepang", "古いお寺を拝観します。", "Mengunjungi kuil Buddha kuno.", "N5"],
  ["ホテル", "hoteru", "hoteru", "Hotel penginapan", "ホテルに泊まります。", "Menginap di hotel.", "N5"],
  ["町 / 街", "machi", "まち", "Kota / Daerah kota", "賑やかな町です。", "Kota yang sangat ramai.", "N5"],
  ["国", "kuni", "くに", "Negara tanah air", "お国はどちらですか？", "Dari negara manakah Anda?", "N5"],
  ["電車", "densha", "でんしゃ", "Kereta rel listrik komuter", "電車に乗ります。", "Naik kereta listrik.", "N5"],
  ["地下鉄", "chikatetsu", "ちかてつ", "Kereta bawah tanah MRT", "地下鉄で移動します。", "Berpindah naik kereta bawah tanah.", "N5"],
  ["新幹線", "shinkansen", "しんかんせん", "Kereta cepat Shinkansen", "新幹線は速いです。", "Shinkansen melaju sangat cepat.", "N5"],
  ["バス", "basu", "basu", "Bus angkutan umum", "市内バスに乗ります。", "Naik bus kota.", "N5"],
  ["タクシー", "takushii", "takushii", "Taksi kendaraan sewa", "タクシーを呼びます。", "Memanggil taksi.", "N5"],
  ["車", "kuruma", "くるま", "Mobil pribadi", "車を運転します。", "Mengendarai mobil.", "N5"],
  ["自転車", "jitensha", "じてんしゃ", "Sepeda kayuh", "自転車で行きます。", "Pergi naik sepeda.", "N5"],
  ["オートバイ", "ootobai", "ootobai", "Sepeda motor", "バイクに乗ります。", "Mengendarai sepeda motor.", "N4"],
  ["飛行機", "hikouki", "ひこうき", "Pesawat terbang udara", "飛行機に乗ります。", "Naik pesawat terbang.", "N5"],
  ["船", "fune", "ふね", "Kapal laut penyeberangan", "船で渡ります。", "Menyeberang naik kapal.", "N5"],
  ["右", "migi", "みぎ", "Kanan arah", "右に曲がります。", "Belok ke kanan.", "N5"],
  ["左", "hidari", "ひだり", "Kiri arah", "左側にあります。", "Terletak di sisi sebelah kiri.", "N5"],
  ["前", "mae", "まえ", "Depan arah / Sebelum", "駅の前です。", "Di depan stasiun.", "N5"],
  ["後ろ", "ushiro", "うしろ", "Belakang arah", "後ろを見てください。", "Tolong lihat ke belakang.", "N5"],
  ["上", "ue", "うえ", "Atas arah", "机の上です。", "Di atas meja.", "N5"],
  ["下", "shita", "した", "Bawah arah", "木の下で休みます。", "Istirahat di bawah pohon.", "N5"],
  ["中", "naka", "なか", "Dalam sisi", "箱の中に入れます。", "Memasukkan ke dalam kotak.", "N5"],
  ["外", "soto", "そと", "Luar sisi", "外で遊びます。", "Bermain di luar rumah.", "N5"],
  ["隣", "tonari", "となり", "Sebelah persis", "隣の部屋です。", "Kamar sebelah.", "N5"],
  ["間", "aida", "あいだ", "Antara celah", "本とペンの間です。", "Di antara buku dan pulpen.", "N5"],
  ["近く", "chikaku", "ちかく", "Dekat / Sekitaran", "駅の近くに住んでいます。", "Tinggal di dekat stasiun.", "N5"],
  ["向かい", "mukai", "むかい", "Seberang hadapan", "道の向かい側です。", "Di seberang jalan raya.", "N4"]
];

for (const p of placeData) {
  add(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[1].includes('sha') || p[1].includes('basu') || p[1].includes('kuruma') || p[1].includes('fune') || p[1].includes('hikouki') ? 'transportasi' : 'tempat');
}

// 9. ALAM, CUACA & HEWAN ~80 items
const natureData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["天気", "tenki", "てんき", "Cuaca hari", "明日の天気予報です。", "Prakiraan cuaca esok hari.", "N5"],
  ["雨", "ame", "あめ", "Hujan", "雨が降っています。", "Hujan sedang turun deras.", "N5"],
  ["雪", "yuki", "ゆき", "Salju putih", "雪だるまを作ります。", "Membuat boneka salju.", "N5"],
  ["風", "kaze", "かぜ", "Angin hembusan", "爽やかな風が吹きます。", "Angin segar bertiup.", "N5"],
  ["空", "sora", "そら", "Langit angkasa", "青空が綺麗です。", "Langit biru sangat indah.", "N5"],
  ["雲", "kumo", "くも", "Awan mendung", "白い雲が浮かんでいます。", "Awan putih melayang di langit.", "N5"],
  ["太陽", "taiyou", "たいよう", "Matahari surya", "太陽が昇ります。", "Matahari terbit di ufuk timur.", "N5"],
  ["月", "tsuki", "つき", "Bulan purnama / Rembulan", "今夜の月は満月です。", "Bulan malam ini purnama.", "N5"],
  ["星", "hoshi", "ほし", "Bintang gemintang", "満天の星空です。", "Langit penuh taburan bintang.", "N5"],
  ["山", "yama", "やま", "Gunung", "富士山に登ります。", "Mendaki gunung Fuji.", "N5"],
  ["川", "kawa", "かわ", "Sungai aliran air", "川で魚が泳いでいます。", "Ikan berenang di sungai.", "N5"],
  ["海", "umi", "うみ", "Laut samudra / Pantai", "海で泳ぎます。", "Berenang di laut pantai.", "N5"],
  ["島", "shima", "しま", "Pulau daratan", "美しい島を訪れます。", "Berkunjung ke pulau yang indah.", "N4"],
  ["森", "mori", "もり", "Hutan rimbun lebat", "森の中を歩きます。", "Berjalan di dalam hutan rimbun.", "N4"],
  ["木", "ki", "き", "Pohon kayu", "大きな木があります。", "Ada pohon rindang yang besar.", "N5"],
  ["花", "hana", "はな", "Bunga mekar", "桜の花が咲きました。", "Bunga sakura mekar indah.", "N5"],
  ["草", "kusa", "くさ", "Rumput ilalang", "芝生の上に座ります。", "Duduk di atas hamparan rumput.", "N4"],
  ["石", "ishi", "いし", "Batu kerikil / Batuan", "小石を拾います。", "Memungut batu kerikil.", "N4"],
  ["犬", "inu", "いぬ", "Anjing peliharaan", "犬の散歩をします。", "Mengajak jalan anjing peliharaan.", "N5"],
  ["猫", "neko", "ねこ", "Kucing peliharaan", "猫が喉を鳴らしています。", "Kucing mendengkur manja.", "N5"],
  ["鳥", "tori", "とり", "Burung unggas", "小鳥が歌っています。", "Burung kecil bernyanyi merdu.", "N5"],
  ["魚", "sakana", "さかな", "Ikan hidup di air", "金魚を飼っています。", "Memelihara ikan mas koki.", "N5"],
  ["馬", "uma", "うま", "Kuda tunggangan", "馬に乗るのが楽しいです。", "Menunggang kuda menyenangkan.", "N4"],
  ["牛", "ushi", "うし", "Sapi perah / ternak", "牧場に牛がいます。", "Ada sapi di peternakan.", "N4"],
  ["豚", "buta", "ぶた", "Babi ternak", "豚が寝ています。", "Babi sedang tertidur.", "N4"],
  ["羊", "hitsuji", "ひつじ", "Domba biri-biri", "羊毛でセーターを作ります。", "Membuat sweater wol domba.", "N4"],
  ["猿", "saru", "さる", "Monyet kera", "温泉に入る猿です。", "Monyet yang mandi berendam di onsen.", "N4"],
  ["熊", "kuma", "くま", "Beruang rimba", "森に熊が出ました。", "Beruang muncul di hutan rimba.", "N4"],
  ["象", "zou", "ぞう", "Gajah belalai", "象の鼻は長いです。", "Belalai gajah sangat panjang.", "N4"],
  ["虫", "mushi", "むし", "Serangga kutu", "虫の音が聞こえます。", "Terdengar derik serangga malam.", "N5"]
];

for (const n of natureData) {
  add(n[0], n[1], n[2], n[3], n[4], n[5], n[6], 'alam_hewan');
}

// 10. PROFESI, SEKOLAH & KERJA ~80 items
const schoolWorkData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["先生", "sensei", "せんせい", "Guru / Dosen pendidik", "田中先生に質問します。", "Bertanya kepada pak guru Tanaka.", "N5"],
  ["学生", "gakusei", "がくせい", "Siswa pelajar / Mahasiswa", "留学生と仲良くなりました。", "Akrab dengan mahasiswa asing.", "N5"],
  ["生徒", "seito", "せいと", "Murid sekolah SMP/SMA", "真面目な生徒たちです。", "Murid-murid yang tekun belajar.", "N5"],
  ["会社員", "kaishain", "かいしゃいん", "Karyawan perusahaan kantor", "父は会社員です。", "Ayah saya karyawan kantor.", "N5"],
  ["公務員", "koumuin", "こうむいん", "Pegawai negeri sipil (PNS)", "安定した公務員です。", "Pegawai negeri yang mapan.", "N4"],
  ["社長", "shachou", "しゃちょう", "Direktur utama / CEO", "社長の挨拶です。", "Sambutan dari direktur utama.", "N4"],
  ["部長", "buchou", "ぶちょう", "Kepala divisi / Manajer departemen", "部長に報告します。", "Melapor kepada kepala divisi.", "N4"],
  ["同僚", "douryou", "どうりょう", "Rekan kerja sekantor", "同僚とランチを食べます。", "Makan siang bersama rekan kerja.", "N4"],
  ["仕事", "shigoto", "しごと", "Pekerjaan profesi", "仕事に一生懸命です。", "Bekerja dengan sepenuh hati.", "N5"],
  ["会社", "kaisha", "かいしゃ", "Perusahaan kantor", "貿易会社に勤めています。", "Bekerja di perusahaan dagang ekspor-impor.", "N5"],
  ["事務所 / オフィス", "jimusho / ofisu", "じむしょ", "Kantor ruang kerja", "事務所で打ち合わせします。", "Pertemuan rapat di kantor.", "N4"],
  ["会議", "kaigi", "かいぎ", "Rapat rapat dinas", "大事な会議があります。", "Ada agenda rapat penting.", "N5"],
  ["資料", "shiryou", "しりょう", "Bahan berkas dokumen / Materi", "会議の資料を配ります。", "Membagikan materi berkas rapat.", "N4"],
  ["名刺", "meishi", "めいし", "Kartu nama bisnis", "名刺を交換します。", "Bertukar kartu nama bisnis.", "N4"],
  ["書類", "shorui", "しょるい", "Dokumen formulir resmi", "書類にサインします。", "Menandatangani dokumen formulir.", "N4"],
  ["宿題", "shukudai", "しゅくだい", "Pekerjaan rumah (PR)", "宿題を提出します。", "Mengumpulkan tugas PR sekolah.", "N5"],
  ["授業", "jugyou", "じゅぎょう", "Jam pelajaran kuliah", "日本語の授業です。", "Pelajaran bahasa Jepang.", "N5"],
  ["試験 / テスト", "shiken / tesuto", "しけん", "Ujian evaluasi / Tes", "期末試験があります。", "Ada ujian akhir semester.", "N5"],
  ["教科書", "kyoukasho", "きょうかしょ", "Buku teks pelajaran resmi", "教科書を開いてください。", "Tolong buka buku pelajaran teks.", "N5"],
  ["質問", "shitsumon", "しつもん", "Pertanyaan", "質問をどうぞ。", "Silakan ajukan pertanyaan.", "N5"],
  ["答え", "kotae", "こたえ", "Jawaban penyelesaian", "正しい答えを書きます。", "Menulis jawaban yang tepat benar.", "N5"],
  ["意味", "imi", "いみ", "Makna arti kata", "単語の意味を調べます。", "Mencari tahu arti kosakata kata.", "N5"],
  ["作文", "sakubun", "さくぶん", "Karangan tulisan esai", "作文を書きました。", "Menulis esai karangan cerita.", "N5"],
  ["文法", "bunpou", "ぶんぽう", "Tata bahasa gramatika", "日本語の文法を学びます。", "Mempelajari tata bahasa Jepang.", "N5"],
  ["発音", "hatsuon", "はつおん", "Pelafalan pengucapan intonasi", "発音がとても綺麗ですね。", "Pelafalan intonasi sangat bagus.", "N4"]
];

for (const s of schoolWorkData) {
  add(s[0], s[1], s[2], s[3], s[4], s[5], s[6], 'profesi_sekolah');
}

// 11. KATA KETERANGAN (FUKUSHI), KONJUNGSI & EKSPRESI ~80 items
const adverbData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["とても / 大変", "totemo / taihen", "とても", "Sangat / Amat sekali", "とても美味しい料理です。", "Masakan yang sangat lezat.", "N5"],
  ["少し / ちょっと", "sukoshi / chotto", "すこし", "Sedikit / Sebentar waktu", "少し疲れています。", "Saya agak sedikit lelah.", "N5"],
  ["たくさん", "takusan", "たくさん", "Banyak jumlahnya", "たくさん食べました。", "Saya sudah makan banyak porsi.", "N5"],
  ["いつも", "itsumo", "いつも", "Selalu senantiasa", "いつも笑顔です。", "Selalu tersenyum manis ceria.", "N5"],
  ["よく", "yoku", "よく", "Sering / Dengan baik mahir", "よく読書をします。", "Sering membaca buku bacaan.", "N5"],
  ["時々", "tokidoki", "ときどき", "Kadang-kadang tempo hari", "時々外食します。", "Kadang-kadang makan di luar.", "N5"],
  ["あまり（〜ない）", "amari (...nai)", "あまり", "Jarang / Tidak begitu (negatif)", "あまりテレビを見ません。", "Jarang menonton siaran televisi.", "N5"],
  ["全然（〜ない）", "zenzen (...nai)", "ぜんぜん", "Sama sekali tidak (negatif)", "全然分かりません。", "Sama sekali tidak paham mengerti.", "N5"],
  ["もう", "mou", "もう", "Sudah / Lagi sekali", "もう食べました。", "Sudah selesai makan.", "N5"],
  ["まだ（〜ない）", "mada (...nai)", "まだ", "Masih / Belum", "まだ宿題をしていません。", "Belum mengerjakan tugas PR.", "N5"],
  ["一緒に", "isshoni", "いっしょに", "Bersama-sama bareng", "一緒に行きましょう。", "Mari pergi bersama-sama.", "N5"],
  ["一人で", "hitoride", "ひとりで", "Sendirian seorang diri", "一人で暮らしています。", "Tinggal seorang diri di kos.", "N5"],
  ["まっすぐ", "massugu", "まっすぐ", "Lurus terus jalan", "まっすぐ進んでください。", "Silakan jalan lurus terus.", "N5"],
  ["ゆっくり", "yukkuri", "ゆっくり", "Pelan-pelan / Santai rileks", "ゆっくり休んでください。", "Silakan beristirahat dengan santai.", "N5"],
  ["だんだん", "dandan", "だんだん", "Lama-kelamaan / Berangsur-angsur", "だんだん寒くなります。", "Lama-kelamaan makin dingin cuacanya.", "N5"],
  ["初めて", "hajimete", "はじめて", "Pertama kalinya perdana", "初めて日本へ行きました。", "Pertama kalinya pergi ke Jepang.", "N5"],
  ["ちょうど", "choudo", "ちょうど", "Tepat persis pas", "ちょうど10時です。", "Tepat persis jam 10 pas.", "N5"],
  ["きっと", "kitto", "きっと", "Pasti niscaya yakin", "きっと合格できます。", "Pasti bisa lulus dengan yakin.", "N4"],
  ["たぶん", "tabun", "たぶん", "Mungkin barangkali", "たぶん明日は雨でしょう。", "Mungkin besok akan turun hujan.", "N5"],
  ["もし", "moshi", "もし", "Jikalau seandainya", "もし時間があれば会いましょう。", "Jika ada waktu luang ayo bertemu.", "N4"],
  ["すぐに", "suguni", "すぐに", "Segera saat itu juga", "すぐに戻ります。", "Segera kembali dalam sekejap.", "N5"],
  ["もうすぐ", "mousugu", "もうすぐ", "Sebentar lagi lekas", "もうすぐ電車が来ます。", "Sebentar lagi keretanya tiba.", "N5"],
  ["大体", "daitai", "だいたい", "Sebagian besar / Kira-kira", "大体理解できました。", "Sebagian besar sudah dipahami.", "N5"],
  ["特に", "tokuni", "とくに", "Terutama khususnya", "特に問題はありません。", "Khususnya tidak ada kendala masalah.", "N4"],
  ["実は", "jitsuwa", "じつは", "Sebenarnya faktanya", "実は秘密があります。", "Sebenarnya ada rahasia terselubung.", "N4"],
  ["急に", "kyuuni", "きゅうに", "Tiba-tiba sekonyong-konyong", "急に雨が降り出しました。", "Tiba-tiba hujan mulai turun.", "N4"],
  ["やっと", "yatto", "やっと", "Akhirnya setelah berjuang", "やっと宿題が終わりました。", "Akhirnya tugas PR selesai juga.", "N4"],
  ["とうとう", "toutou", "とうとう", "Pada akhirnya sudah", "とうとう夢が叶いました。", "Pada akhirnya impian terwujud.", "N4"],
  ["しかし / でも", "shikashi / demo", "しかし", "Tetapi namun akan tetapi", "でも諦めません。", "Tetapi saya tidak akan menyerah.", "N5"],
  ["だから / ですから", "dakara / desukara", "だから", "Oleh karena itu maka dari itu", "ですから急ぎましょう。", "Oleh karena itu mari lekas bergegas.", "N5"]
];

for (const adv of adverbData) {
  add(adv[0], adv[1], adv[2], adv[3], adv[4], adv[5], adv[6], 'keterangan_fukushi');
}

// 12. SALAM, UNGKAPAN & TATA KRAMA ~35 items
const greetData: [string, string, string, string, string, string, 'N5' | 'N4'][] = [
  ["おはようございます", "ohayou gozaimasu", "おはようございます", "Selamat pagi (sopan)", "先生、おはようございます。", "Selamat pagi, Pak/Bu Guru.", "N5"],
  ["こんにちは", "konnichiwa", "こんにちは", "Selamat siang / Halo", "皆様、こんにちは。", "Halo semuanya, selamat siang.", "N5"],
  ["こんばんは", "konbanwa", "こんばんは", "Selamat malam salam sapa", "こんばんは、お元気ですか？", "Selamat malam, apa kabarnya?", "N5"],
  ["おやすみなさい", "oyasuminasai", "おやすみなさい", "Selamat tidur / Selamat beristirahat", "おやすみなさい、良い夢を。", "Selamat tidur, semoga mimpi indah.", "N5"],
  ["ありがとうございます", "arigatou gozaimasu", "ありがとうございます", "Terima kasih banyak (sopan)", "ご親切にありがとうございます。", "Terima kasih banyak atas keramahan Anda.", "N5"],
  ["どういたしまして", "douitashimashite", "どういたしまして", "Sama-sama / Kembali terima kasih", "どういたしまして、お役に立てて嬉しいです。", "Sama-sama, senang bisa membantu.", "N5"],
  ["すみません", "sumimasen", "すみません", "Maaf / Permisi / Terima kasih", "すみません、道を教えてください。", "Permisi, tolong beri tahu jalannya.", "N5"],
  ["ごめんなさい", "gomen nasai", "ごめんなさい", "Mohon maaf tulus hati", "遅れてごめんなさい。", "Mohon maaf karena terlambat.", "N5"],
  ["失礼します", "shitsurei shimasu", "しつれいします", "Permisi masuk / Pamit undur diri", "お先に失礼します。", "Saya permisi pamit undur diri duluan.", "N5"],
  ["いただきます", "itadakimasu", "いただきます", "Selamat makan (doa syukur sebelum makan)", "感謝していただきます。", "Dengan bersyukur mari makan.", "N5"],
  ["ごちそうさまでした", "gochisousama deshita", "ごちそうさまでした", "Terima kasih atas hidangan lezatnya", "美味しかった、ごちそうさまでした。", "Sangat lezat, terima kasih hidangannya.", "N5"],
  ["いってきます", "ittekimasu", "いってきます", "Saya berangkat dulu ya!", "学校へいってきます！", "Saya pamit berangkat ke sekolah!", "N5"],
  ["いってらっしゃい", "itterasshai", "いってらっしゃい", "Selamat jalan / Hati-hati di jalan", "気をつけていってらっしゃい。", "Hati-hati dan selamat di jalan.", "N5"],
  ["ただいま", "tadaima", "ただいま", "Saya pulang / Saya sudah kembali", "ただいま、お腹が空いたよ。", "Saya sudah pulang, perut lapar nih.", "N5"],
  ["おかえりなさい", "okaerinasai", "おかえりなさい", "Selamat datang kembali di rumah", "おかえりなさい、お疲れ様。", "Selamat pulang kembali ke rumah.", "N5"],
  ["お疲れ様でした", "otsukaresama deshita", "おつかれさまでした", "Terima kasih atas kerja keras hari ini", "今日も一日お疲れ様でした。", "Terima kasih atas kerja kerasnya hari ini.", "N5"],
  ["初めまして", "hajimemashite", "はじめまして", "Senang berkenalan dengan Anda pertama kali", "初めまして、よろしくお願いします。", "Senang berkenalan, mohon bimbingannya.", "N5"],
  ["よろしくお願いします", "yoroshiku onegai shimasu", "よろしくおねがいします", "Mohon bantuan dan kerja samanya", "これからよろしくお願いします。", "Mulai sekarang mohon kerja samanya.", "N5"],
  ["おめでとうございます", "omedetou gozaimasu", "おめでとうございます", "Selamat ya! (ulang tahun/kelulusan)", "お誕生日おめでとうございます！", "Selamat merayakan hari ulang tahun!", "N5"],
  ["乾杯！", "kanpai!", "かんぱい！", "Bersulang minuman bersulang!", "みんなの成功を祝って乾杯！", "Bersulang demi kesuksesan kita semua!", "N5"]
];

for (const g of greetData) {
  add(g[0], g[1], g[2], g[3], g[4], g[5], g[6], 'salam');
}

import { batch2List } from './vocabBatch2';
list.push(...batch2List);

import { batch3List } from './vocabBatch3';
list.push(...batch3List);

console.log(`\n========================================`);
console.log(`TOTAL VOCABULARY ITEMS GENERATED: ${list.length}`);
console.log(`========================================\n`);

// Format with IDs
const formattedCards = list.map((item, idx) => ({
  id: `voc-${String(idx + 1).padStart(4, '0')}`,
  category: 'vocab',
  subCategory: item.subCategory,
  japanese: item.kanji,
  kanji: /[\u4e00-\u9faf]/.test(item.kanji) ? item.kanji : undefined,
  reading: item.reading,
  furigana: item.furigana,
  meaningId: item.meaningId,
  exampleJp: item.exampleJp,
  exampleId: item.exampleId,
  level: item.level
}));

const outPath = path.resolve('src/data/vocab/vocab1000.json');
fs.writeFileSync(outPath, JSON.stringify(formattedCards, null, 2), 'utf-8');
console.log(`Successfully written to ${outPath}`);
