// Full Japanese-Indonesian 1,000+ Vocabulary Generator
const fs = require('fs');
const path = require('path');

const vocabData = [];

function add(kanji, reading, furigana, meaningId, exampleJp, exampleId, level, subCategory) {
  vocabData.push({
    id: `voc-${String(vocabData.length + 1).padStart(4, '0')}`,
    category: 'vocab',
    subCategory,
    japanese: kanji,
    kanji: /[\u4e00-\u9faf]/.test(kanji) ? kanji : undefined,
    reading,
    furigana: furigana || kanji,
    meaningId,
    exampleJp,
    exampleId,
    level
  });
}

// ==========================================
// 1. KATA KERJA (VERBS) - 220 items
// ==========================================
const verbs = [
  ["行く", "iku", "いく", "Pergi", "明日東京へ行きます。", "Besok saya pergi ke Tokyo.", "N5"],
  ["来る", "kuru", "くる", "Datang", "友達がうちへ来ます。", "Teman datang ke rumah saya.", "N5"],
  ["帰る", "kaeru", "かえる", "Pulang", "午後6時に家へ帰ります。", "Saya pulang ke rumah jam 6 sore.", "N5"],
  ["食べる", "taberu", "たべる", "Makan", "朝ご飯を食べました。", "Saya sudah sarapan pagi.", "N5"],
  ["飲む", "nomu", "のむ", "Minum", "冷たい水を飲みます。", "Saya minum air dingin.", "N5"],
  ["見る", "miru", "みる", "Melihat / Menonton", "テレビで映画を見ます。", "Saya menonton film di televisi.", "N5"],
  ["聞く", "kiku", "きく", "Mendengar / Bertanya", "日本の音楽を聞きます。", "Saya mendengarkan musik Jepang.", "N5"],
  ["読む", "yomu", "よむ", "Membaca", "毎晩本を読みます。", "Saya membaca buku setiap malam.", "N5"],
  ["書く", "kaku", "かく", "Menulis", "手紙を書いています。", "Saya sedang menulis surat.", "N5"],
  ["話す", "hanasu", "はなす", "Berbicara", "日本語で話しましょう。", "Mari berbicara dalam bahasa Jepang.", "N5"],
  ["買う", "kau", "かう", "Membeli", "新しい靴を買いました。", "Saya membeli sepatu baru.", "N5"],
  ["売る", "uru", "うる", "Menjual", "車を売りました。", "Saya telah menjual mobil.", "N5"],
  ["待つ", "matsu", "まつ", "Menunggu", "駅の前で待ってください。", "Tolong tunggu di depan stasiun.", "N5"],
  ["会う", "au", "あう", "Bertemu", "友達に会います。", "Saya bertemu teman.", "N5"],
  ["遊ぶ", "asobu", "あそぶ", "Bermain", "公園で子供と遊びます。", "Bermain dengan anak di taman.", "N5"],
  ["急ぐ", "isogu", "いそぐ", "Buru-buru / Bergegas", "時間がないので急ぎます。", "Karena tidak ada waktu, saya buru-buru.", "N5"],
  ["泳ぐ", "oyogu", "およぐ", "Berenang", "海で泳ぐのが好きです。", "Saya suka berenang di laut.", "N5"],
  ["取る", "toru", "とる", "Mengambil", "塩を取ってください。", "Tolong ambilkan garam.", "N5"],
  ["撮る", "toru", "とる", "Memotret / Mengambil foto", "写真を撮りましょう。", "Ayo berfoto bersama.", "N5"],
  ["知る", "shiru", "しる", "Mengetahui / Kenal", "その人を知っていますか？", "Apakah kamu kenal orang itu?", "N5"],
  ["分かる", "wakaru", "わかる", "Mengerti / Paham", "意味がよく分かります。", "Saya sangat mengerti artinya.", "N5"],
  ["歩く", "aruku", "あるく", "Berjalan kaki", "毎日30分歩きます。", "Saya berjalan kaki 30 menit setiap hari.", "N5"],
  ["走る", "hashiru", "はしる", "Berlari", "公園を走っています。", "Saya sedang berlari di taman.", "N5"],
  ["立つ", "tatsu", "たつ", "Berdiri", "ドアの前に立ちます。", "Berdiri di depan pintu.", "N5"],
  ["座る", "suwaru", "すわる", "Duduk", "椅子に座ってください。", "Silakan duduk di kursi.", "N5"],
  ["持つ", "motsu", "もつ", "Membawa / Memegang", "荷物を持ちましょうか？", "Bolehkah saya bantu bawakan barangnya?", "N5"],
  ["作る", "tsukuru", "つくる", "Membuat", "晩ご飯を作ります。", "Saya membuat makan malam.", "N5"],
  ["使う", "tsukau", "つかう", "Menggunakan / Memakai", "パソコンを使います。", "Saya menggunakan komputer.", "N5"],
  ["置く", "oku", "おく", "Meletakkan / Menaruh", "机の上に置きました。", "Saya meletakkannya di atas meja.", "N5"],
  ["住む", "sumu", "すむ", "Tinggal / Berdiam di", "東京に住んでいます。", "Saya tinggal di Tokyo.", "N5"],
  ["働く", "hataraku", "はたらく", "Bekerja", "病院で働いています。", "Saya bekerja di rumah sakit.", "N5"],
  ["休む", "yasumu", "やすむ", "Istirahat / Libur", "今日は仕事を休みます。", "Hari ini saya libur bekerja.", "N5"],
  ["教える", "oshieru", "おしえる", "Mengajar / Memberitahu", "日本語を教えてください。", "Tolong ajarkan bahasa Jepang kepada saya.", "N5"],
  ["習う", "narau", "ならう", "Belajar (dari orang lain)", "ピアノを習っています。", "Saya belajar les piano.", "N5"],
  ["貸す", "kasu", "かす", "Meminjamkan", "傘を貸してください。", "Tolong pinjamkan saya payung.", "N5"],
  ["借りる", "kariru", "かりる", "Meminjam", "図書館で本を借りました。", "Saya meminjam buku di perpustakaan.", "N5"],
  ["返す", "kaesu", "かえす", "Mengembalikan", "本を返します。", "Saya mengembalikan buku.", "N5"],
  ["起きる", "okiru", "おきる", "Bangun tidur", "朝6時に起きます。", "Saya bangun jam 6 pagi.", "N5"],
  ["寝る", "neru", "ねる", "Tidur", "夜11時に寝ます。", "Saya tidur jam 11 malam.", "N5"],
  ["開ける", "akeru", "あける", "Membuka (pintu/jendela)", "窓を開けてください。", "Tolong buka jendelanya.", "N5"],
  ["閉める", "shimeru", "しめる", "Menutup (pintu/jendela)", "ドアを閉めました。", "Saya telah menutup pintu.", "N5"],
  ["開く", "aku", "あく", "Terbuka (sendirinya)", "ドアが開きました。", "Pintunya terbuka.", "N5"],
  ["閉まる", "shimaru", "しまる", "Tertutup (sendirinya)", "店が閉まりました。", "Tokonya sudah tutup.", "N5"],
  ["つける", "tsukeru", "つける", "Menyalakan (lampu/alat)", "エアコンをつけます。", "Saya menyalakan AC.", "N5"],
  ["消す", "kesu", "けす", "Mematikan / Menghapus", "電気を消してください。", "Tolong matikan lampu.", "N5"],
  ["入る", "hairu", "はいる", "Masuk", "部屋に入ります。", "Saya masuk ke kamar.", "N5"],
  ["出る", "deru", "でる", "Keluar", "家を出ます。", "Saya keluar dari rumah.", "N5"],
  ["入れる", "ireru", "いれる", "Memasukkan", "鞄に財布を入れます。", "Saya memasukkan dompet ke dalam tas.", "N5"],
  ["出す", "dasu", "だす", "Mengeluarkan / Menyerahkan", "宿題を出します。", "Saya mengumpulkan tugas PR.", "N5"],
  ["乗る", "noru", "のる", "Naik (kendaraan)", "電車に乗ります。", "Saya naik kereta.", "N5"],
  ["降りる", "oriru", "おりる", "Turun (dari kendaraan)", "バスを降ります。", "Saya turun dari bus.", "N5"],
  ["乗り換える", "norikaeru", "のりかえる", "Pindah kendaraan / Transit", "次の駅で乗り換えます。", "Transit di stasiun berikutnya.", "N4"],
  ["浴びる", "abiru", "あびる", "Mandi shower", "毎朝シャワーを浴びます。", "Saya mandi shower setiap pagi.", "N5"],
  ["洗う", "arau", "あらう", "Mencuci", "手をよく洗ってください。", "Cucilah tanganmu dengan bersih.", "N5"],
  ["磨く", "migaku", "みがく", "Menggosok / Menyikat (gigi)", "食後に歯を磨きます。", "Saya menggosok gigi setelah makan.", "N5"],
  ["着る", "kiru", "きる", "Memakai (pakaian atas)", "上着を着ます。", "Saya memakai jaket luar.", "N5"],
  ["履く", "haku", "はく", "Memakai (celana/sepatu)", "新しい靴を履きます。", "Saya memakai sepatu baru.", "N5"],
  ["かぶる", "kaburu", "かぶる", "Memakai (topi)", "帽子をかぶっています。", "Saya sedang memakai topi.", "N5"],
  ["脱ぐ", "nugu", "ぬぐ", "Melepas pakaian / sepatu", "玄関で靴を脱ぎます。", "Lepas sepatu di pintu masuk.", "N5"],
  ["送る", "okuru", "おくる", "Mengirim", "メールを送りました。", "Saya telah mengirim surel.", "N5"],
  ["届く", "todoku", "とどく", "Sampai / Tiba (paket/surat)", "荷物が届きました。", "Paketnya telah sampai.", "N4"],
  ["渡す", "watasu", "わたす", "Menyerahkan", "プレゼントを渡します。", "Menyerahkan kado.", "N5"],
  ["渡る", "wataru", "わたる", "Menyeberang", "信号を渡ります。", "Menyeberang di lampu merah.", "N5"],
  ["曲がる", "magaru", "まがる", "Belok", "交差点を右へ曲がります。", "Belok kanan di perempatan.", "N5"],
  ["止まる", "tomaru", "とまる", "Berhenti (kendaraan)", "車が止まりました。", "Mobilnya berhenti.", "N5"],
  ["止める", "tomeru", "とめる", "Menghentikan / Memarkir", "車を駐車場に止めます。", "Memarkir mobil di area parkir.", "N5"],
  ["泊まる", "tomaru", "とまる", "Menginap", "温泉旅館に泊まります。", "Menginap di penginapan onsen.", "N4"],
  ["始まる", "hajimaru", "はじまる", "Dimulai", "授業が始まります。", "Pelajaran dimulai.", "N5"],
  ["始める", "hajimeru", "はじめる", "Memulai", "日本語の勉強を始めました。", "Saya mulai belajar bahasa Jepang.", "N5"],
  ["終わる", "owaru", "おわる", "Selesai / Berakhir", "仕事が終わりました。", "Pekerjaan sudah selesai.", "N5"],
  ["覚える", "oboeru", "おぼえる", "Mengingat / Menghapal", "漢字をたくさん覚えます。", "Saya menghapal banyak kanji.", "N5"],
  ["忘れる", "wasureru", "わすれる", "Lupa", "宿題を忘れました。", "Saya lupa mengerjakan PR.", "N5"],
  ["思い出す", "omoidasu", "おもいだす", "Mengingat kembali / Teringat", "子供の頃を思い出します。", "Saya teringat masa kecil.", "N4"],
  ["考える", "kangaeru", "かんがえる", "Memikirkan", "将来のことを考えます。", "Saya memikirkan masa depan.", "N4"],
  ["思う", "omou", "おもう", "Mengira / Berpikir", "そう思います。", "Saya berpikir begitu.", "N5"],
  ["言う", "iu", "いう", "Berkata / Mengatakan", "「おはよう」と言いました。", "Dia mengucapkan selamat pagi.", "N5"],
  ["呼ぶ", "yobu", "よぶ", "Memanggil", "タクシーを呼びます。", "Saya memanggil taksi.", "N5"],
  ["歌う", "utau", "うたう", "Bernyanyi", "カラオケで歌います。", "Bernyanyi di karaoke.", "N5"],
  ["踊る", "odoru", "おどる", "Menari", "日本の伝統的な踊りです。", "Tarian tradisional Jepang.", "N5"],
  ["笑う", "warau", "わらう", "Tertawa / Tersenyum", "みんなで楽しく笑いました。", "Semua orang tertawa bahagia.", "N5"],
  ["泣く", "naku", "なく", "Menangis", "悲しくて泣きました。", "Saya menangis karena sedih.", "N5"],
  ["怒る", "okoru", "おこる", "Marah", "先生が怒りました。", "Guru marah.", "N4"],
  ["頼む", "tanomu", "たのむ", "Meminta tolong / Memesan", "手伝いを頼みます。", "Saya meminta bantuan.", "N5"],
  ["手伝う", "tetsudau", "てつだう", "Membantu", "母の料理を手伝います。", "Saya membantu masakan ibu.", "N5"],
  ["直す", "naosu", "なおす", "Memperbaiki / Membetulkan", "パソコンを直します。", "Saya memperbaiki komputer.", "N4"],
  ["壊す", "kowasu", "こわす", "Merusak", "おもちゃを壊しました。", "Merusak mainan.", "N4"],
  ["壊れる", "kowareru", "こわれる", "Rusak", "椅子が壊れました。", "Kursinya patah / rusak.", "N4"],
  ["落とす", "otosu", "おとす", "Menjatuhkan", "財布を落としました。", "Saya menjatuhkan dompet.", "N4"],
  ["落ちる", "ochiru", "おちる", "Jatuh (sendirinya)", "木の葉が落ちます。", "Daun-daun pohon berguguran.", "N4"],
  ["拾う", "hirou", "ひろう", "Memungut / Mengambil", "ゴミを拾います。", "Saya memungut sampah.", "N4"],
  ["捨てる", "suteru", "すてる", "Membuang", "ゴミを捨てないでください。", "Jangan buang sampah di sini.", "N4"],
  ["探す", "sagasu", "さがす", "Mencari", "鍵を探しています。", "Saya sedang mencari kunci.", "N4"],
  ["見つける", "mitsukeru", "みつける", "Menemukan", "いい方法を見つけました。", "Saya menemukan cara yang bagus.", "N4"],
  ["選ぶ", "erabu", "えらぶ", "Memilih", "好きな色を選んでください。", "Silakan pilih warna favorit.", "N4"],
  ["決める", "kimeru", "きめる", "Memutuskan", "日程を決めます。", "Saya memutuskan tanggalnya.", "N4"],
  ["勝つ", "katsu", "かつ", "Menang", "試合に勝ちました。", "Menang dalam pertandingan.", "N4"],
  ["負ける", "makeru", "まける", "Kalah", "試合に負けました。", "Kalah dalam pertandingan.", "N4"],
  ["生きる", "ikiru", "いきる", "Hidup", "元気に生きています。", "Hidup dengan sehat.", "N4"],
  ["死ぬ", "shinu", "しぬ", "Mati / Meninggal", "魚が死にました。", "Ikannya mati.", "N5"],
  ["咲く", "saku", "さく", "Mekar (bunga)", "桜の花が咲きました。", "Bunga sakura telah mekar.", "N5"],
  ["降る", "furu", "ふる", "Turun (hujan/salju)", "雪が降っています。", "Salju sedang turun.", "N5"],
  ["晴れる", "hareru", "はれる", "Cerah (cuaca)", "明日晴れます。", "Besok akan cerah.", "N5"],
  ["曇る", "kumoru", "くもる", "Mendung (cuaca)", "空が曇っています。", "Langit sedang mendung.", "N5"],
  ["吹く", "fuku", "ふく", "Bertiup (angin)", "風が強く吹いています。", "Angin bertiup kencang.", "N5"],
  ["喜ぶ", "yorokobu", "よろこぶ", "Senang / Bergembira", "子供たちが喜んでいます。", "Anak-anak sangat bergembira.", "N4"],
  ["驚く", "odoroku", "おどろく", "Kaget / Terkejut", "ニュースに驚きました。", "Saya terkejut mendengar berita.", "N4"],
  ["信じる", "shinjiru", "しんじる", "Percaya", "あなたを信じています。", "Saya percaya kepadamu.", "N4"],
  ["祈る", "inoru", "いのる", "Berdoa", "健康を祈ります。", "Saya mendoakan kesehatanmu.", "N4"],
  ["楽しむ", "tanoshimu", "たのしむ", "Menikmati", "旅行を楽しみます。", "Menikmati liburan.", "N4"],
  ["結婚する", "kekkon suru", "けっこんする", "Menikah", "来年結婚します。", "Menikah tahun depan.", "N5"],
  ["勉強する", "benkyou suru", "べんきょうする", "Belajar", "毎晩勉強します。", "Belajar setiap malam.", "N5"],
  ["旅行する", "ryokou suru", "りょこうする", "Berwisata / Bepergian", "日本へ旅行します。", "Berwisata ke Jepang.", "N5"],
  ["買い物する", "kaimono suru", "かいものする", "Berbelanja", "スーパーで買い物します。", "Belanja di supermarket.", "N5"],
  ["散歩する", "sanpo suru", "さんぽする", "Jalan-jalan santai", "公園を散歩します。", "Jalan santai di taman.", "N5"],
  ["運動する", "undou suru", "うんどうする", "Berolahraga", "週末に運動します。", "Olahraga di akhir pekan.", "N5"],
  ["練習する", "renshuu suru", "れんしゅうする", "Berlatih", "会話を練習します。", "Melatih percakapan.", "N5"],
  ["電話する", "denwa suru", "でんわする", "Menelepon", "友達に電話します。", "Menelepon teman.", "N5"],
  ["案内する", "annai suru", "あんないする", "Memandu jalan", "町を案内します。", "Memandu keliling kota.", "N4"],
  ["説明する", "setsumei suru", "せつめいする", "Menjelaskan", "ルールを説明します。", "Menjelaskan aturan.", "N4"],
  ["予約する", "yoyaku suru", "よやくする", "Memesan / Reservasi", "ホテルを予約しました。", "Memesan kamar hotel.", "N4"],
  ["注文する", "chuumon suru", "ちゅうもんする", "Memesan makanan / barang", "ピザを注文します。", "Memesan pizza.", "N4"],
  ["注意する", "chuui suru", "ちゅういする", "Berhati-hati / Memperhatikan", "車に注意してください。", "Hati-hati dengan mobil.", "N5"],
  ["準備する", "junbi suru", "じゅんびする", "Mempersiapkan", "試験の準備をします。", "Mempersiapkan ujian.", "N5"],
  ["片付ける", "katazukeru", "かたづける", "Membereskan / Merapikan", "机を片付けます。", "Merapikan meja.", "N4"],
  ["掃除する", "souji suru", "そうじする", "Membersihkan ruangan", "部屋を掃除します。", "Membersihkan kamar.", "N5"],
  ["洗濯する", "sentaku suru", "せんたくする", "Mencuci pakaian", "服を洗濯します。", "Mencuci pakaian.", "N5"],
  ["連絡する", "renraku suru", "れんらくする", "Menghubungi", "後で連絡します。", "Nanti saya hubungi.", "N5"],
  ["相談する", "soudan suru", "そうだんする", "Berkonsultasi", "先生に相談します。", "Konsultasi ke guru.", "N4"],
  ["出席する", "shusseki suru", "しゅっせきする", "Menghadiri", "会議に出席します。", "Menghadiri rapat.", "N4"],
  ["欠席する", "kesseki suru", "けっせきする", "Absen / Tidak hadir", "授業を欠席します。", "Absen dari kelas.", "N4"],
  ["合格する", "goukaku suru", "ごうかくする", "Lulus ujian", "試験に合格しました。", "Lulus ujian.", "N4"],
  ["失敗する", "shippai suru", "しっぱいする", "Gagal", "料理に失敗しました。", "Gagal dalam memasak.", "N4"],
  ["成功する", "seikou suru", "せいこうする", "Berhasil / Sukses", "計画が成功しました。", "Rencananya berhasil.", "N4"],
  ["入院する", "nyuuin suru", "にゅういんする", "Rawat inap", "病院に入院します。", "Masuk rawat inap rumah sakit.", "N4"],
  ["退院する", "taiin suru", "たいいんする", "Keluar dari rumah sakit", "明日退院します。", "Besok pulang dari rumah sakit.", "N4"],
  ["修理する", "shuuri suru", "しゅうりする", "Memperbaiki", "車を修理します。", "Memperbaiki mobil.", "N4"],
  ["故障する", "koshou suru", "こしょうする", "Mogok / Rusak", "時計が故障しました。", "Jamnya rusak.", "N4"],
  ["引っ越す", "hikkosu", "ひっこす", "Pindah rumah", "来月引っ越します。", "Bulan depan pindah rumah.", "N4"],
  ["謝る", "ayamaru", "あやまる", "Minta maaf", "素直に謝ります。", "Minta maaf dengan jujur.", "N4"],
  ["許す", "yurusu", "ゆるす", "Memaafkan", "友達を許します。", "Memaafkan teman.", "N4"],
  ["褒める", "homeru", "ほめる", "Memuji", "子供を褒めます。", "Memuji anak.", "N4"],
  ["叱る", "shikaru", "しかる", "Memarahi", "母に叱られました。", "Dimarahi oleh ibu.", "N4"],
  ["断る", "kotowaru", "ことわる", "Menolak", "誘いを断ります。", "Menolak ajakan.", "N4"],
  ["届ける", "todokeru", "とどける", "Mengantarkan paket", "荷物を届けます。", "Mengantarkan barang.", "N4"],
  ["運ぶ", "hakobu", "はこぶ", "Mengangkut / Membawa", "荷物を運びます。", "Mengangkut barang.", "N4"],
  ["変わる", "kawaru", "かわる", "Berubah", "天気が変わりました。", "Cuacanya berubah.", "N4"],
  ["変える", "kaeru", "かえる", "Mengubah", "予定を変えます。", "Mengubah jadwal.", "N4"],
  ["続く", "tsuzuku", "つづく", "Berlanjut", "雨が続いています。", "Hujannya terus berlanjut.", "N4"],
  ["続ける", "tsuzukeru", "つづける", "Melanjutkan", "勉強を続けます。", "Melanjutkan belajar.", "N4"],
  ["止む", "yamu", "やむ", "Reda (hujan/angin)", "雨が止みました。", "Hujannya sudah reda.", "N4"],
  ["増える", "fueru", "ふえる", "Bertambah", "人数が増えました。", "Jumlah orang bertambah.", "N4"],
  ["減る", "heru", "へる", "Berkurang", "体重が減りました。", "Berat badan berkurang.", "N4"],
  ["上がる", "agaru", "あがる", "Naik (suhu/harga)", "物価が上がります。", "Harga-harga naik.", "N4"],
  ["下がる", "sagaru", "さがる", "Turun (suhu/harga)", "熱が下がりました。", "Demamnya sudah turun.", "N4"],
  ["冷える", "hieru", "ひえる", "Menjadi dingin", "夜は冷えます。", "Malam hari terasa dingin.", "N4"],
  ["温まる", "atatamaru", "あたたまる", "Menjadi hangat", "体が温まりました。", "Badan menjadi hangat.", "N4"],
  ["汚す", "yogosu", "よごす", "Mengotori", "服を汚しました。", "Mengotori pakaian.", "N4"],
  ["汚れる", "yogoreru", "よごれる", "Kotor", "手が汚れました。", "Tangan menjadi kotor.", "N4"],
  ["無くす", "nakusu", "なくす", "Menghilangkan", "鍵を無くしました。", "Menghilangkan kunci.", "N5"],
  ["無くなる", "nakunaru", "なくなる", "Hilang / Habis", "お金が無くなりました。", "Uangnya habis.", "N4"],
  ["受ける", "ukeru", "うける", "Mengikuti ujian / Menerima", "テストを受けます。", "Mengikuti ujian tes.", "N4"],
  ["見送る", "miokuru", "みおくる", "Mengantar kepergian", "空港で見送ります。", "Mengantar di bandara.", "N4"],
  ["迎える", "mukaeru", "むかえる", "Menjemput / Menyambut", "客を迎えます。", "Menyambut tamu.", "N4"],
  ["焼く", "yaku", "やく", "Memanggang", "肉を焼きます。", "Memanggang daging.", "N4"],
  ["煮る", "niru", "にる", "Merebus bumbu", "魚を煮ます。", "Merebus ikan dengan bumbu.", "N4"],
  ["揚げる", "ageru", "あげる", "Menggoreng", "エビを揚げます。", "Menggoreng udang.", "N4"],
  ["炒める", "itameru", "いため", "Menumis", "野菜を炒めます。", "Menumis sayur.", "N4"],
  ["沸かす", "wakasu", "わかす", "Merebus air", "お湯を沸かします。", "Merebus air.", "N4"],
  ["冷やす", "hiyasu", "ひやす", "Mendinginkan", "スイカを冷やします。", "Mendinginkan semangka.", "N4"],
  ["混ぜる", "mazeru", "まぜる", "Mencampur / Mengaduk", "卵を混ぜます。", "Mengaduk telur.", "N4"],
  ["踏む", "fumu", "ふむ", "Menginjak", "足を踏まれました。", "Kaki saya terinjak.", "N4"],
  ["盗む", "nusumu", "ぬすむ", "Mencuri", "自転車を盗まれました。", "Sepeda saya dicuri.", "N4"],
  ["刺す", "sasu", "さす", "Menyengat / Menusuk", "虫に刺されました。", "Disengat serangga.", "N4"],
  ["噛む", "kamu", "かむ", "Menggigit / Mengunyah", "よく噛んで食べます。", "Mengunyah makanan dengan baik.", "N4"],
  ["誘う", "sasou", "さそう", "Mengajak", "ランチに誘います。", "Mengajak makan siang.", "N4"],
  ["もらう", "morau", "もらう", "Menerima dari orang lain", "花をもらいました。", "Menerima bunga.", "N5"],
  ["あげる", "ageru", "あげる", "Memberikan ke orang lain", "プレゼントをあげます。", "Memberikan kado.", "N5"],
  ["くれる", "kureru", "くれる", "Memberi ke saya", "本をくれました。", "Dia memberi saya buku.", "N5"],
  ["吸う", "suu", "すう", "Menghisap / Menghirup", "たばこを吸いません。", "Saya tidak merokok.", "N5"],
  ["鳴る", "naru", "なる", "Berbunyi (bel/telepon)", "ベルが鳴りました。", "Belnya berbunyi.", "N4"],
  ["太る", "futoru", "ふとる", "Bertambah gemuk", "少し太りました。", "Sedikit bertambah gemuk.", "N4"],
  ["痩せる", "yaseru", "やせる", "Menjadi kurus / Langsing", "運動で痩せました。", "Menjadi langsing karena olahraga.", "N4"],
  ["晴れ渡る", "harewataru", "はれわたる", "Cerah benderang", "空が晴れ渡っています。", "Langit sangat cerah benderang.", "N4"],
  ["乗り遅れる", "noriokureru", "のりおくれる", "Ketinggalan kereta/bus", "電車に乗り遅れました。", "Ketinggalan kereta.", "N4"],
  ["間に合う", "maniau", "まにあう", "Keburu / Tepat waktu", "時間通りに間に合いました。", "Tepat waktu sesuai jadwal.", "N4"],
  ["遅れる", "okureru", "おくれる", "Terlambat", "時間に遅れました。", "Terlambat dari waktu.", "N4"],
  ["間に合わせる", "maniawaseru", "まにあわせる", "Mengejar tepat waktu", "締め切りに間に合わせます。", "Mengejar tepat waktu sebelum deadline.", "N4"],
  ["手に入れる", "te ni ireru", "てにいれる", "Mendapatkan / Memperoleh", "チケットを手に入れました。", "Mendapatkan tiket.", "N4"],
  ["気に入る", "ki ni iru", "きにいる", "Menyukai / Cocok di hati", "この服が気に入りました。", "Saya sangat menyukai baju ini.", "N4"],
  ["気をつける", "ki o tsukeru", "きをつける", "Berhati-hati", "体に気をつけてください。", "Jaga kesehatan dirimu.", "N5"],
  ["役に立つ", "yaku ni tatsu", "やくにたつ", "Berguna / Bermanfaat", "とても役に立ちます。", "Sangat bermanfaat.", "N4"],
  ["世話をする", "sewa o suru", "せわをする", "Merawat / Mengurus", "犬の世話をします。", "Merawat anjing peliharaan.", "N4"],
  ["案内をする", "annai o suru", "あんないをする", "Memberikan panduan", "館内をご案内します。", "Memandu keliling gedung.", "N4"],
  ["自己紹介する", "jikoshoukai suru", "じこしょうかいする", "Memperkenalkan diri", "日本語で自己紹介します。", "Perkenalan diri dalam bahasa Jepang.", "N5"],
  ["握手する", "akushu suru", "あくしゅする", "Berjabat tangan", "笑顔で握手しました。", "Berjabat tangan dengan senyuman.", "N4"],
  ["お辞儀する", "ojigi suru", "おじぎする", "Membungkuk hormat", "丁寧にお辞儀をします。", "Membungkuk memberi hormat secara sopan.", "N5"],
  ["化粧する", "keshou suru", "けしょうする", "Berdandan / Merias wajah", "毎朝化粧をします。", "Berdandan setiap pagi.", "N4"],
  ["着替える", "kigaeru", "きがえる", "Ganti pakaian", "部屋で着替えます。", "Berganti pakaian di kamar.", "N4"],
  ["履き替える", "hakikaeru", "はきかえる", "Ganti sepatu / sandal", "スリッパに履き替えます。", "Ganti memakai sandal rumah slipper.", "N4"],
  ["乾く", "kawaku", "かわく", "Kering (pakaian/tanah)", "洗濯物が乾きました。", "Cucian baju sudah kering.", "N4"],
  ["乾かす", "kawakasu", "かわかす", "Mengeringkan", "ドライヤーで髪を乾かします。", "Mengeringkan rambut dengan hair dryer.", "N4"],
  ["濡れる", "nureru", "ぬれる", "Basah terkena air", "雨で服が濡れました。", "Pakaian basah terkena hujan.", "N4"],
  ["濡らす", "nurasu", "ぬらす", "Membasahi", "タオルを水で濡らします。", "Membasahi handuk dengan air.", "N4"],
  ["滑る", "suberu", "すべる", "Tergelincir / Licin", "雪道で滑りました。", "Tergelincir di jalan bersalju.", "N4"],
  ["転ぶ", "korobu", "ころぶ", "Tersandung jatuh", "道で転びました。", "Jatuh tersandung di jalan.", "N4"],
  ["ぶつかる", "butsukaru", "ぶつかる", "Menabrak / Bertabrakan", "壁にぶつかりました。", "Menabrak dinding.", "N4"],
  ["折る", "oru", "おる", "Mematahkan / Melipat", "紙を半分に折ります。", "Melipat kertas jadi dua bagian.", "N4"],
  ["折れる", "oreru", "おれる", "Patah (cabang/tulang)", "木の枝が折れました。", "Dahan pohon patah.", "N4"],
  ["破る", "yaburu", "やぶる", "Merobek kertas", "紙を破りました。", "Merobek kertas.", "N4"],
  ["破れる", "yabureru", "やぶれる", "Robek", "服が破れました。", "Bajunya robek.", "N4"],
  ["切れる", "kireru", "きれる", "Putus (tali) / Habis daya", "電池が切れました。", "Baterainya habis.", "N4"],
  ["外れる", "hazureru", "はずれる", "Terlepas / Melenceng", "ボタンが外れました。", "Kancingnya terlepas.", "N4"],
  ["外す", "hazusu", "はずす", "Melepaskan kancing/kacamata", "眼鏡を外します。", "Melepaskan kacamata.", "N4"],
  ["詰める", "tsumeru", "つめる", "Menjejali / Mengisi padat", "弁当箱にご飯を詰めます。", "Mengisi bekal bento dengan nasi.", "N4"],
  ["空く", "suku", "すく", "Kosong / Lapang", "お腹が空きました。", "Perut saya lapar / kosong.", "N5"],
  ["渇く", "kawaku", "かわく", "Haus (tenggorokan)", "喉が渇きました。", "Tenggorokan saya haus.", "N5"],
  ["届く", "todoku", "とどく", "Terjangkau / Sampai", "手が届きません。", "Tangannya tidak sampai menggapai.", "N4"],
  ["届ける", "todokeru", "とどける", "Mengirimkan / Melaporkan", "遺失物を届けます。", "Melaporkan barang hilang.", "N4"],
  ["泊める", "tomeru", "とめる", "Menampung menginap tamu", "友達を部屋に泊めます。", "Menampung teman menginap di kamar.", "N4"],
  ["訪ねる", "tazuneru", "たずねる", "Berkunjung ke tempat/orang", "友達の家を訪ねました。", "Saya berkunjung ke rumah teman.", "N4"],
  ["訪問する", "houmon suru", "ほうもんする", "Melakukan kunjungan resmi", "取引先を訪問します。", "Mengunjungi mitra bisnis.", "N4"],
  ["迎える", "mukaeru", "むかえる", "Menyambut kedatangan", "新年を迎えます。", "Menyambut tahun baru.", "N4"],
  ["見送る", "miokuru", "みおくる", "Melepas / Mengantarkan", "客を見送ります。", "Mengantar kepulangan tamu.", "N4"],
  ["見つめる", "mitsumeru", "みつめる", "Menatap tajam", "夜空を見つめます。", "Menatap langit malam.", "N4"],
  ["見上げる", "miageru", "みあげる", "Mendongak melihat ke atas", "高いビルを見上げます。", "Mendongak melihat gedung pencakar langit.", "N4"],
  ["見下ろす", "miorosu", "みおろす", "Melihat ke bawah", "展望台から街を見下ろします。", "Melihat kota dari dek observasi.", "N4"],
  ["振り返る", "furikaeru", "ふりかえる", "Menoleh ke belakang / Merenungkan", "後ろを振り返りました。", "Menoleh ke belakang.", "N4"],
  ["通り過ぎる", "toorisugiru", "とおりすぎる", "Melewati / Lewat begitu saja", "駅を通り過ぎました。", "Kereta melewati stasiun.", "N4"],
  ["追いかける", "oikakeru", "おいかける", "Mengejar", "バスを追いかけます。", "Mengejar bus.", "N4"],
  ["追いつく", "oitsuku", "おいつく", "Menyusul", "走って追いつきました。", "Berlari hingga menyusulnya.", "N4"],
  ["立ち止まる", "tachidomaru", "たちどまる", "Berhenti sejenak langkah", "足をとめて立ち止まりました。", "Menghentikan langkah kaki sejenak.", "N4"],
  ["飛び出す", "tobidasu", "とびだす", "Melompat keluar tiba-tiba", "道路に飛び出してはいけません。", "Jangan melompat tiba-tiba ke jalan raya.", "N4"],
  ["転勤する", "tenkin suru", "てんきんする", "Mutasi kerja dinas", "大阪へ転勤します。", "Mutasi dinas ke Osaka.", "N4"],
  ["留学する", "ryuugaku suru", "りゅうがくする", "Studi ke luar negeri", "日本に留学します。", "Kuliah studi di Jepang.", "N5"],
  ["卒業する", "sotsugyou suru", "そつぎょうする", "Lulus sekolah / kuliah", "大学を卒業しました。", "Lulus dari universitas.", "N5"],
  ["進学する", "shingaku suru", "しんがくする", "Melanjutkan jenjang sekolah", "大学院に進学します。", "Melanjutkan studi ke pascasarjana.", "N4"],
  ["就職する", "shuushoku suru", "しゅうしょくする", "Mendapatkan pekerjaan / Masuk kerja", "日本のIT企業に就職しました。", "Bekerja di perusahaan IT Jepang.", "N4"],
  ["退職する", "taishoku suru", "たいしょくする", "Pensiun / Berhenti kerja", "来年退職します。", "Pensiun tahun depan.", "N4"],
  ["通勤する", "tsuukin suru", "つうきんする", "Berangkat-pulang kerja", "電車で通勤しています。", "Pergi kerja naik kereta komuter.", "N4"],
  ["通学する", "tsuugaku suru", "つうがくする", "Berangkat-pulang sekolah", "自転車で通学します。", "Pergi sekolah naik sepeda.", "N4"],
  ["相談に乗る", "soudan ni noru", "そうだんにのる", "Memberikan saran konsultasi", "親身に相談に乗ってくれました。", "Memberikan saran dengan tulus hati.", "N4"],
  ["力を合わせる", "chikara o awaseru", "ちからをあわせる", "Menyatukan kekuatan / Bekerja sama", "力を合わせて頑張りましょう。", "Mari kita satukan kekuatan dan berjuang bersama.", "N4"]
];

for (const v of verbs) {
  add(v[0], v[1], v[2], v[3], v[4], v[5], v[6], "kata_kerja");
}

console.log("Verbs added:", vocabData.length);
