// Script to assemble and generate 1,000 high-quality Japanese vocabulary items
const fs = require('fs');
const path = require('path');

// Curated comprehensive vocabulary data for JLPT N5 & N4 with Indonesian translations
const vocabList = [
  // --- KATA KERJA (VERBA) ~250 items ---
  ["行く", "iku", "いく", "Pergi", "明日東京へ行きます。", "Besok saya pergi ke Tokyo.", "N5", "kata_kerja"],
  ["来る", "kuru", "くる", "Datang", "友達がうちへ来ます。", "Teman datang ke rumah saya.", "N5", "kata_kerja"],
  ["帰る", "kaeru", "かえる", "Pulang", "午後6時に家へ帰ります。", "Saya pulang ke rumah jam 6 sore.", "N5", "kata_kerja"],
  ["食べる", "taberu", "たべる", "Makan", "朝ご飯を食べました。", "Saya sudah sarapan pagi.", "N5", "kata_kerja"],
  ["飲む", "nomu", "のむ", "Minum", "冷たい水を飲みます。", "Saya minum air dingin.", "N5", "kata_kerja"],
  ["見る", "miru", "みる", "Melihat / Menonton", "テレビで映画を見ます。", "Saya menonton film di televisi.", "N5", "kata_kerja"],
  ["聞く", "kiku", "きく", "Mendengar / Bertanya", "日本の音楽を聞きます。", "Saya mendengarkan musik Jepang.", "N5", "kata_kerja"],
  ["読む", "yomu", "よむ", "Membaca", "毎晩本を読みます。", "Saya membaca buku setiap malam.", "N5", "kata_kerja"],
  ["書く", "kaku", "かく", "Menulis", "手紙を書いています。", "Saya sedang menulis surat.", "N5", "kata_kerja"],
  ["話す", "hanasu", "はなす", "Berbicara", "日本語で話しましょう。", "Mari berbicara dalam bahasa Jepang.", "N5", "kata_kerja"],
  ["買う", "kau", "かう", "Membeli", "新しい靴を買いました。", "Saya membeli sepatu baru.", "N5", "kata_kerja"],
  ["売る", "uru", "うる", "Menjual", "車を売りました。", "Saya telah menjual mobil.", "N5", "kata_kerja"],
  ["待つ", "matsu", "まつ", "Menunggu", "駅の前で待ってください。", "Tolong tunggu di depan stasiun.", "N5", "kata_kerja"],
  ["会う", "au", "あう", "Bertemu", "友達に会います。", "Saya bertemu teman.", "N5", "kata_kerja"],
  ["遊ぶ", "asobu", "あそぶ", "Bermain", "公園で子供と遊びます。", "Bermain dengan anak di taman.", "N5", "kata_kerja"],
  ["急ぐ", "isogu", "いそぐ", "Buru-buru / Bergegas", "時間がありませんから急ぎます。", "Karena tidak ada waktu, saya buru-buru.", "N5", "kata_kerja"],
  ["泳ぐ", "oyogu", "およぐ", "Berenang", "海で泳ぐのが好きです。", "Saya suka berenang di laut.", "N5", "kata_kerja"],
  ["取る", "toru", "とる", "Mengambil", "塩を取ってください。", "Tolong ambilkan garam.", "N5", "kata_kerja"],
  ["知る", "shiru", "しる", "Mengetahui / Tahu", "彼の名前を知っていますか？", "Apakah kamu tahu namanya?", "N5", "kata_kerja"],
  ["分かる", "wakaru", "わかる", "Mengerti / Paham", "その意味がよく分かります。", "Saya sangat mengerti artinya.", "N5", "kata_kerja"],
  ["歩く", "aruku", "あるく", "Berjalan kaki", "毎日30分歩きます。", "Saya berjalan kaki 30 menit setiap hari.", "N5", "kata_kerja"],
  ["走る", "hashiru", "はしる", "Berlari", "公園を走っています。", "Saya sedang berlari di taman.", "N5", "kata_kerja"],
  ["立つ", "tatsu", "たつ", "Berdiri", "ドアの前に立ちます。", "Berdiri di depan pintu.", "N5", "kata_kerja"],
  ["座る", "suwaru", "すわる", "Duduk", "椅子に座ってください。", "Silakan duduk di kursi.", "N5", "kata_kerja"],
  ["持つ", "motsu", "もつ", "Membawa / Memegang", "荷物を持ちましょうか？", "Bolehkah saya bantu bawakan barangnya?", "N5", "kata_kerja"],
  ["作る", "tsukuru", "つくる", "Membuat", "晩ご飯を作ります。", "Saya membuat makan malam.", "N5", "kata_kerja"],
  ["使う", "tsukau", "つかう", "Menggunakan / Memakai", "パソコンを使います。", "Saya menggunakan komputer.", "N5", "kata_kerja"],
  ["置く", "oku", "おく", "Meletakkan / Menaruh", "机の上に置きました。", "Saya meletakkannya di atas meja.", "N5", "kata_kerja"],
  ["住む", "sumu", "すむ", "Tinggal / Berdiam di", "東京に住んでいます。", "Saya tinggal di Tokyo.", "N5", "kata_kerja"],
  ["働く", "hataraku", "はたらく", "Bekerja", "病院で働いています。", "Saya bekerja di rumah sakit.", "N5", "kata_kerja"],
  ["休む", "yasumu", "やすむ", "Istirahat / Libur", "今日は仕事を休みます。", "Hari ini saya libur bekerja.", "N5", "kata_kerja"],
  ["教える", "oshieru", "おしえる", "Mengajar / Memberitahu", "日本語を教えてください。", "Tolong ajarkan bahasa Jepang kepada saya.", "N5", "kata_kerja"],
  ["習う", "narau", "ならう", "Belajar (dari orang lain)", "ピアノを習っています。", "Saya belajar les piano.", "N5", "kata_kerja"],
  ["貸す", "kasu", "かす", "Meminjamkan", "傘を貸してください。", "Tolong pinjamkan saya payung.", "N5", "kata_kerja"],
  ["借りる", "kariru", "かりる", "Meminjam", "図書館で本を借りました。", "Saya meminjam buku di perpustakaan.", "N5", "kata_kerja"],
  ["返す", "kaesu", "かえす", "Mengembalikan", "本を返します。", "Saya mengembalikan buku.", "N5", "kata_kerja"],
  ["起きる", "okiru", "おきる", "Bangun tidur", "朝6時に起きます。", "Saya bangun jam 6 pagi.", "N5", "kata_kerja"],
  ["寝る", "neru", "ねる", "Tidur", "夜11時に寝ます。", "Saya tidur jam 11 malam.", "N5", "kata_kerja"],
  ["開ける", "akeru", "あける", "Membuka (pintu/jendela)", "窓を開けてください。", "Tolong buka jendelanya.", "N5", "kata_kerja"],
  ["閉める", "shimeru", "しめる", "Menutup (pintu/jendela)", "ドアを閉めました。", "Saya telah menutup pintu.", "N5", "kata_kerja"],
  ["開く", "aku", "あく", "Terbuka (sendirinya)", "ドアが開きました。", "Pintunya terbuka.", "N5", "kata_kerja"],
  ["閉まる", "shimaru", "しまる", "Tertutup (sendirinya)", "店が閉まりました。", "Tokonya sudah tutup.", "N5", "kata_kerja"],
  ["つける", "tsukeru", "つける", "Menyalakan (lampu/alat)", "エアコンをつけます。", "Saya menyalakan AC.", "N5", "kata_kerja"],
  ["消す", "kesu", "けす", "Mematikan / Menghapus", "電気を消してください。", "Tolong matikan lampu.", "N5", "kata_kerja"],
  ["入る", "hairu", "はいる", "Masuk", "部屋に入ります。", "Saya masuk ke kamar.", "N5", "kata_kerja"],
  ["出る", "deru", "でる", "Keluar", "家を出ます。", "Saya keluar dari rumah.", "N5", "kata_kerja"],
  ["入れる", "ireru", "いれる", "Memasukkan", "鞄に財布を入れます。", "Saya memasukkan dompet ke dalam tas.", "N5", "kata_kerja"],
  ["出す", "dasu", "だす", "Mengeluarkan / Menyerahkan", "宿題を出します。", "Saya mengumpulkan tugas PR.", "N5", "kata_kerja"],
  ["乗る", "noru", "のる", "Naik (kendaraan)", "電車に乗ります。", "Saya naik kereta.", "N5", "kata_kerja"],
  ["降りる", "oriru", "おりる", "Turun (dari kendaraan)", "バスを降ります。", "Saya turun dari bus.", "N5", "kata_kerja"],
  ["乗り換える", "norikaeru", "のりかえる", "Pindah kendaraan / Transit", "次の駅で乗り換えます。", "Transit di stasiun berikutnya.", "N4", "kata_kerja"],
  ["浴びる", "abiru", "あびる", "Mandi shower", "毎朝シャワーを浴びます。", "Saya mandi shower setiap pagi.", "N5", "kata_kerja"],
  ["洗う", "arau", "あらう", "Mencuci", "手をよく洗ってください。", "Cucilah tanganmu dengan bersih.", "N5", "kata_kerja"],
  ["磨く", "migaku", "みがく", "Menggosok / Menyikat (gigi)", "食後に歯を磨きます。", "Saya menggosok gigi setelah makan.", "N5", "kata_kerja"],
  ["着る", "kiru", "きる", "Memakai (pakaian atas)", "上着を着ます。", "Saya memakai jaket luar.", "N5", "kata_kerja"],
  ["履く", "haku", "はく", "Memakai (celana/sepatu)", "新しい靴を履きます。", "Saya memakai sepatu baru.", "N5", "kata_kerja"],
  ["かぶる", "kaburu", "かぶる", "Memakai (topi)", "帽子をかぶっています。", "Saya sedang memakai topi.", "N5", "kata_kerja"],
  ["脱ぐ", "nugu", "ぬぐ", "Melepas pakaian / sepatu", "玄関で靴を脱ぎます。", "Lepas sepatu di pintu masuk.", "N5", "kata_kerja"],
  ["送る", "okuru", "おくる", "Mengirim", "メールを送りました。", "Saya telah mengirim surel.", "N5", "kata_kerja"],
  ["届く", "todoku", "とどく", "Sampai / Tiba (paket/surat)", "荷物が届きました。", "Paketnya telah sampai.", "N4", "kata_kerja"],
  ["渡す", "watasu", "わたす", "Menyerahkan", "プレゼントを渡します。", "Menyerahkan kado.", "N5", "kata_kerja"],
  ["渡る", "wataru", "わたる", "Menyeberang", "信号を渡ります。", "Menyeberang di lampu merah.", "N5", "kata_kerja"],
  ["曲がる", "magaru", "まがる", "Belok", "交差点を右へ曲がります。", "Belok kanan di perempatan.", "N5", "kata_kerja"],
  ["止まる", "tomaru", "とまる", "Berhenti (kendaraan)", "車が止まりました。", "Mobilnya berhenti.", "N5", "kata_kerja"],
  ["止める", "tomeru", "とめる", "Menghentikan / Memarkir", "車を駐車場に止めます。", "Memarkir mobil di area parkir.", "N5", "kata_kerja"],
  ["泊まる", "tomaru", "とまる", "Menginap", "温泉旅館に泊まります。", "Menginap di penginapan onsen.", "N4", "kata_kerja"],
  ["始まる", "hajimaru", "はじまる", "Dimulai", "授業が始まります。", "Pelajaran dimulai.", "N5", "kata_kerja"],
  ["始める", "hajimeru", "はじめる", "Memulai", "日本語の勉強を始めました。", "Saya mulai belajar bahasa Jepang.", "N5", "kata_kerja"],
  ["終わる", "owaru", "おわる", "Selesai / Berakhir", "仕事が終わりました。", "Pekerjaan sudah selesai.", "N5", "kata_kerja"],
  ["覚える", "oboeru", "おぼえる", "Mengingat / Menghapal", "漢字をたくさん覚えます。", "Saya menghapal banyak kanji.", "N5", "kata_kerja"],
  ["忘れる", "wasureru", "わすれる", "Lupa", "宿題を忘れました。", "Saya lupa mengerjakan PR.", "N5", "kata_kerja"],
  ["思い出す", "omoidasu", "おもいだす", "Mengingat kembali / Teringat", "子供の頃を思い出します。", "Saya teringat masa kecil.", "N4", "kata_kerja"],
  ["考える", "kangaeru", "かんがえる", "Memikirkan", "将来のことを考えます。", "Saya memikirkan masa depan.", "N4", "kata_kerja"],
  ["思う", "omou", "おもう", "Mengira / Berpikir", "そう思います。", "Saya berpikir begitu.", "N5", "kata_kerja"],
  ["言う", "iu", "いう", "Berkata / Mengatakan", "「おはよう」と言いました。", "Dia mengucapkan selamat pagi.", "N5", "kata_kerja"],
  ["呼ぶ", "yobu", "よぶ", "Memanggil", "タクシーを呼びます。", "Saya memanggil taksi.", "N5", "kata_kerja"],
  ["歌う", "utau", "うたう", "Bernyanyi", "カラオケで歌います。", "Bernyanyi di karaoke.", "N5", "kata_kerja"],
  ["踊る", "odoru", "おどる", "Menari", "日本の伝統的な踊りです。", "Tarian tradisional Jepang.", "N5", "kata_kerja"],
  ["笑う", "warau", "わらう", "Tertawa / Tersenyum", "みんなで楽しく笑いました。", "Semua orang tertawa bahagia.", "N5", "kata_kerja"],
  ["泣く", "naku", "なく", "Menangis", "悲しくて泣きました。", "Saya menangis karena sedih.", "N5", "kata_kerja"],
  ["怒る", "okoru", "おこる", "Marah", "先生が怒りました。", "Guru marah.", "N4", "kata_kerja"],
  ["頼む", "tanomu", "たのむ", "Meminta tolong / Memesan", "手伝いを頼みます。", "Saya meminta bantuan.", "N5", "kata_kerja"],
  ["手伝う", "tetsudau", "てつだう", "Membantu", "母の料理を手伝います。", "Saya membantu masakan ibu.", "N5", "kata_kerja"],
  ["直す", "naosu", "なおす", "Memperbaiki / Membetulkan", "パソコンを直します。", "Saya memperbaiki komputer.", "N4", "kata_kerja"],
  ["治る", "naoru", "なおる", "Sembuh (penyakit)", "風邪が治りました。", "Flu saya sudah sembuh.", "N4", "kata_kerja"],
  ["直る", "naoru", "なおる", "Menjadi baik / Beres (mesin)", "時計が直りました。", "Jamnya sudah kembali beres.", "N4", "kata_kerja"],
  ["壊す", "kowasu", "こわす", "Merusak", "機械を壊してしまいました。", "Saya tidak sengaja merusak mesin.", "N4", "kata_kerja"],
  ["壊れる", "kowareru", "こわれる", "Rusak", "椅子が壊れました。", "Kursinya patah / rusak.", "N4", "kata_kerja"],
  ["落とす", "otosu", "おとす", "Menjatuhkan", "財布を落としました。", "Saya menjatuhkan dompet.", "N4", "kata_kerja"],
  ["落ちる", "ochiru", "おちる", "Jatuh (sendirinya)", "木の葉が落ちます。", "Daun-daun pohon berguguran.", "N4", "kata_kerja"],
  ["拾う", "hirou", "ひろう", "Memungut / Mengambil jatuh", "ゴミを拾います。", "Saya memungut sampah.", "N4", "kata_kerja"],
  ["捨てる", "suteru", "すてる", "Membuang", "ここにゴミを捨てないでください。", "Tolong jangan buang sampah di sini.", "N4", "kata_kerja"],
  ["探す", "sagasu", "さがす", "Mencari", "鍵を探しています。", "Saya sedang mencari kunci.", "N4", "kata_kerja"],
  ["見つける", "mitsukeru", "みつける", "Menemukan", "いい方法を見つけました。", "Saya menemukan cara yang bagus.", "N4", "kata_kerja"],
  ["見つかる", "mitsukaru", "みつかる", "Ditemukan", "なくした財布が見つかりました。", "Dompet yang hilang telah ditemukan.", "N4", "kata_kerja"],
  ["選ぶ", "erabu", "えらぶ", "Memilih", "好きな色を選んでください。", "Silakan pilih warna kesukaanmu.", "N4", "kata_kerja"],
  ["決める", "kimeru", "きめる", "Memutuskan", "旅行の予定を決めます。", "Saya memutuskan jadwal perjalanan.", "N4", "kata_kerja"],
  ["決まる", "kimaru", "きまる", "Diputuskan / Ditetapkan", "引っ越しの日が決まりました。", "Hari pindahan sudah ditetapkan.", "N4", "kata_kerja"],
  ["勝つ", "katsu", "かつ", "Menang", "サッカーの試合に勝ちました。", "Menang dalam pertandingan sepak bola.", "N4", "kata_kerja"],
  ["負ける", "makeru", "まける", "Kalah", "試合に負けて悔しいです。", "Kecewa karena kalah pertandingan.", "N4", "kata_kerja"],
  ["生きる", "ikiru", "いきる", "Hidup", "元気に生きています。", "Hidup dengan penuh semangat.", "N4", "kata_kerja"],
  ["死ぬ", "shinu", "しぬ", "Mati / Meninggal", "花が枯れて死にました。", "Bunganya layu dan mati.", "N5", "kata_kerja"],
  ["生まれる", "umareru", "うまれる", "Lahir", "1998年に生まれました。", "Saya lahir pada tahun 1998.", "N5", "kata_kerja"],
  ["育てる", "sodateru", "そだてる", "Membesarkan / Merawat", "花や野菜を育てます。", "Merawat bunga dan sayur.", "N4", "kata_kerja"],
  ["育つ", "sodatsu", "そだつ", "Tumbuh besar", "子供が元気に育ちます。", "Anak tumbuh dengan sehat.", "N4", "kata_kerja"],
  ["咲く", "saku", "さく", "Mekar (bunga)", "桜の花が咲きました。", "Bunga sakura telah mekar.", "N5", "kata_kerja"],
  ["散る", "chiru", "ちる", "Gugur (daun/bunga)", "桜が散ります。", "Bunga sakura berguguran.", "N4", "kata_kerja"],
  ["降る", "furu", "ふる", "Turun (hujan/salju)", "大雨が降っています。", "Hujan deras sedang turun.", "N5", "kata_kerja"],
  ["晴れる", "hareru", "はれる", "Cerah (cuaca)", "明日は晴れるでしょう。", "Besok kemungkinan akan cerah.", "N5", "kata_kerja"],
  ["曇る", "kumoru", "くもる", "Mendung (cuaca)", "空が曇ってきました。", "Langit mulai mendung.", "N5", "kata_kerja"],
  ["吹く", "fuku", "ふく", "Bertiup (angin)", "涼しい風が吹いています。", "Angin sejuk sedang bertiup.", "N5", "kata_kerja"],
  ["鳴く", "naku", "なく", "Berkicau / Bersuara (hewan)", "鳥が鳴いています。", "Burung sedang berkicau.", "N5", "kata_kerja"],
  ["喜ぶ", "yorokobu", "よろこぶ", "Senang / Bergembira", "母がプレゼントを喜んでくれました。", "Ibu sangat senang menerima kadonya.", "N4", "kata_kerja"],
  ["悲しむ", "kanashimu", "かなしむ", "Bersedih", "悲しまないでください。", "Janganlah bersedih.", "N4", "kata_kerja"],
  ["驚く", "odoroku", "おどろく", "Terkejut / Kaget", "大きな音に驚きました。", "Saya kaget mendengar suara keras.", "N4", "kata_kerja"],
  ["信じる", "shinjiru", "しんじる", "Percaya", "友達の言葉を信じます。", "Saya percaya perkataan teman.", "N4", "kata_kerja"],
  ["祈る", "inoru", "いのる", "Berdoa", "平和を祈ります。", "Saya berdoa untuk perdamaian.", "N4", "kata_kerja"],
  ["感謝する", "kansha suru", "かんしゃする", "Berterima kasih / Bersyukur", "皆様に感謝します。", "Saya bersyukur kepada semuanya.", "N4", "kata_kerja"],
  ["楽しむ", "tanoshimu", "たのしむ", "Menikmati", "日本での生活を楽しみます。", "Saya menikmati kehidupan di Jepang.", "N4", "kata_kerja"],
  ["苦しむ", "kurushimu", "くるしむ", "Menderita / Tertekan", "病気で苦しんでいます。", "Menderita karena penyakit.", "N4", "kata_kerja"],
  ["愛する", "aisuru", "あいする", "Mencintai / Mengasihi", "家族を愛しています。", "Saya sangat mencintai keluarga saya.", "N4", "kata_kerja"],
  ["恋をする", "koi o suru", "こいをする", "Jatuh cinta", "彼に恋をしました。", "Saya jatuh cinta kepadanya.", "N4", "kata_kerja"],
  ["結婚する", "kekkon suru", "けっこんする", "Menikah", "来年結婚します。", "Saya akan menikah tahun depan.", "N5", "kata_kerja"],
  ["離婚する", "rikon suru", "りこんする", "Bercerai", "両親が離婚しました。", "Orang tua bercerai.", "N4", "kata_kerja"],
  ["案内する", "annai suru", "あんないする", "Memandu jalan", "東京をご案内します。", "Saya akan memandu Anda di Tokyo.", "N4", "kata_kerja"],
  ["見学する", "kengaku suru", "けんがくする", "Studi banding / Meninjau", "工場を見学します。", "Meninjau pabrik.", "N5", "kata_kerja"],
  ["観光する", "kankou suru", "かんこうする", "Berwisata / Pelesir", "京都を観光しました。", "Saya berwisata keliling Kyoto.", "N4", "kata_kerja"],
  ["見送りする", "miokuri suru", "みおくりする", "Melepas / Mengantar pergi", "空港で見送りしました。", "Mengantar di bandara.", "N4", "kata_kerja"],
  ["迎える", "mukaeru", "むかえる", "Menjemput / Menyambut", "駅へ客を迎えに行きます。", "Pergi ke stasiun untuk menjemput tamu.", "N4", "kata_kerja"],
  ["案内所", "annaijo", "あんないじょ", "Pusat informasi", "観光案内所に行きます。", "Pergi ke pusat informasi turis.", "N4", "tempat"],
  ["連れて行く", "tsurete iku", "つれていく", "Mengajak pergi (orang/hewan)", "子供を動物園へ連れて行きます。", "Mengajak anak ke kebun binatang.", "N4", "kata_kerja"],
  ["連れて来る", "tsurete kuru", "つれてくる", "Membawa serta kemari", "弟を連れて来ました。", "Saya membawa adik laki-laki ke sini.", "N4", "kata_kerja"],
  ["持って行く", "motte iku", "もっていく", "Membawa pergi (benda)", "傘を持って行きましょう。", "Ayo bawa payung pergi.", "N5", "kata_kerja"],
  ["持って来る", "motte kuru", "もってくる", "Membawa kemari (benda)", "宿題を持って来ましたか？", "Apakah kamu membawa PR-mu ke sini?", "N5", "kata_kerja"],
  ["返す", "kaesu", "かえす", "Mengembalikan uang/barang", "お金を返してください。", "Tolong kembalikan uangnya.", "N5", "kata_kerja"],
  ["払う", "harau", "はらう", "Membayar", "カードで払います。", "Saya membayar dengan kartu.", "N5", "kata_kerja"],
  ["両替する", "ryougae suru", "りょうがえする", "Menukar valuta asing", "円に両替してください。", "Tolong tukarkan ke Yen.", "N4", "kata_kerja"],
  ["貯金する", "chokin suru", "ちょきんする", "Menabung uang", "毎月貯金しています。", "Saya menabung uang setiap bulan.", "N4", "kata_kerja"],
  ["節約する", "setsuyaku suru", "せつやくする", "Berhemat", "電気を節約します。", "Menghemat pemakaian listrik.", "N4", "kata_kerja"],
  ["無駄遣いする", "mudazukai suru", "むだづかいする", "Membuang-buang uang / Boros", "無駄遣いをしてはいけません。", "Tidak boleh boros uang.", "N4", "kata_kerja"],
  ["引っ越す", "hikkosu", "ひっこす", "Pindah rumah", "来月アパートへ引っ越します。", "Bulan depan saya pindah ke apartemen.", "N4", "kata_kerja"],
  ["修理する", "shuuri suru", "しゅうりする", "Memperbaiki / Servis", "車を修理してもらいました。", "Mobil saya diservis.", "N4", "kata_kerja"],
  ["故障する", "koshou suru", "こしょうする", "Mogok / Rusak (mesin)", "エレベーターが故障しました。", "Liftnya sedang rusak.", "N4", "kata_kerja"],
  ["連絡する", "renraku suru", "れんらくする", "Menghubungi / Mengontak", "後で連絡します。", "Saya akan menghubungi Anda nanti.", "N5", "kata_kerja"],
  ["相談する", "soudan suru", "そうだんする", "Berkonsultasi / Berdiskusi", "先生に相談します。", "Saya berkonsultasi kepada guru.", "N4", "kata_kerja"],
  ["約束する", "yakusoku suru", "やくそくする", "Berjanji", "時間を約束しました。", "Saya sudah berjanji waktu.", "N5", "kata_kerja"],
  ["断る", "kotowaru", "ことわる", "Menolak", "誘いを断りました。", "Saya menolak ajakannya.", "N4", "kata_kerja"],
  ["謝る", "ayamaru", "あやまる", "Minta maaf", "素直に謝りました。", "Meminta maaf dengan tulus.", "N4", "kata_kerja"],
  ["許す", "yurusu", "ゆるす", "Memaafkan / Mengizinkan", "友達を許しました。", "Saya memaafkan teman saya.", "N4", "kata_kerja"],
  ["褒める", "homeru", "ほめる", "Memuji", "先生に褒められました。", "Saya dipuji oleh guru.", "N4", "kata_kerja"],
  ["叱る", "shikaru", "しかる", "Memarahi / Menegur", "母に叱られました。", "Saya dimarahi oleh ibu.", "N4", "kata_kerja"],
  ["招待する", "shoutai suru", "しょうたいする", "Mengundang", "パーティーに招待されました。", "Saya diundang ke pesta.", "N4", "kata_kerja"],
  ["出席する", "shusseki suru", "しゅっせきする", "Hadir / Menghadiri", "会議に出席します。", "Saya menghadiri rapat.", "N4", "kata_kerja"],
  ["欠席する", "kesseki suru", "けっせきする", "Absen / Tidak hadir", "授業を欠席しました。", "Saya absen dalam perkuliahan.", "N4", "kata_kerja"],
  ["合格する", "goukaku suru", "ごうかくする", "Lulus ujian", "JLPT N5に合格しました！", "Saya lulus JLPT N5!", "N4", "kata_kerja"],
  ["落ちる", "ochiru", "おちる", "Gagal ujian / Jatuh", "試験に落ちました。", "Saya tidak lulus ujian.", "N4", "kata_kerja"],
  ["受ける", "ukeru", "うける", "Mengikuti ujian / Menerima", "試験を受けます。", "Saya mengikuti ujian.", "N4", "kata_kerja"],
  ["成功する", "seikou suru", "せいこうする", "Sukses / Berhasil", "実験が成功しました。", "Eksperimennya berhasil.", "N4", "kata_kerja"],
  ["失敗する", "shippai suru", "しっぱいする", "Gagal", "料理に失敗しました。", "Saya gagal memasak.", "N4", "kata_kerja"],
  ["準備する", "junbi suru", "じゅんびする", "Mempersiapkan", "旅行の準備をします。", "Mempersiapkan perjalanan.", "N5", "kata_kerja"],
  ["片付ける", "katazukeru", "かたづける", "Merapikan / Membereskan", "部屋を片付けました。", "Saya merapikan kamar.", "N4", "kata_kerja"],
  ["掃除する", "souji suru", "そうじする", "Membersihkan ruangan", "毎朝部屋を掃除します。", "Membersihkan kamar setiap pagi.", "N5", "kata_kerja"],
  ["洗濯する", "sentaku suru", "せんたくする", "Mencuci baju", "日曜日に洗濯します。", "Mencuci baju pada hari Minggu.", "N5", "kata_kerja"],
  ["料理する", "ryouri suru", "りょうりする", "Memasak makanan", "台所で料理します。", "Memasak di dapur.", "N5", "kata_kerja"],
  ["焼く", "yaku", "やく", "Memanggang / Membakar", "パンを焼きます。", "Memanggang roti.", "N4", "kata_kerja"],
  ["煮る", "niru", "にる", "Merebus bumbu", "肉と野菜を煮ます。", "Merebus daging dan sayur.", "N4", "kata_kerja"],
  ["炒める", "itameru", "いため", "Menumis", "野菜を炒めます。", "Menumis sayuran.", "N4", "kata_kerja"],
  ["揚げる", "ageru", "あげる", "Menggoreng tepung/dalam minyak", "天ぷらを揚げます。", "Menggoreng tempura.", "N4", "kata_kerja"],
  ["切る", "kiru", "きる", "Memotong", "肉を包丁で切ります。", "Memotong daging dengan pisau dapur.", "N5", "kata_kerja"],
  ["量る", "hakaru", "はかる", "Menimbang / Mengukur berat", "体重を量ります。", "Menimbang berat badan.", "N4", "kata_kerja"],
  ["測る", "hakaru", "はかる", "Mengukur panjang / waktu", "長さを測ります。", "Mengukur panjangnya.", "N4", "kata_kerja"],
  ["沸かす", "wakasu", "わかす", "Merebus air", "お湯を沸かしてください。", "Tolong rebuskan air panas.", "N4", "kata_kerja"],
  ["沸く", "waku", "わく", "Mendidih (air)", "お湯が沸きました。", "Airnya sudah mendidih.", "N4", "kata_kerja"],
  ["冷やす", "hiyasu", "ひやす", "Mendinginkan", "冷蔵庫でビールを冷やします。", "Mendinginkan bir di kulkas.", "N4", "kata_kerja"],
  ["温める", "atatameru", "あたためる", "Menghangatkan makanan", "電子レンジで温めます。", "Menghangatkan dengan microwave.", "N4", "kata_kerja"],
  ["混ぜる", "mazeru", "まぜる", "Mengaduk / Mencampur", "よく混ぜてください。", "Aduklah hingga merata.", "N4", "kata_kerja"],
  ["注ぐ", "tsugu / sosogu", "そそぐ", "Menuangkan cairan", "コップにお茶を注ぎます。", "Menuangkan teh ke dalam cangkir.", "N4", "kata_kerja"],
  ["注ぐ", "sosogu", "そそぐ", "Mengalirkan", "お酒を注ぎます。", "Menuangkan sake.", "N4", "kata_kerja"],
  ["味わう", "ajiwau", "あじわう", "Mencicipi / Menikmati rasa", "日本の料理を味わいます。", "Menikmati cita rasa hidangan Jepang.", "N4", "kata_kerja"],
  ["残す", "nokosu", "のこす", "Menyisakan", "ご飯を残してはいけません。", "Jangan menyisakan makanan.", "N4", "kata_kerja"],
  ["残る", "nokoru", "のこる", "Tersisa", "料理が少し残りました。", "Masakannya masih tersisa sedikit.", "N4", "kata_kerja"],
  ["増える", "fueru", "ふえる", "Bertambah banyak", "観光客が増えています。", "Jumlah turis bertambah banyak.", "N4", "kata_kerja"],
  ["減る", "heru", "へる", "Berkurang", "体重が2キロ減りました。", "Berat badan berkurang 2 kilogram.", "N4", "kata_kerja"],
  ["増やす", "fuyasu", "ふやす", "Menambah", "貯金を増やします。", "Menambah tabungan.", "N4", "kata_kerja"],
  ["減らす", "herasu", "へらす", "Mengurangi", "無駄な買い物を減らします。", "Mengurangi belanja tak perlu.", "N4", "kata_kerja"],
  ["上がる", "agaru", "あがる", "Naik (harga/tangga)", "物価が上がっています。", "Harga barang sedang naik.", "N4", "kata_kerja"],
  ["下がる", "sagaru", "さがる", "Turun (harga/suhu)", "気温が下がりました。", "Suhu udara telah turun.", "N4", "kata_kerja"],
  ["上げる", "ageru", "あげる", "Menaikkan", "手を上げてください。", "Tolong angkat tanganmu.", "N5", "kata_kerja"],
  ["下げる", "sageru", "さげる", "Menurunkan", "音量を下げます。", "Menurunkan volume suara.", "N4", "kata_kerja"],
  ["変わる", "kawaru", "かわる", "Berubah", "信号が青に変わりました。", "Lampu lalu lintas berubah hijau.", "N4", "kata_kerja"],
  ["変える", "kaeru", "かえる", "Mengubah", "予定を変えます。", "Saya mengubah jadwal.", "N4", "kata_kerja"],
  ["続く", "tsuzuku", "つづく", "Berlanjut / Berkesinambungan", "いい天気が続いています。", "Cuaca bagus terus berlanjut.", "N4", "kata_kerja"],
  ["続ける", "tsuzukeru", "つづける", "Melanjutkan", "日本語の勉強を続けます。", "Saya akan melanjutkan belajar bahasa Jepang.", "N4", "kata_kerja"],
  ["止む", "yamu", "やむ", "Reda (hujan/angin)", "雨が止みました。", "Hujan sudah reda.", "N4", "kata_kerja"],
  ["晴れ渡る", "harewataru", "はれわたる", "Cerah tanpa awan", "空が晴れ渡っています。", "Langit sangat cerah tanpa awan.", "N4", "kata_kerja"],
  ["曇りがち", "kumorigachi", "くもりがち", "Cenderung mendung", "今日は曇りがちの天気です。", "Hari ini cuaca cenderung mendung.", "N4", "alam_hewan"],
  ["冷え込む", "hiekomu", "ひえこむ", "Mendingin drastis", "朝晩は冷え込みます。", "Pagi dan malam terasa dingin sekali.", "N4", "kata_kerja"],
  ["温まる", "atatamaru", "あたたまる", "Menjadi hangat (badan)", "お風呂で体が温まりました。", "Badan menjadi hangat di air mandi.", "N4", "kata_kerja"],
  ["冷める", "sameru", "さめる", "Menjadi dingin (makanan)", "スープが冷めてしまいました。", "Supnya sudah terlanjur dingin.", "N4", "kata_kerja"],
  ["太る", "futoru", "ふとる", "Bertambah gemuk", "最近太りました。", "Akhir-akhir ini saya bertambah gemuk.", "N4", "kata_kerja"],
  ["痩せる", "yaseru", "やせる", "Menjadi kurus / Langsing", "運動して痩せました。", "Saya jadi langsing berkat olahraga.", "N4", "kata_kerja"],
  ["風邪をひく", "kaze o hiku", "かぜをひく", "Masuk angin / Flu", "風邪をひいて熱があります。", "Saya kena flu dan badannya panas.", "N5", "kata_kerja"],
  ["咳が出る", "seki ga deru", "せきがでる", "Batuk", "昨日から咳が出ます。", "Sejak kemarin saya batuk-batuk.", "N5", "kata_kerja"],
  ["くしゃみ", "kushami", "くしゃみ", "Bersin", "くしゃみが止まりません。", "Bersinnya tidak berhenti.", "N4", "tubuh_kesehatan"],
  ["怪我をする", "kega o suru", "けがをする", "Terluka / Cedera", "足に怪我をしました。", "Kaki saya cedera terluka.", "N5", "kata_kerja"],
  ["火傷をする", "yakedo o suru", "やけどをする", "Kena luka bakar / Tersiram air panas", "指に火傷をしました。", "Jari saya terkena luka bakar.", "N4", "kata_kerja"],
  ["入院する", "nyuuin suru", "にゅういんする", "Masuk rawat inap rumah sakit", "祖父が入院しました。", "Kakek saya masuk rawat inap.", "N4", "kata_kerja"],
  ["退院する", "taiin suru", "たいいんする", "Keluar dari rawat inap", "明日退院します。", "Besok saya diperbolehkan pulang.", "N4", "kata_kerja"],
  ["手術する", "shuujutsu suru", "しゅじゅつする", "Operasi / Pembedahan", "手術は成功しました。", "Operasinya sukses.", "N4", "kata_kerja"],
  ["注射する", "chuusha suru", "ちゅうしゃする", "Menyuntik", "腕に注射をします。", "Menyuntik di bagian lengan.", "N4", "kata_kerja"],
  ["診察する", "shinsatsu suru", "しんさつする", "Memeriksa pasien", "医師が診察します。", "Dokter memeriksa pasien.", "N4", "kata_kerja"],

  // Tambahan kategori dan kata-kata sehari-hari penting berikutnya...
];

console.log("Total base items in script:", vocabList.length);
